### ISSUE TITLE
ClassNotFoundException: OrderOpcControllerCore

### ISSUE THREAD

**Issue by Torrentus** [mollie/PrestaShop#105]
### Expected behavior
Configuration page shows up. 

### Actual behavior
![image](https://user-images.githubusercontent.com/3865006/52888234-43381c80-317b-11e9-90df-baa82c68075c.png)

## Log
Level | Channel | Message
-- | -- | --
DEBUG23:39:09 | doctrine | SELECT name FROM pr_module WHERE active = 1
CRITICAL23:39:09 | php | Fatal Error: Class 'OrderOpcControllerCore' not found
DEBUG23:39:09 | doctrine | SELECT name FROM pr_module WHERE active = 1
CRITICAL23:39:09 | request | Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "OrderOpcControllerCore" from the global namespace. Did you forget a "use" statement?" at /home/u47320p43168/domains/domainname.nl/public_html/vimexx/override/controllers/front/OrderOpcController.php line 2

### Steps to reproduce the behavior
Migrated to 1.7.5.0 using 1-click-upgrade, but deïnstalled all modules (by deleting 'modules' folder) and reïnstalled the modules from clean 1.7.5.0 install. Then tried to reïnstall newest version of Mollie (3.3.5) but get _'Attempted to load class "OrderOpcControllerCore" from the global namespace.
Did you forget a "use" statement?'_ when trying to access the configuration page of the module.

**If I install the older version that I also used in prestashop 1.6, version 3.1.0, then configuration page shows up fine.**

### Environment
* PrestaShop version: 1.7.5.0
* Mollie module version: 3.3.5 
* PHP version: 7.0.33

**Comment by Torrentus** [comment]
Release 3.2.0 also works, the issue starts to appear from 3.3.0 onwards.

**Comment by firstred** [comment]
Hi @Torrentus,

What versions did you upgrade from?
Have you also checked the `/overrides` folder for the `OrderOpcController.php` file? This sounds like a leftover from PrestaShop 1.6. PrestaShop 1.7 does not have this file.

**Comment by Torrentus** [comment]
OrderOpcControllerCore turned out to be remains from an older version of the MyParcel module. Deleted the files in the overrides folder and that solved this issue.

**Comment by firstred** [comment]
Great to hear! Good luck with the migration!

**Comment by losiadly** [comment]
@Torrentus Hi, i have the same problem, can u tell mi where i have to delete files? best regards
