### ISSUE TITLE
Order isn't created in the backoffice after succesfull payment

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop#107]
### Expected behavior
After a customer has paid using the Mollie API a order should be created in the backoffice of Prestashop

### Actual behavior
There is no order created in the backoffice with a error in the log that looks like this:  Mollie::validateMollieOrder - Order cannot be created

### Steps to reproduce the behavior
Hard to reproduce it only occurs sometimes.

### Environment
* PrestaShop version: 16.1.23
* Mollie module version: 3.3.5
* PHP version: Current PHP version: 7.0.33

**Comment by 30knees** [comment]
This happened to me, too. For me, it was for PayPal via Mollie. 

A customer wrote asking about her order number XYZ. She said she paid by PayPal but didn't get any order confirmation from us.

I checked and couldn't find an order in her name. She then forwarded me the PayPal confirmation email. It references an actual order in our shop that belongs to another customer. I can see the PayPal transaction in PayPal, but not in our shop.

**Comment by Maikel726** [comment]
> 
> 
> This happened to me, too, with a PayPal via Mollie order.
> 
> A customer wrote asking about her order number XYZ. She said she paid by PayPal but didn't get any order confirmation from us.
> 
> I checked and couldn't find an order in her name. She then forwarded me the PayPal confirmation email. It references an actual order in our shop that belongs to another customer. I can see the PayPal transaction in PayPal, but not in our shop.

Yes i think also that's the reason why the order isn't created because the orders have the same order number, one order will be created with that number or what you have configured. But the other order will not be created and you have to check your Mollie backoffice to see that there exactly was a successful payment
