### ISSUE TITLE
Double orders issue

### ISSUE THREAD

**Issue by wouterb038** [mollie/PrestaShop#108]
**Expected behavior**
After a customer has paid using the Mollie Payment module then 1 order must be created.

**Actual behavior**
Most orders are created properly. But we have already seen 3x on different PrestaShops that sometimes an order is created 2x. A few important notes:

- We noticed that the double orders were all paid via Rabobank. (betalen.rabobank.nl)
- The first order has a transaction ID, the second does not.
- The 2 double orders have exactly the same times.
- The 2 orders have the same CART ID
- The 2 orders both have their own ORDER ID

**Environment**
    PrestaShop version: 16.1.23 / 1.7.5.1
    Mollie module version: 3.3.5
    PHP version: Current PHP version: 5.6.40 / 7.2.2

**Comment by snowycatsoftware** [comment]
Hi @wouterb038 ,

Unfortunately Prestashop's order validation is prone to race conditions so this may happen from time to time. We're still looking for ways to minimize this problem. One (partial) solution you could try right now is to add a UNIQUE constraint to the `reference`column of the `ps_orders` table (replace `ps_` with your own prefix).

Kind regards
