### ISSUE TITLE
firstred/mollie-api-php is no longer available

### ISSUE THREAD

**Issue by njdarda** [mollie/PrestaShop#109]
### Expected behavior
Being able to run composer install.

### Actual behavior
While running composer install i get:
```
  Problem 1
    - Installation request for mollie/prestashop @dev -> satisfiable by mollie/prestashop[dev-master].
    - mollie/prestashop dev-master requires firstred/mollie-api-php ^2.7.0 -> no matching package found.
```
The dependency you use is no longer there:
https://github.com/firstred/mollie-api-php

### Steps to reproduce the behavior
Clone the repo and run `composer install` inside it 

### Environment
* PrestaShop version: 1.6.1.23
* Mollie module version: 3.4.0
* PHP version: 7.2

**Comment by margud** [comment]
This bug was fixed in new release. Try upgrading to [3.4.3](https://github.com/mollie/PrestaShop/releases/tag/3.4.3) version
