### ISSUE TITLE
Orders not set to backorder if product out of stock

### ISSUE THREAD

**Issue by Torrentus** [mollie/PrestaShop#110]
### Expected behavior
After an order is created and one or more items contained in the order are out of stock, the status of the order should be set to 'PS_OS_OUTOFSTOCK_PAID' or  'PS_OS_OUTOFSTOCK_UNPAID' depending on the completion of the payment.

### Actual behavior
After an order is created, the status is set to 'Payment accepted' and/or 'Waiting for bank transaction' even if the products in the order are out of stock. 

### Steps to reproduce the behavior
My shop is an upgraded store from 1.6.x to 1.7.5; this upgrade path has led to some 'stock'-issues before, so this might not be reproducable on a fresh install (did not test), still imporant to solve I believe. 

### Environment
* PrestaShop version: 1.7.5.1
* Mollie module version: 3.3.5
* PHP version: 7.2.17

### Suggestions

I found that in Prestashop/classes/PaymentModule.php of prestashop 1.7.5, this is done:

```php
// Set the order status
                    $new_history = new OrderHistory();
                    $new_history->id_order = (int) $order->id;
                    $new_history->changeIdOrderState((int) $id_order_state, $order, true);
                    $new_history->addWithemail(true, $extra_vars);
                    // Switch to back order if needed
                    if (Configuration::get('PS_STOCK_MANAGEMENT') &&
                            ($order_detail->getStockState() ||
                            $order_detail->product_quantity_in_stock < 0)) {
                        $history = new OrderHistory();
                        $history->id_order = (int) $order->id;
                        $history->changeIdOrderState(Configuration::get($order->hasBeenPaid() ? 'PS_OS_OUTOFSTOCK_PAID' : 'PS_OS_OUTOFSTOCK_UNPAID'), $order, true);
                        $history->addWithemail();
                    }
                    unset($order_detail);
                    // Order is reloaded because the status just changed
                    $order = new Order((int) $order->id);
```

But in mollie.php, this happens instead:
```php
 // Set the order status
                    $this->setOrderStatus($order->id, $idOrderState, true, $extraVars);
                    // Switch to back order if needed
                    if (Configuration::get('PS_STOCK_MANAGEMENT') &&
                        ($orderDetail->getStockState() || $orderDetail->product_quantity_in_stock < 0)
                    ) {
                        $this->setOrderStatus($order, Configuration::get($order->valid ? 'PS_OS_OUTOFSTOCK_PAID' : 'PS_OS_OUTOFSTOCK_UNPAID'), true, $extraVars);
                    }
                    unset($orderDetail);
                    // Order is reloaded because the status just changed
                    $order = new Order((int) $order->id);
```

And suspect that mollie.php might have to be updated to perform the same logic as Prestashop core file?

**Comment by Torrentus** [comment]
I forgot to mention that the statusses work correctly if I manually create an order in the backend (and thus do not use the mollie plugin).

**Comment by snowycatsoftware** [comment]
Hi @Torrentus ,

Thank you for taking the time to reporting this issue. We are currently working on new version of the Mollie module. We will take this into account.

We will inform you as soon as it is released and update you on this issue.

Kind regards

**Comment by christiaan01** [comment]
We are experiencing the same issue since the latest update.

Prestashop 1.6.1.17
Mollie 3.3.5
PHP 7.0.32

**Comment by Torrentus** [comment]
Any news?

**Comment by ArturasInvertus** [comment]
Hi @Torrentus ,

New Mollie module was released and the feature is include.

Best regards

**Comment by Torrentus** [comment]
Hi Arturas, great, thank you :-)
