### ISSUE TITLE
Order ID not showing in order confirmation email

### ISSUE THREAD

**Issue by christiaan01** [mollie/PrestaShop#111]
Since the latest Mollie update (3.3.5) the variable {id_order} does not show up in the order confirmation e-mail. The same goes for the {delay} variable. 

When using other payment methods than Mollie, the variables are displayed correctly.

Prestashop 1.6.1.17
Mollie 3.3.5
PHP 7.0.32

**Comment by margud** [comment]
Try upgrading module to [3.4.3](https://github.com/mollie/PrestaShop/releases/tag/3.4.3) version. This issue should have been fixed in this version.
