### ISSUE TITLE
Payments with mobile devices not possible - checkout redirects always to homepage if mollie module is activated

### ISSUE THREAD

**Issue by didi-2018** [mollie/PrestaShop#112]
Hi, if Mollie module is enabled the costumer is always redirected to homepage before he/she can choose any payment in checkout. All steps in checkout are working till choosing the shipping method and then he/she will be redirected to homepage. This behavior is only on mobile devices. If the Mollie module is disabled the checkout works perfekt! 

I contacted you last week wednesday on Prestashop Addons and I got no answer. I contacted you again on friday last week on Prestashop Addons too and by phone and I still got no answer! I have lost so many order cause no customers can order anymore! 

It really needs to be fixed urgent!! Please answer my messages on Prestashop Addons! There you will find all access datas!  I can not loose more orders! 

PS 1.7.5.1
Mollie 3.3.5

**Comment by margud** [comment]
Try installing 3.4.4 Mollie version. If you still get this issue create new issue or reopen this one.
