### ISSUE TITLE
Customers never reach mollie payments portal

### ISSUE THREAD

**Issue by reestyle-it** [mollie/PrestaShop#115]
### Expected behavior
A customer should reach the mollie payment portal for ideal and other NL-foreign payment methods.

### Actual behavior
In certain cases the customer never reaches the mollie payment portal.

### Steps to reproduce the behavior
Add a product to the cart and try to check out. Doesn't always occur, though with specific products in our shop it always occurs. Checked the products, but unable to find flaws there. Checking out using wiretransfer (/direct bank) will work, so to me it should have something to do with the Mollie plugin specifically.

### Environment
* PrestaShop version: 1.7.5.0 
* Mollie module version: 3.3.5
* PHP version: 7.2.19-0ubuntu0.18.04.1

**Comment by ArturasInvertus** [comment]
Could you grant backoffice access so we could investigate why in your case mollie payment is not loading?
Please don't share it publicly and send it to my email: arturas.mockus@invertus.eu
