### ISSUE TITLE
Used wrong namespcae in webhook controller 

### ISSUE THREAD

**Issue by tobias-roccomedia** [mollie/PrestaShop#117]
### Expected behavior

as you changed namespace it should be like
use Mollie\Api\Resources\Payment;

### Actual behavior

we have below use in webhook controller
use MollieModule\Mollie\Api\Resources\Payment;

### Steps to reproduce the behavior

go and check the webhook controller

### Environment
* PrestaShop version: 1.7.5.0
* Mollie module version: 3.4.0
* PHP version: 7.1.26

**Comment by margud** [comment]
It was solved in 3.4.1 release.
