### ISSUE TITLE
Apple Pay - desktop / android etc.

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop#119]
### Expected behavior
Hide Apple pay when payment is on desktop / android etc.

### Actual behavior
Payment is shown on desktop / android etc.

### Steps to reproduce the behavior
Try checkout on desktop.
Error when trying to pay on desktop (attachment screenshot)

### Environment
Tested on version 1.6.1.*

![Screenshot 2019-08-02 at 14 23 54](https://user-images.githubusercontent.com/1645341/62369902-60965280-b531-11e9-8247-1c98b45c4352.png)

**Comment by margud** [comment]
Hi @basemedia ,

For for starting using Apple Pay and reporting issue!
Apple Pay method is available only on Apple devices and it is checked by using the canMakePayments method on the window.ApplePaySession object. 

Could you please share some more details with us?

Thanks

**Comment by basemedia** [comment]
Your welcome. I am testing it on Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)
 and Firefox 68.0.1 (64-bit)(Apple Imac) and I see the payment option in the list. What kind of information do you need more?

**Comment by ArturasInvertus** [comment]
Hi @basemedia ,

If possible we would need backoffice access. We tried to reproduce issue on our side and we couldn't.  Please don't share it publicly and send it to my email: arturas.mockus@invertus.eu

Best

**Comment by basemedia** [comment]
@ArturasInvertus I will get back to you friday (short holiday now)
