### ISSUE TITLE
Improvement | Banktransfer (payent methods)

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop#122]
Possibility to select country by payment method (based on customer's country of origin)

**Comment by ArturasInvertus** [comment]
Thanks for improvement suggestion. This feature is on our roadmap but at the moment it is too early to say when it will be implemented. Will keep you posted.

**Comment by margud** [comment]
This feature has been added in [3.4.3](https://github.com/mollie/PrestaShop/releases/tag/3.4.3) release.
