### ISSUE TITLE
Table mol_country is missing after module installation

### ISSUE THREAD

**Issue by getdatakick** [mollie/PrestaShop#129]
### Expected behavior
table `mol_country` should be created during install

### Actual behavior
table `mol_country` is not created during installation

### Steps to reproduce the behavior
Install the module

### Notes

Table `mol_country` is being created as part of upgrade script for [3.4.3 version](https://github.com/mollie/PrestaShop/blob/ae9687bbbf5f7da1d9b0caceed364deedcd39ec7/upgrade/Upgrade-3.4.3.php#L47). This table is NOT created in [install.php](https://github.com/mollie/PrestaShop/blob/master/sql/install.php) script

**Comment by margud** [comment]
Thank you for reporting this issue. We indeed missed it and it will be fixed in next release.
