### ISSUE TITLE
BUG: Payment page = Blank ; Trying to get property of non-object

### ISSUE THREAD

**Issue by bitprocessor** [mollie/Prestashop#13]
Hi,

I'm test-driving a Prestashop 1.6.1.2 install with a test API-key from Mollie (ID 2126931).
Testing with the default Prestashop theme. Mollie module version: Release 1.2.2

Upon arrival on the "Payment" setup, the page becomes completely blank. 
The following errors are logged in the apache log (site-info & IP addresses removed)

[Sat Nov 21 18:41:38.701243 2015] [:error] [pid 14931] [client <info_removed>:46790] PHP Notice:  Trying to get property of non-object in /srv/www/<info_removed>/modules/mollie/mollie.php on line 875, referer: http://<info_removed>/index.php?controller=order

[Sat Nov 21 18:41:38.701295 2015] [:error] [pid 14931] [client <info_removed>:46790] PHP Fatal error:  Call to a member function all() on null in /srv/www/<info_removed>/modules/mollie/mollie.php on line 875, referer: http://<info_removed>/index.php?controller=order

Any thoughts on how to fix this?

Thanks in advance for your feedback.

Best regards,
Maarten

**Comment by RicardoJ** [comment]
Hello @bitprocessor,

Does this issue still exist?

Ricardo,
Mollie

**Comment by jimkaler** [comment]
Hey, @ghost i am getting same error while retrieving response after payment done.

**Comment by snowycatsoftware** [comment]
Hi @jimkaler ,

- which version of PrestaShop are you currently using?
- which version of the Mollie module are you currenlty using?
- which PHP version are you currently using?

Kind regards

**Comment by jimkaler** [comment]
Hey @snowycatsoftware 
I am using "mollie/mollie-api-php": "^1.9" for laravel.
php version is 7.0.

**Comment by jimkaler** [comment]
I  think my webhook is not getting called. @snowycatsoftware

**Comment by jimkaler** [comment]
My code for creating payment: 
![screenshot from 2018-04-11 11-21-04](https://user-images.githubusercontent.com/36437555/38598553-70b5293c-3d7a-11e8-8cb6-a43ce84d9dba.png)

Function when calling webhook url:
I am just saving demo data into database to know is my webhook calling or not. but its not inserting data into database.

![screenshot from 2018-04-11 11-21-46](https://user-images.githubusercontent.com/36437555/38598589-9d056632-3d7a-11e8-85e7-b02fbf04c4c5.png)
