### ISSUE TITLE
Version 3.4.4 and 3.4.5 are not working after update PS 1.7.5.1

### ISSUE THREAD

**Issue by didi-2018** [mollie/PrestaShop#132]
I updated Mollie to version 3.4.4 (and 3.4.5 too) and half of the functions are gone. 

In module all the payments should shown as in older version like this: 

![image](https://user-images.githubusercontent.com/44971218/66656808-fab7fc80-ec3e-11e9-9ed4-999dc06f123c.png)

but in version 3.4.4 and 3.4.5 there is nothing shown: 

![image](https://user-images.githubusercontent.com/44971218/66656892-21763300-ec3f-11e9-981a-748ab23cab53.png)

In orders should a table be shown with ordered products for Klarna payments. But it is gone in version 3.4.4 and 3.4.5 too.

I am using PS 1.7.5.1
PHP version 7.2.1

**Comment by margud** [comment]
We couldn't reproduce the issue. Could you try to reinstall the module or if it doesn't help you can give us your FTP so we can check what is posing this problem.
You can send FTP to marius.gudauskis@invertus.eu

**Comment by didi-2018** [comment]
Done! You just got all access with email.

**Comment by margud** [comment]
Can you check your shop now if everything is correct? Everything looks fine or am i missing something?

**Comment by didi-2018** [comment]
Hello, 

okay, thank you! It seams to work now again. What was the issue? 

Why can I not change the state for “Refund”?  If I try to choose another State from the drop down list, it does not change. It always goes back to state “Erstattet”.

**Comment by margud** [comment]
I just upgraded module, i didn't do any other changes so i don't know why it didn't work before.
If you could give me order tab permission i could investigate status issue. Maybe you have changed order sufferance generator in your theme and if its validation fails there might be some problems with your orders.

**Comment by margud** [comment]
I just check and yes it doesn't work for some reason. We will investigate
and try to fix it as soon as possible. For now if you want to change it you
can do it by changing it in database configuration table by finding its
name MOLLIE_STATUS_REFUNDED and changing its value 20 or wait for next
release.

2019-10-16, tr, 17:27 didi-2018 <notifications@github.com> rašė:
