### ISSUE TITLE
Error in Thirty Bees 1.1.0

### ISSUE THREAD

**Issue by grbfst** [mollie/PrestaShop#133]
### Expected behavior
No error after installation

### Actual behavior
Warning on line 5392 in file /var/www/www.mensys.eu/modules/mollie/mollie.php
[2] preg_match(): Compilation failed: syntax error in subpattern name (missing terminator) at offset 40

code is: 
if (preg_match($pattern, $content, $m))....

But $m is not defined or empty

### Steps to reproduce the behavior
After installation and/or after opening the mollie plugin

### Environment
* Thirty Bees 1.1.0 
* Mollie module version: 3.3.4 
* PHP version: 7.0.33

**Comment by margud** [comment]
Could you try to upgrade Mollie version to 3.4.5 and tell us if the issue is still there?

**Comment by grbfst** [comment]
Sorry,
I mentioned wrong version. I already used 3.4.5

**Comment by margud** [comment]
Maybe you could send me your FTP so i could check what is posing this issue?
You can send it to marius.gudauskis@invertus.eu

**Comment by pedalracer** [comment]
Can you confirm that latest Mollie runs fine with Thirtybees?
