### ISSUE TITLE
Status doesn't apply on orders of out of stock products

### ISSUE THREAD

**Issue by AnatoleRozan** [mollie/PrestaShop#134]
### Expected behavior

In Prestashop, when you have out of stock products (with 0 quantity in stock), you can still sell them with a native option called "Allow ordering of out-of-stock products". 
With this option enabled, when you sell an out of stock product, the transaction will first be registered the the status "Payment accepted", then directly after, a new status is apply called : "Awaiting replenishment".
The transaction should be registered like that in the back-office.

### Actual behavior
After a successful payement of an out of stock product, the order is in the back-office but without status on it.
I tested on a new fresh Prestashop in 1.6.0.9 and I still have the problem.
<img width="676" alt="Capture d’écran 2019-10-18 à 11 19 52" src="https://user-images.githubusercontent.com/38098728/67082348-43206e80-f199-11e9-9a95-01de836188cc.png">

The problem appear only on orders of products which have 0 quantity in stock (or less).

### Steps to reproduce the behavior
Purchase a product with 0 quantity in stock with the native Prestashop option enabled that allows you to do that.

I think you plugin doesn't support the native functionality which allow customer to purchase out of stock products.
It is here: Preferences > Products > Allow ordering of out-of-stock products

### Environment
* PrestaShop version: 1.6.0.9 
* Mollie module version: 3.4.5
 
* PHP version: 7.1.26

**Comment by margud** [comment]
Its supported but the problem is that PS 1.6.0.* versions have different logic and statuses for out of stock products. We will see what we can do to fix this issue for PS1.6.0.* versions. For now only way to fix is to upgrade to PS1.6.1 version.

**Comment by AnatoleRozan** [comment]
Thank you for you reply. We unfortunately can't upgrade to 1.6.1 right now.
We are waiting for news from your part.

**Comment by margud** [comment]
We found a work around. For legacy PrestaShop versions which do not have 'On backorder (Paid)' or 'On backorder (Not paid)' order statuses, the module will create and use them.
We created a new zip for you, please try it and let us know if it works. Please delete the old module version before installing because the module update will not create new statuses.
[molliePreRelease.zip](https://github.com/mollie/PrestaShop/files/3760758/molliePreRelease.zip)

**Comment by AnatoleRozan** [comment]
Thank you. The plugin seems to work properly.

1) In the native Prestashop, first it apply the status "Payment accepted", then few seconds after, if the product is out of stock, the status "On backorder". Could you do the same?
It is important because, we send an e-mail via the Payment accepted status and we hide the backorder one.

2) Why do you create new status (instead of using the native ones? Could you use the native ones?
The Prestashop 1.6.0.9 has a native backorder status (that you can't delete).

Thanks for your work.

Ps : I attach you a screen of a backorder.
<img width="627" alt="backorder" src="https://user-images.githubusercontent.com/38098728/67374211-29a86980-f581-11e9-9297-5540cd25c6a3.png">

**Comment by margud** [comment]
We changed it to use only native statuses like you suggested. Please check if everything is alright and lets us know.
[molliePreRelease.zip](https://github.com/mollie/PrestaShop/files/3761900/molliePreRelease.zip)

**Comment by AnatoleRozan** [comment]
Well done @margud and to all your team! Working perfectly!
