### ISSUE TITLE
Order is registered with an amount of 0€

### ISSUE THREAD

**Issue by AnatoleRozan** [mollie/PrestaShop#135]
### Expected behavior
After the payement the order should be registered with the good total amount in the back-office.

### Actual behavior
The order is in the back-office but with a total amount of 0€.
<img width="1153" alt="Capture d’écran 2019-10-18 à 11 30 17" src="https://user-images.githubusercontent.com/38098728/67083042-b2e32900-f19a-11e9-9659-5cc5b76c163b.png">

We have this error:
AH01071: Got error 'PHP message: PHP Notice:  Use of undefined constant _PS_PRICE_COMPUTE_PRECISION_ - assumed '_PS_PRICE_COMPUTE_PRECISION_' in /modules/mollie/mollie.phpon line 4637\nPHP message: PHP Warning:  round() expects parameter 2 to be integer

I tested it on a complete fresh new Prestashop in 1.6.0.9.

### Correction

I've replaced all "_PS_PRICE_COMPUTE_PRECISION_"
by "2" in the mollie.php file and the bug was resolved.

But I need your confirmation that it is a correct solution.

### Environment
* PrestaShop version: 1.6.0.9 
* Mollie module version: 3.4.5 
* PHP version: 7.1.26

**Comment by margud** [comment]
Maybe you could try installing latest Mollie [3.4.5](https://github.com/mollie/PrestaShop/releases/tag/3.4.5) version or is there a reason you want to use 3.3.5 version?

**Comment by AnatoleRozan** [comment]
Hi,
Thanks for your reply.
We’re using the 3.4.5 version. Sorry, I made a mistake in my issue.

**Comment by margud** [comment]
Thank you for opening this issue. We tested and indeed in older PS versions they don't convert string to int that's why it doesn't work. We will fix this issue next release but for now you should replace all

 _PS_PRICE_COMPUTE_PRECISION_
 in Mollie to 
(int) _PS_PRICE_COMPUTE_PRECISION_
and this should fix this issue correctly.

**Comment by margud** [comment]
We just found out that PS1.6.0.* dont have PS_PRICE_COMPUTE_PRECISION so leave it at 2 for the moment while we find solution.

**Comment by AnatoleRozan** [comment]
Ok. Then in the file "mollie.php", we replace all PS_PRICE_COMPUTE_PRECISION to 2. Or just few of them? I'm just worry about making some new bugs with that solution.

**Comment by margud** [comment]
You can replace all of them. In PS1.6.0.9 there is no such thing as PS_PRICE_COMPUTE_PRECISION thats why it didnt work for you. We will also remove it in our next release and change it with const 2.
