### ISSUE TITLE
On Safari: InvalidAccessError: Trying to start an Apple Pay session from an insecure document. 

### ISSUE THREAD

**Issue by preitsma** [mollie/PrestaShop#136]
### Expected behavior
No error messages

### Actual behavior
When enabling the Mollie plugin, it throws the error (in console): InvalidAccessError: Trying to start an Apple Pay session from an insecure document on line 36 of apple_payment.js

This error message breaks other Javascript functionality on the homepage of the shop like the Ajax put in cart button and the autocomplete on search.

Furthermore it seems to make Safari consume unreasonable amounts of CPU-time and resources, resulting in a frozen Webinfo Console.

Try http://ps17.hayonlinewinkel.com/nl/ 

Disabling the Mollie add-on or renaming the apple_payement.js on the server solves the issue.

### Steps to reproduce the behavior
1. Navigate to  http://ps17.hayonlinewinkel.com/nl/ 
2. Try autocomplete function in Search.. or Place-in-Basket button on a product pane -> both don't work
3. Check Webinfo Console

### Environment
* PrestaShop version: 1.7.6.1 
* Mollie module version: 3.4.5 
* Safari 12.1.1
* OSX: 10.14.5
* PHP version: 7.1.32

**Comment by margud** [comment]
We found out that after latest iOS update this issue appeared and we are not sure how to deal with it yet. For now you can change line 36 in mollie/views/js/apple_payment.js
    if (window.ApplePaySession && window.ApplePaySession.canMakePayments()) {
with 
    if (window.ApplePaySession) {

It should work like that but it wont check if user can make apple pay payment like before.

**Comment by margud** [comment]
We fixed this issue in 3.4.6 release by disabling apple pay if shop doesn't have SSL enabled.
