### ISSUE TITLE
No TAX on Total

### ISSUE THREAD

**Issue by TomanDesign** [mollie/PrestaShop#138]
After august module update we have a problem with orders payed by iDEAL. After the customer makes the payment, no tax is added to the invoice summary.

![Screenshot_2019-10-24 Orders Order XGJETXEHL](https://user-images.githubusercontent.com/4354135/67469912-32667180-f64d-11e9-94c5-60b9ae80e639.png)

There is an overpayment in the payment area.

![Screenshot_2019-10-24 Orders Order XGJETXEHL_](https://user-images.githubusercontent.com/4354135/67469914-32ff0800-f64d-11e9-916d-5e66cf703b07.png)

Example values in database :

Payment with problem:

payment		        iDEAL
total_paid		        59,1
total_paid_real	        71,52
total_paid_tax_excl	59,1
total_paid_tax_incl	59,1
total_paid_tax_excl	59,1
total_paid_tax_incl	59,1

Payment without problem:

payment		        Mollie
total_paid		        55,07
total_paid_real	        55,07
total_paid_tax_excl	45,5
total_paid_tax_incl	55,07
total_paid_tax_excl	45,5
total_paid_tax_incl	55,07

### Environment
PrestaShop version: 1.7.6.1
Mollie module version: 3.4.5
PHP version:  7.2.20

**Comment by margud** [comment]
Thank you for creating this issue. It got fixed and will be added in next release. For now if you don't want to wait till new release and wish to fix it yourself just add ! before $withTaxes in mollie.php line 4638
