### ISSUE TITLE
Inform the customers when Mollie is unavailable

### ISSUE THREAD

**Issue by chrisvanberg** [mollie/PrestaShop#139]
### Expected behavior
Automatically deactivate/reactivate the payment method who encounter an issue

And when Mollie is completely down show a more user friendly message like "Our payment plateform encounter a problem, please try later or use another payment option" 

### Actual behavior
When Mollie is down, the customer on prestashop see a raw message returned by the api/add-on. It's not user friendly and it can scare the customer

### Steps to reproduce the behavior
Try to make a payment when Mollie is down

### Environment
* PrestaShop version: 1.7.5.0 and 1.7.5.6 
* Mollie module version: 3.3.4
* PHP version: 7.2

**Comment by margud** [comment]
We fixed this issue in new 3.4.6 release.
