### ISSUE TITLE
Mollie creates table in orders when customer pay with PayPal, Stripe and so on

### ISSUE THREAD

**Issue by didi-2018** [mollie/PrestaShop#140]
Hello, 

I have a problem with Mollie Module. If the customer try to pay with Mollie Klarna payment and Klarna decline the payment and the customer goes back to my shop and choose for example PayPal payment the Mollie module than creates the Klarna payment table in order as if the customer had paid with Klarna but the customer paid with PayPal. This table in backoffice order should not be created if the customer pay with PayPal or Stripe or with what ever. 

Please check it. 

Thank you very much in advance

Best regards

![image](https://user-images.githubusercontent.com/44971218/68692845-7c6cb400-0576-11ea-9f1e-5a3abfc9c595.png)

![image](https://user-images.githubusercontent.com/44971218/68692927-a02ffa00-0576-11ea-81b7-c42f577c11df.png)

**Comment by SimonasB88** [comment]
Hey, thank you for contacting us,

We tried to reproduce the issue with scenario like you described: https://streamable.com/svsmx

Can you please double check the pre-conditions of the issue, and if possible give us a video of reproduction or reproduce more detailed steps?

It would be great for our bug fixing and module improving.

Thank you!

Looking forward to hearing from you!

**Comment by didi-2018** [comment]
your video does not show backoffice order where the Klarna table is created. And you pay with KBC not with Klarna. 

![image](https://user-images.githubusercontent.com/44971218/68781173-ae921a80-0637-11ea-940d-7db122b337d2.png)

![image](https://user-images.githubusercontent.com/44971218/68781191-b5209200-0637-11ea-8fd0-d7237f340b1c.png)

![image](https://user-images.githubusercontent.com/44971218/68781210-bb167300-0637-11ea-853b-9e05d6161610.png)

![image](https://user-images.githubusercontent.com/44971218/68781235-c1a4ea80-0637-11ea-8dd2-92690ee4cdb3.png)

**Comment by SimonasB88** [comment]
Hey Diana,

Yes, thank you for correcting the issue information, we are working into it. 

I will update you with the latest, as soon as possible.

Have a great day!

**Comment by SimonasB88** [comment]
Hey Diana, hope you are doing fine, just following-up,

Please check the test flow we created: https://streamable.com/5ou5z

As you can see, there are 2 orders created separately in mollie.com dashboard. One action is with Failed order on Klarna, other with Paid order on Paypal. Prestashop dashboard shows Paypal order, as the last payment. I wrote to you just to let you know the situation. We are continuing testing. 

![image](https://user-images.githubusercontent.com/29095235/68868303-f8463800-06ff-11ea-8261-092231f7d566.png)
