### ISSUE TITLE
Tax breakdown is wrong

### ISSUE THREAD

**Issue by DaniGithub** [mollie/PrestaShop#141]
### Expected behavior
When I make an order and use the Mollie module to complete it I expect the invoice to have a proper tax breakdown of the Total Products and Total Shipping.

### Actual behavior
At the moment the tax breakdown is wrong.

(the tax breakdown is good if I use the official Wire Payment module of PrestaShop)

### Steps to reproduce the behavior
- Install PrestaShop 1.7.6.1 on a local server
- Install the Mollie module v3.4.6 and configure it with a test API
- **Got to Winkelinstellingen -> Klantinstelling -> Groepen and change all three groups to show prices excl. tax.**
- Make an order and use one of the payment methods by Mollie
- View the invoice and see how the tax breakdown is wrong

### Environment
* PrestaShop v1.7.6.1
* Mollie module v3.4.6
* PHP version: 7.2.18

![tax-breakdown](https://user-images.githubusercontent.com/9342005/69506728-2ada0700-0f30-11ea-9463-ff3c30bcccd8.png)

**Comment by DaniGithub** [comment]
As a temporary fix until the Mollie module developers can implement a proper fix do the following.

Open `modules\mollie\mollie.php`

Find line 4604 that starts with `$withTaxes = $this->isCartWithTaxes($idCart);`

Directly after it on a new line add the following:
`$withTaxes = true;`


Note that I am not an expert PHP/PrestaShop developer. Implement this on your own risk.

**Maybe this is related to this GitHub Issue?**
https://github.com/mollie/PrestaShop/issues/138

**Comment by margud** [comment]
Thank you for creating this issue. We investigated and found out that our module inserted wrong price for products with taxes if shop displayed price without taxes. This issue was fixed and will be included in new 3.4.7 release.
