### ISSUE TITLE
Notice about how it is checking overrides

### ISSUE THREAD

**Issue by Smiles-v** [mollie/PrestaShop#142]
### Expected behavior
Opening the module from the BO causes this error to be shown. We found this error in ThirtyBees 1.1.0 but expect it also to be happening in Prestashop.

### Actual behavior
Warning op lijn 5392 in bestand /var/www/vhosts/shopurl.com/httpdocs/modules/mollie/mollie.php
[2] preg_match(): Compilation failed: syntax error in subpattern name (missing terminator) at offset 40

### Steps to reproduce the behavior
Disable debugging mode under caching (advanced parameters -> performance)

### Environment
* Tirtybees 1.1.0
* Mollie module version: 3.4.6
* PHP version: 7.1.33

**Comment by margud** [comment]
Do you still get this error with new Mollie version? I couldn't reproduce this error. Maybe you could give us more information how to reproduce it?

**Comment by Smiles-v** [comment]
Error occurs in Thirty bees, not sure about PS. Only shows when you enable logging and error showing.
