### ISSUE TITLE
New Functionality: Add a description to a payment method

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop#151]
Attached a design of what would be the best option.

Thanks.

![4bfd3e2a-bf85-4848-af90-9e23fe476b49](https://user-images.githubusercontent.com/1645341/72888400-c52ab100-3d0d-11ea-9d63-460507597f8b.jpeg)

**Comment by basemedia** [comment]
Please inform about status.

**Comment by SimonasB88** [comment]
Thank you for the suggestion of improvement. We have discussed it internally. It’s a nice idea to have, however we don’t see it as the one that will give most benefits to our customers. At the moment we are focused on the features that are more important in our current roadmap, however we might comeback to this idea in the future. If you have any other ideas, please let us know. We really appreciate all suggestions.
