### ISSUE TITLE
Can't use creditcard payment on PSv1.6 with OPC in new version 3.5.5 (v3.5.0 works)

### ISSUE THREAD

**Issue by coMegaWebMaster** [mollie/PrestaShop#152]
Mollie version 3.5.0 works ok, but the latest version 3.5.2 does not make the windows come from the creditcard payment. In the console I see a JS error and I think it is the new file that is made for PSv1.6 in that new version (mollie_iframe_16.js).
Hope this is enough information, if more is needed then let me know.

Environment:
MySQL version 10.2.30-MariaDB
PrestaShop version:  1.6.1.24
Mollie module version: 3.5.0 (version 3.5.2 does not work with creditcard)
PHP version: 7.1.33

**Comment by coMegaWebMaster** [comment]
Same issue with Mollie version 3.5.3, downgraded to Mollie version 3.5.0 again.

**Comment by coMegaWebMaster** [comment]
Same issue with Mollie version 3.5.5, downgraded to Mollie version 3.5.0 again.

**Comment by margud** [comment]
We couldn't reproduce this error with 3.5.5 Mollie version.
Maybe you could give more information about error or sand me your ftp to marius.gudauskis@invertus.eu ?

**Comment by coMegaWebMaster** [comment]
@margud, did you received my email?

**Comment by margud** [comment]
Hi Alex,

Yes, I got it. I will investigate as soon as possible to let you know about
the situation.

2020-04-03, pn, 18:18 Alexander van Amersfort <notifications@github.com>
rašė:
