### ISSUE TITLE
Order statuses could not change an set in BO Module

### ISSUE THREAD

**Issue by alerch** [mollie/PrestaShop#155]
### Expected behavior
when changing Status after paid to different Status it should be set in BO after a payment.

### Actual behavior
when changing Status after paid to different Status it stays at default entry "paid".

### Steps to reproduce the behavior
open module in BO switch to advanced settings, change first order state to different state and save. After reopen the module the Order State is still the default and not the selected before. 

### Environment
* PrestaShop version: 1.7.6.2 
* Mollie module version: 3.5.4 
* PHP version: 7.2.
* Multishop - Module with same behavior in "all-shops" and "one specific selected shop"

**Comment by rootje123** [comment]
Hi Alerch,

Can you mail us to info@mollie.com and add tech support in the subject line? 

Kind regards,

Mollie

**Comment by margud** [comment]
This issue should have been fixed in new 3.5.5 release. If you still have this issue please re-open this issue.
