### ISSUE TITLE
Live/Test switch button on the back office

### ISSUE THREAD

**Issue by chrisvanberg** [mollie/PrestaShop#159]
Hello, thanks for your work on the PrestaShop's addon, the quality is there !
I have a suggestion for improving the addon.
### Expected behavior
On the back office, it would be useful if you could enter your test and live api key and then switch with a simple click on a button.

### Actual behavior
For the moment, if you want to use the test api, you have to replace the live api on the back-office and then put back the live api key when you're done testing

### Steps to reproduce the behavior
N/A

### Environment
* PrestaShop version: 1.7.5.0
* Mollie module version: 3.3.5 
* PHP version: 7.1.26

**Comment by SimonasB88** [comment]
Hello @chrisvanberg thank you for your suggestion,

Discussed with the team, we are going to implement this on the next Mollie release. Stay tooned.

Best of luck.
