### ISSUE TITLE
Version 4.0.0

### ISSUE THREAD

**Issue by coMegaWebMaster** [mollie/PrestaShop#163]
A few issues:
1. Zip folder is named incorrect, this should have been "mollie".
2. Payment image are not showing, getting the no image.

### Environment
* PrestaShop version: 1.6.1.24
* Mollie module version: 4.0.0
* PHP version: 7.2.30

**Comment by margud** [comment]
There was a GitHub issue when uploading module.zip that we didn't notice. It's uploaded now.
