### ISSUE TITLE
Tax breakdown is wrong

### ISSUE THREAD

**Issue by MaartenPol** [mollie/PrestaShop#175]
### Expected behavior
When I make an order and use the Mollie module to complete it I expect the invoice to have a proper tax breakdown of the Total Products and Total Shipping.

### Actual behavior
At the moment the tax breakdown is wrong.
(the tax breakdown is good if I use the official Wire Payment module of PrestaShop)

### Steps to reproduce the behavior

- Install PrestaShop 1.7.6.5 on a local server
- Install the Mollie module v4.0.5 and configure it 
- Make an order and use one of the payment methods by Mollie
- View the invoice and see how the tax breakdown is wrong 

### Environment
* PrestaShop version: 1.7.6.5
* Mollie module version: 4.0.5
* PHP version: 7.3.31 

![Image of issue](https://i.ibb.co/dgHxSP6/Aantekening-2020-06-17-123038.png)

**Comment by pic16f876** [comment]
Same Issue Here,

**Environment**

> PrestaShop version: 1.7.6.5
> Mollie module version: 4.0.5
> PHP version: 7.3

Paid With Mollie plugin:
![Mollie Payment](https://user-images.githubusercontent.com/67101966/85012297-1dea6280-b163-11ea-8645-085a78d65d76.PNG)

Paid with bank transfer (no Mollie Plugin)
![Bank Transfer](https://user-images.githubusercontent.com/67101966/85012385-39ee0400-b163-11ea-857c-dcabbc17be32.PNG)

**Comment by superknutsel** [comment]
Try uncommenting line 422
//$order->total_paid_tax_excl = $totalPrice->toPrecision(2);
in file /modules/mollie/controllers/front/payment.php

**Comment by MaartenPol** [comment]
> Try uncommenting line 422
> //$order->total_paid_tax_excl = $totalPrice->toPrecision(2);
> in file /modules/mollie/controllers/front/payment.php

That works!

**Comment by SimonasB88** [comment]
Hey guys, thank you for your insights! Our team really appreciates that,
I can assure, this thing is added to our TODO list as well.
----
Best Regards,
Invertus Support Team

**Comment by pic16f876** [comment]
> > Try uncommenting line 422
> > //$order->total_paid_tax_excl = $totalPrice->toPrecision(2);
> > in file /modules/mollie/controllers/front/payment.php
> 
> That works!

Confirmed!

**Comment by margud** [comment]
Issue was resolved in [4.0.6](https://github.com/mollie/PrestaShop/releases/tag/4.0.6) release.
