### ISSUE TITLE
Double payment accepted status in 4.0.5

### ISSUE THREAD

**Issue by hknobbe** [mollie/PrestaShop#176]
as per request of @SimonasB88, in a new topic:

I think I've found a small bug in 4.0.5. (settings are the same in 4.0.4 with that version all went well):

As soon as mollie returns order/payment accepted it changes the status of the order 2 times and sends out the mail 2 times:

![Screenshot_2](https://user-images.githubusercontent.com/39634152/84747142-2e5dda00-afb7-11ea-93d7-6cd6fa54c417.png)

&

![Screenshot_3](https://user-images.githubusercontent.com/39634152/84747336-6bc26780-afb7-11ea-8447-e77998ebba0b.png)

Settings:
![Screenshot_4](https://user-images.githubusercontent.com/39634152/84747564-b80da780-afb7-11ea-9b1e-b262cd427b17.png)
![Screenshot_5](https://user-images.githubusercontent.com/39634152/84747569-b9d76b00-afb7-11ea-926d-6d4ef5dbddac.png)

_Originally posted by @hknobbe in https://github.com/mollie/PrestaShop/issues/173#issuecomment-644601052_

**Comment by SimonasB88** [comment]
Hey @hknobbe nice to hear from you!
Yes, this was recently tested, and it seems that we have covered the bug and fixed now. Still testing at the moment.

Best Regards,
Invertus Support Team

**Comment by margud** [comment]
Issue was resolved in [4.0.6](https://github.com/mollie/PrestaShop/releases/tag/4.0.6) release.
