### ISSUE TITLE
title or method_name instead of id_method on the invoice

### ISSUE THREAD

**Issue by superknutsel** [mollie/PrestaShop#178]
### Expected behavior
Show for example iDEAL on the chosen payment method or anything used in the title set in the module.

### Actual behavior
It is showing ideal which is not the correct spelling coming from the table mol_payment_method (id_method)

### Steps to reproduce the behavior
create an order, check the name of the payment method on the invoice.

### Environment
* PrestaShop version: 1.7.6.4 
* Mollie module version: 4.0.5
* PHP version: 7.2

**Comment by Maz-Invertus** [comment]
Hi @superknutsel ,

We really appreciate your input in this community. We have added this issue to our backlog and it should be fixed in upcoming releases. 

Please follow the latest updates.

Thank you!

**Comment by margud** [comment]
Issue was resolved in [4.0.6](https://github.com/mollie/PrestaShop/releases/tag/4.0.6) release.
