### ISSUE TITLE
payments are pending and double payement accepted 

### ISSUE THREAD

**Issue by dono1309** [mollie/PrestaShop#179]
### Expected behavior

many payments are pending and don't cancel automactily
![Capture](https://user-images.githubusercontent.com/63119415/85235728-a8f38300-b417-11ea-8ce6-2c198f534892.PNG)

double payement accepted 

### Steps to reproduce the behavior
make payement

### Environment
* PrestaShop version: 1.7.6.5 
* Mollie module version: 4.0.5
* PHP version: 7.2

**Comment by Ditwo** [comment]
This concerns "expired" status on mollie.com. Not reflected into Prestashop

Thks & regards

**Comment by Maz-Invertus** [comment]
Hi @Ditwo,

We really appreciate your input in this community. We have added this issue to our backlog and it should be fixed in upcoming releases.

Please follow the latest updates.

Thank you!

**Comment by margud** [comment]
Issue was resolved in [4.0.6](https://github.com/mollie/PrestaShop/releases/tag/4.0.6) release.
