### ISSUE TITLE
Overboeking

### ISSUE THREAD

**Issue by basemedia** [mollie/Prestashop#18]
Het valt mij op dat veel klanten die een overboeking kiezen niet hun emailadres achterlaten (we kunnen ze dan ook geen mail sturen met de betalingsgegevens.) Is het mogelijk dat deze automatisch wordt meegegeven?

**Comment by ndijkstra** [comment]
Hi, ik heb hier een Pull Request voor gemaakt en zal dit morgen met mijn collega's bespreken om samen te voegen.

**Comment by basemedia** [comment]
Top!

Mvg,

Luke

**Comment by mollierobbert** [comment]
Nick's pull request has been merged. Please upgrade the Mollie module to v1.3.0.
