### ISSUE TITLE
Status back to paid when shipped

### ISSUE THREAD

**Issue by pic16f876** [mollie/PrestaShop#184]
### Expected behavior
When I fill in the details of shipping the order should gets "status shipped" if not allready shipped selected 
### Actual behavior
When I fill in the details of shipping the order gets "status paid" and customer gets another email

### Steps to reproduce the behavior
"Make an order, then fill in details of shipping (carrier and tracking nr

### Environment
* PrestaShop version: 1.7.6.5 
* Mollie module version: 4.0.6
* PHP version: 7.3

![Screen Shot 06-30-20 at 03 01 PM](https://user-images.githubusercontent.com/67101966/86129207-a0b7d980-bae2-11ea-8a91-7310470d50d0.PNG)

**Comment by SimonasB88** [comment]
Hey @pic16f876 ,

Thanks for your insights, I am dropping this to the team to check and I will update you as soon as possible!

Best Regards.

**Comment by thezimba** [comment]
We also encountered the same problem. Is it already a solution for this or at least a temporally workaround?

Somehow a webhook from the mollie API triggered this
![image](https://user-images.githubusercontent.com/68066905/87048813-7cec4600-c1fc-11ea-835f-996c6b2ac59c.png)

![image](https://user-images.githubusercontent.com/68066905/87049181-f2581680-c1fc-11ea-8b62-0e3fe9b35aad.png)

**Comment by waschier-design** [comment]
Same Error here - Please fix immediately.

**Comment by Jordi123451** [comment]
**Yes, we have the same problem**

**Comment by waschier-design** [comment]
Any news on this topic?

**Comment by SimonasB88** [comment]
Hey guys,

This case is being tested right now, we will update you when we will get the actual results 👍 

Best Regards.

**Comment by SimonasB88** [comment]
Hey guys,
Yesterday we were executing some tests on one of the v 4.0.7 branches, regarding this case on PS1763 PHP 7.0 All Shops Multistores MacOS Firefox.

![image](https://user-images.githubusercontent.com/29095235/88771679-4749d580-d188-11ea-8d27-af349df3e197.png)

![image](https://user-images.githubusercontent.com/29095235/88771742-5af53c00-d188-11ea-86c0-4c69b59d2f96.png)

![image](https://user-images.githubusercontent.com/29095235/88772051-d3f49380-d188-11ea-996e-f58736f29f1d.png)

No duplications in statuses so far.

Best Regards.

**Comment by thezimba** [comment]
In our case the webhook was triggered from Mollie when in a specific order was updated to shipped in the mollie dashboard (Klarna order).

**Comment by MerijnMollie** [comment]
Thanks for the additional info @thezimba ! That's definitely a scenario we'll test more in detail. Expect an update this week!

**Comment by MerijnMollie** [comment]
@thezimba @waschier-design @Jordi123451 , 
We found the issue, and will fix it within the upcoming 407 release!
Expect this latest on monday.

**Comment by Maz-Invertus** [comment]
Hi @thezimba  @waschier-design  @Jordi123451 ,
Please have a look at new [Mollie 4.0.7 release](https://github.com/mollie/PrestaShop/releases/tag/4.0.7) where this issue has been fixed.

**Comment by SimonasB88** [comment]
Hey @thezimba @waschier-design @Jordi123451 @pic16f876 , just a friendly follow up after some time, so are you experiencing the same status bugs so far in 4.0.7?

Best Regards.

**Comment by SimonasB88** [comment]
Hey everyone!
The thread is closed due the inactivity for some time.
Please raise a new ticket if it is necessary.

Have a great day!
Best Regards.
