### ISSUE TITLE
Got 500 internal server error when paying

### ISSUE THREAD

**Issue by GertJanBraeckevelt** [mollie/PrestaShop#191]
### Expected behavior
Paying

### Actual behavior
Got a 500 internal server error.

### Steps to reproduce the behavior
Trying to pay. Got the same thing trying all payment options. Reverting back to 3.5.5 solved the issue.

### Environment
* PrestaShop version: 1.7.6.3
* Mollie module version: 4.0.6
* PHP version: 7.3

**Comment by SimonasB88** [comment]
Hello @GertJanBraeckevelt thanks for your message!

We would like to advise to make the old v.3.5 module uninstall completely, and also check the option to delete all the folder of Mollie from your server.

Then install the new v.4.0.6 from the fresh and configure all the required module settings.

Let us know the checkouting results. We will take the other actions if else.

Best Regards.

**Comment by SimonasB88** [comment]
Hey @GertJanBraeckevelt just a friendly follow-up, have you managed to try those steps recommended?

Best Regards.

**Comment by margud** [comment]
This ticket is closed due to lack of activity for some time.
If the issue wasn’t solved please raise a new ticket and our support team will assign a developer to it.
Have a nice day.
