### ISSUE TITLE
V4.07 on Thirtybees V1.1.x all orders equal 1EURO

### ISSUE THREAD

**Issue by pedalracer** [mollie/PrestaShop#197]
### Actual behavior
1. Payment / order via PayPal  equals 1EURO "Total_order" (but actual sum ist far more than 1EURO)
2. canceled payments / changing of payment option creates order with 1EURO and status canceled

(Tested on fresh install of Thirtybees. I did the same with Prestashop 1.6.24 and no problems noticed)

### Steps to reproduce the behavior
Install latest Thirtybees (and make an update via core updater), install Mollie V.4.07 and make a test order.

### Environment
* THIRTYBEES version: 1.1.x  
* Mollie module version: 4.0.7

**Comment by Maz-Invertus** [comment]
Hi @pedalracer ,

Thank you for raising the issue and being an active Mollie community member. Could you please share more details about the issue:

- Scenario how to reproduce the issue with screenshots.
- All the possible error logs.

**Comment by pedalracer** [comment]
I came from Mollie 3.5.5 with Thritybees V1.1.x latest (PS 1.6 fork)
I resetted it, deinstalled and deleted it from server.
I disabled all chaches in backoffice performance tab.
I installed Mollie V4.0.7 via backoffice and set it up with my live credential mimecking as best as I knew the V3.5.5 settings.

Result:
Each order gets "total_order" 1 EURO

I installed fresh Thirtybees and installed Mollie V.4.07
I entered test_API code
Same result: All orders now with total_order = 1 EURO

https://i.imgur.com/R7vyHyA.png
*************************************************
thirty bees version 1.1.0-1.1.x 
PHP-Version 7.3.21 Speichergrenze 384M  max_execution_time 0 
MySQL-Version 5.7.31-1  MySQL-Engine InnoDB MySQL-Treiber DbPDO

**Comment by SimonasB88** [comment]
Hey @pedalracer  thanks for your message!

We have backloged this case and we will let you know about the updates!

Best Regards.

**Comment by SimonasB88** [comment]
Hey,

This fix was added to the the upcoming 4.0.8.

Best Regards.

**Comment by pedalracer** [comment]
I spend again time setting up Mollie module and had to notice that this crazy error still exists in 4.0.9

Please take your two hours time and check this on Thirtybees, so we can use Mollie V.4.x this year during Xmas sales.

**Comment by SimonasB88** [comment]
Hey @pedalracer we backloged this, I assure you we will reproduce the possible bug, fix, and let you know the updates.

Best Regards.

**Comment by pedalracer** [comment]
Since most merchants would be happy to use Mollie at whole during xmas business I like to propose you get in contact with Mr. Hucik from Datakick. He found already the or a possible culprit and referred to it:
https://github.com/mollie/PrestaShop/pull/232

**Comment by SimonasB88** [comment]
Hey @pedalracer,

Thanks for your insight, team appreciates. 
Our developers will align to that case and let you know.

Best Regards.

**Comment by SimonasB88** [comment]
Hey @pedalracer we have tested the case on the local machine, this bug existed in 4.0.9 version with the next version (4.1.0) it shouldn’t be any problems.

We have made orders with 4.1.0 version haven’t reproduced the bug, but when I downgraded version to 4.0.9 the bug appeared it seems that bug will be fixed with the next release.

![image](https://user-images.githubusercontent.com/29095235/98107046-9ea3c400-1ea2-11eb-88e2-db174494fef2.png)

**Comment by 30knees** [comment]
@SimonasB88 It's back in the version 4.1.1., but the original fix supplied here https://github.com/mollie/PrestaShop/pull/232 works if the file is updated.

**Comment by SimonasB88** [comment]
Hello @30knees 

OK, I will ask the developers to check this in 4.1.1. and update the code. Thanks.

Best Regards.

**Comment by SimonasB88** [comment]
Hello @30knees @pedalracer thank you for the insights, sorry for a delay in response here, our developers checked and reproduced the issue for sure, the fix will be definitely included into upcoming 4.2.0 release, witch will be bigger release.

Best Regards.
