### ISSUE TITLE
Error 500 bij betaalmethode & dubbele orderstatussen

### ISSUE THREAD

**Issue by Goedkoopsteverf** [mollie/PrestaShop#205]
### Expected behavior
Error 500 bij het maken van het plaatsen en afrekenen van de producten in de winkelwagen, ook worden er orderstatussen dubbel aangemaakt welke er reeds in zitten dus alles is na iedere installatie dubbel 

### Actual behavior
Gewoon alles inclusief de installatiemappen verwijderen en de V4.0.7 versie teruggezet 

### Steps to reproduce the behavior
Deze versie dus niet uitrollen Mollie dient deze te verwijderen en is achter de oren te krabbelen of dit wederom de juiste weg is om dit uit te rollen

### Environment
* PrestaShop version: 1.7.6.5 
* Mollie module version: 4.0.8 
* PHP version: 1.7.6.5

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf thank you for your short report, 
Yes, we are on to this known bug about Error 500, but we are not sure about the order duplication after the multiple module installations. It might be relative to the first bug you have mentioned.

We will definitely check this and fix this as fast as possible.

Best Regards.

**Comment by Goedkoopsteverf** [comment]
> Hey @Goedkoopsteverf thank you for your short report,
> Yes, we are on to this known bug about Error 500, but we are not sure about the order duplication after the multiple module installations. It might be relative to the first bug you have mentioned.
> 
> We will definitely check this and fix this as fast as possible.
> 
> Best Regards.

The duplications of the orderstatus has something to do with the translations file, the old orderstatusses are hidden automatically by the update of the plugin, see the attached screenshots below:
![Screenshot_3](https://user-images.githubusercontent.com/71271481/93311730-a6ca7600-f806-11ea-8ccc-9dd20be2c046.png)
![Screenshot_2](https://user-images.githubusercontent.com/71271481/93311734-a7fba300-f806-11ea-8e97-3385287b4d9f.png)
![Screenshot_1](https://user-images.githubusercontent.com/71271481/93311735-a7fba300-f806-11ea-91f1-0bd57922abb8.png)
![Orderstatus](https://user-images.githubusercontent.com/71271481/93311736-a7fba300-f806-11ea-968c-6c2573bd7d48.png)

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf thanks for the info you provided,
We are checking this with the team, definitely we will inform you about the fix.

Best Regards.

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf 
We are in the process of testing now, this fix was merged into the upcoming 4.0.9.

Case can be closed.
Best Regards.

**Comment by Goedkoopsteverf** [comment]
So the fix is for the Error 500 and the double orderstatus.

When is the option payment fee available in the mollie plugin so the Prestashop invoice is handled correctly

**Comment by SimonasB88** [comment]
> So the fix is for the Error 500 and the double orderstatus.
> 
> When is the option payment fee available in the mollie plugin so the Prestashop invoice is handled correctly

Hey, could you please give us more details about the Prestashop invoices and payment fees? If it is separate issue, to make thread more clearer, please create separate issue.

Best Regards.

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf you wrote some time ago about this order duplication issue.
Are you still experiencing the issue? If so, could you screen-capture a video of the issue reproduction?

Best Regards.

**Comment by Goedkoopsteverf** [comment]
We  can not test this in the new version so we can not tell you if this is still happening.

**Comment by Goedkoopsteverf** [comment]
The translation fix is not added in this new version V4.0.9, see our new issue

**Comment by SimonasB88** [comment]
@Goedkoopsteverf thanks for the reply, we have backloged the new issue, but regarding the main title of the issue, are you experiencing the same in 4.0.9?

Best Regards.

**Comment by Goedkoopsteverf** [comment]
Solved with version V4.0.9
