### ISSUE TITLE
Payment Fee PSP Module

### ISSUE THREAD

**Issue by Goedkoopsteverf** [mollie/PrestaShop#207]
![Screenshot_4](https://user-images.githubusercontent.com/71271481/93890631-db4c9f00-fcea-11ea-8d33-d0f423d3a5aa.png)
![Screenshot_3](https://user-images.githubusercontent.com/71271481/93890633-dbe53580-fcea-11ea-8e19-dce5a097a1eb.png)
![Screenshot_2](https://user-images.githubusercontent.com/71271481/93890636-dbe53580-fcea-11ea-8c0b-9c902be48218.png)

### Expected behavior
Payment Fee 

### Actual behavior
The option payment fee is available as fixed amount of percentage but is is not placed on the PDF Invoice created by prestashop

### Environment
* PrestaShop version: 1.7.6.5 
* Mollie module version: 4.0.7 
* PHP version: 7.2.33

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf thanks for the message, checking with the team this case.

We will update you once we get valuable information.

Best Regards.

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf 
Have you checked the latest Mollie v.4.0.8 and made checkouting with Pay Later?
<img width="869" alt="image" src="https://user-images.githubusercontent.com/29095235/94025731-816ad880-fdc1-11ea-9079-21d36f575c83.png">

**Comment by Goedkoopsteverf** [comment]
This version we had implemented but gave a error 500, see our previous issue

**Comment by Goedkoopsteverf** [comment]
In new release the Payment Fee is still not working on the default Prestashop invoiuce as stated above

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf thanks for the message,
Now this design change is being discussed with the Mollie team as well.

Best Regards.

**Comment by AmandaMollie** [comment]
@Goedkoopsteverf - We've reviewed the request and for now we won't make any changes to the formatting of the invoice but will definitely keep it in the backlog for future improvement opportunities.

**Comment by SimonasB88** [comment]
Hello @Goedkoopsteverf if you don't have additional questions we can close this thread.

**Comment by SimonasB88** [comment]
This ticket is closed due to lack of activity for some time.
If the issue wasn’t solved please raise a new ticket and our support team will assign a developer to it.
Have a nice day.
