### ISSUE TITLE
Creation of double shopping carts after approval payment Mollie

### ISSUE THREAD

**Issue by Goedkoopsteverf** [mollie/PrestaShop#211]
### Expected behavior
This module makes after a payment has taken place a double shopping cart with the same items

### Actual behavior
n.b.

### Steps to reproduce the behavior
See after a payment has been excepted by Mollie the shopping carts and you wil see a duplication of the one what has just be handle a agreed on paymant

### Environment
* PrestaShop version: 1.7.6.5 
* Mollie module version: 4.0.7 
* PHP version: 7.2.33

**Comment by SimonasB88** [comment]
Hello and thank you for your query.
@Goedkoopsteverf are you experiencing the same issues on 4.0.8?

Best Regards.

**Comment by Goedkoopsteverf** [comment]
We cann't test this because the error 500 is in this version so we have to switch back to the previous version.

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf thank you for your information,

We are still having some struggles trying to reproduce the case.
Could you please give us the actual video screen reproduction steps? 

Best Regards.
