### ISSUE TITLE
Errors in 1.6.1.24

### ISSUE THREAD

**Issue by drwebbe** [mollie/PrestaShop#212]
### Actual behavior

Klanten konden niet meer betalen. Er was een update dus heb ik deze geinstalleerd.
Maar na update naar 4.0.7 kreeg ik volgende foutmelding :
[PrestaShop] Fatal error in module file :/var/www/vhosts/babypro.be/httpdocs/modules/mollie/mollie.php:
Uncaught Error: Call to undefined method Smarty_Data::fetch() in /var/www/vhosts/babypro.be/httpdocs/modules/mollie/mollie.php:378 Stack trace: #0 /var/www/vhosts/babypro.be/httpdocs/modules/mollie/mollie.php(263): Mollie->getUpdateMessage('https://github....') #1 /var/www/vhosts/babypro.be/httpdocs/controllers/admin/AdminModulesController.php(868): Mollie->getContent() #2 /var/www/vhosts/babypro.be/httpdocs/controllers/admin/AdminModulesController.php(1117): AdminModulesControllerCore->postProcessCallback() #3 /var/www/vhosts/babypro.be/httpdocs/classes/controller/Controller.php(178): AdminModulesControllerCore->postProcess() #4 /var/www/vhosts/babypro.be/httpdocs/classes/Dispatcher.php(367): ControllerCore->run() #5 /var/www/vhosts/babypro.be/httpdocs/admin907d7pepe/index.php(58): DispatcherCore->dispatch() #6 {main} thrown

En na installatie van versie 4.0.8 kreeg ik deze foutmelding en was de Backoffice niet meer bereikbaar :
[PrestaShop] Fatal error in module file :/var/www/vhosts/babypro.be/httpdocs/classes/module/Module.php(1361) : eval()'d code:
syntax error, unexpected 'use' (T_USE)

Ook installatie van 4.0.6 geeft nu foutmeldingen.

### Environment
* PrestaShop version: 1.6.1.24 
* Mollie module version: 4.0.7 & 4.0.8 
* PHP version: 7.1.33

**Comment by tomjas1997** [comment]
Error has been fixed with newest version of mollie 4.0.8 , you can upgrade it at https://github.com/mollie/PrestaShop/releases/tag/4.0.8

**Comment by SimonasB88** [comment]
Hey @drwebbe wanted to double check, are you experiencing the same issue, and have you tried to update the module to the 4.0.8 or 4.0.9?
https://github.com/mollie/PrestaShop/releases/tag/4.0.9
https://github.com/mollie/PrestaShop/releases/tag/4.0.8

Best Regards.

**Comment by drwebbe** [comment]
Had 4.0.8 al geprobeerd (zie eerste post onderaan).
4.0.9 nog niet geprobeerd.

**Comment by SimonasB88** [comment]
@drwebbe ok, please check 4.0.9 and let us know the feedback.

Best Regards.

**Comment by SimonasB88** [comment]
Hey dear @drwebbe , have you managed to check the 4.0.9?

Best Regards.

**Comment by SimonasB88** [comment]
This ticket is closed due to lack of activity for some time.
If the issue wasn’t solved please raise a new ticket and our support team will assign a developer to it.
Have a nice day.
