### ISSUE TITLE
Orderstatus not translated

### ISSUE THREAD

**Issue by Goedkoopsteverf** [mollie/PrestaShop#216]
![Screenshot_2](https://user-images.githubusercontent.com/71271481/95479392-ffff7280-098a-11eb-91fb-5fb95c2a4fb7.png)
![Screenshot_1](https://user-images.githubusercontent.com/71271481/95477516-b7df5080-0988-11eb-9aef-225e334e54c3.png)
### Expected behavior
Correct display of translated items

### Actual behavior
After correcting the items in the translation file, the are incorrect displayed, the modifier is not present and deactivated statusses are not hidden, again excisting order statusses are created (see 1017 till 1020).

### Steps to reproduce the behavior
See translation file and backoffice

### Environment
* PrestaShop version: 1.7.6.5 
* Mollie module version: 4.0.9 
* PHP version: 7.2.34

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf thanks for the report,
Added to our TODO, will inform you about the fix.

Best Regards.

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf ,

Investigated the issue. The translation for the order statuses is added in Shop Parameters-> Order settings-> Statuses tab-> Edit Payment that you want to translate-> Edit status name in the language you want to display it.

![image](https://user-images.githubusercontent.com/29095235/96252152-2d1ad900-0fba-11eb-8c82-3bc2643c1e4c.png)

Please let us know if you will have any questions, else we can close this issue as well.
Best Regards.

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf have you got the chance to check this?
