### ISSUE TITLE
Add country in payment description 

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop#217]
The Mollie module provides the possibilty to add  {cart.id} {order.reference} {customer.firstname} {customer.lastname} {customer.company} to the description. Is it possible to add a country code?

We have to add something here first?:

`
public static function generateDescriptionFromCart($cartId, $orderReference = '')
    {
        if ($cartId instanceof Cart) {
            $cart = $cartId;
        } else {
            $cart = new Cart($cartId);
        }

        $buyer = null;
        if ($cart->id_customer) {
            $buyer = new Customer($cart->id_customer);
        }

        $filters = array(
            '%'                    => $cartId,
            '{cart.id}'            => $cartId,
            '{order.reference}'    => $orderReference,
            '{customer.firstname}' => $buyer == null ? '' : $buyer->firstname,
            '{customer.lastname}'  => $buyer == null ? '' : $buyer->lastname,
            '{customer.company}'   => $buyer == null ? '' : $buyer->company,
        );

        $content = str_ireplace(
            array_keys($filters),
            array_values($filters),
            Configuration::get(static::MOLLIE_DESCRIPTION)
        );

        return $content;
    }`

**Comment by SimonasB88** [comment]
Hey @basemedia thank you for your suggestion,
I have backloged the ticket, will come back to you after we will discuss with the team.

Best Regards.

**Comment by Goedkoopsteverf** [comment]
Advice don't install won"t work even what the develloper said, seach for a other PSP with betere payment plugins for Prestashop

**Comment by SimonasB88** [comment]
Hey @basemedia sorry for a delay in this thread,

We had some intensive work regarding the 4.1.0 release and fixes, so this case for now has been put for a side a little bit. We still need to check this and approve with Mollie.

We can slightly predict that this implementation would be included somewhere in future releases but we need to discuss about this improvement with Mollie. 

Thanks for your insight.

Can we close the issue for now? I can assure we have backloged this case for sure.

Best Regards.

**Comment by SimonasB88** [comment]
The issue was closed, due to the inactivity for some time.
If other issues will occur, please raise a new ticket.

Best Regards.
