### ISSUE TITLE
Error 500, niet installeren werkt gewoon totaal niet

### ISSUE THREAD

**Issue by Goedkoopsteverf** [mollie/PrestaShop#219]
### Expected behavior
Betaalmethode aan klanten aanbieden

### Actual behavior
Betaalmethode wordt aangeboden maar geeft direct daarop een error 500 (betreft alle versie 4.0

### Steps to reproduce the behavior
Versie V4.0.9 installeren of V4.0.8 en alles wijst vanzelf

### Environment
* PrestaShop version: 1.7.5.5 
* Mollie module version: 4.0.9 
* PHP version: 7.2.34

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf sorry to hear about this, but could you be more detailed?
Could you provide us the screen-capture reproduction step by step? Or at least more detailed steps with some graphics?

The cause of this could be multiple, maybe cache, maybe the Prestashop theme or maybe something else.

Best Regards.

**Comment by Goedkoopsteverf** [comment]
This is simple as our client has placed the items in the cart and choose wich paymentmethode will be used by clicking te conformation the nex screen apears with a error 500, this is not logged in the Prestrashop Logfiles.

**Comment by SimonasB88** [comment]
@Goedkoopsteverf ok, thanks for your information, did the client delete the old version from the Prestashop and all the folder, and do fresh 4.0.9 install?

Best Regards.

**Comment by SimonasB88** [comment]
@Goedkoopsteverf thanks for your feedback, we are checking this out with the team.
We will update you with the notification about the fix.

Best Regards.

**Comment by vdlsolutions** [comment]
Same problem here. Also a 500 error when the payment is started.

When debugging Prestashop I get:
Can't load Order status (id_order_state: 0)
at line 244 in file classes/PaymentModule.php

Apparently the configuration value cannot be loaded properly, so it is passed as 0 and then things go wrong.
In other words, the id_order_state is passed incorrectly. I was able to fix it temporarily to change the code below:

\modules\mollie\controllers\front\payment.php

```
$this->module->validateOrder(
            (int) $cartId,
	    (int) Configuration::get(Mollie\Config\Config::STATUS_MOLLIE_AWAITING),
            $totalPrice->toPrecision(2),
            isset(Mollie\Config\Config::$methods[$apiPayment->method]) ? Mollie\Config\Config::$methods[$method] : $this->module->name,
            null,
            $extraVars,
            null,
            false,
            $secureKey
        ); 
```

into:

```
        $this->module->validateOrder(
            (int) $cartId,
	    1,    // Temporary solution for the order status
            $totalPrice->toPrecision(2),
            isset(Mollie\Config\Config::$methods[$apiPayment->method]) ? Mollie\Config\Config::$methods[$method] : $this->module->name,
            null,
            $extraVars,
            null,
            false,
            $secureKey
        );
```

In /modules/mollie/src/config/Config/Config.php I see:
const STATUS_MOLLIE_AWAITING = 'mollie_awaiting';

We are using Prestashop 1.7.6.1
Upgrade Mollie module from 3.4.5 to 4.0.9

Hopefully you can find the cause and make a nice solution for it. Best Regards.

**Comment by krisvdb** [comment]
I have similar issue .  

Prestashop 1.6.1.24

Logs show following error.
PaymentModule::validateOrder - Order Status cannot be loaded

Same issue in 4.0.8
--

**Comment by SimonasB88** [comment]
Hey guys,
After you upgrade the module from 3.4.5 to 4.0.9 or 4.0.8, you should always reset the module additionally. 
We reproduced that case on localhosts and test environments.
We have backloged this, we will check what best we can do in order to solve this not user friendly solution.

Best Regards.

**Comment by Goedkoopsteverf** [comment]
Advice don't install won"t work even what the develloper said, seach for a other PSP with betere payment plugins for Prestashop
