### ISSUE TITLE
Double shopping carts are createrd

### ISSUE THREAD

**Issue by Goedkoopsteverf** [mollie/PrestaShop#221]
### Expected behavior
By order placement there must be one cart created

### Actual behavior
By order placement  there is after payment from one cart a double cart is created

![image](https://user-images.githubusercontent.com/71271481/95853880-618e5b00-0d56-11eb-8ea7-f372e8c0bc6e.png)

### Steps to reproduce the behavior
Place a order and do a payment session after the order has the orderstatus PAID a double cart is created with
the same content

### Environment
* PrestaShop version: 1.7.6.5 
* Mollie module version: 4.0.9 
* PHP version: 7.2.34

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf thanks for the insight,
backloged this, will update you when we include the fix.

Best Regards.

**Comment by SimonasB88** [comment]
Hey @Goedkoopsteverf  news from development team:

> We have implemented cart duplication functionality, because there was an issue when the client would make an order and if the order/payment would fail, the whole cart was deleted and the client needed to gather all the products all over again. So we added functionality when the client gets an error his cart get duplicated to not lose it and he would not need to gather his products to cart again.

Best Regards.

**Comment by hknobbe** [comment]
@SimonasB88 same issue here, is it possible to make sure that after payment the cart gets destroyed? We use follow up emails for when people leave there cart. Now when someone pays they receive an email that they left there cart. Not an ideal situation!

**Comment by SimonasB88** [comment]
Hey @hknobbe ! Well, I am afraid there is the best possible solution from Prestashop so far. If the cart gets destroyed, the user will be instantly redirected to the homepage, when he navigates by clicking Back on browser, or clicking 3D page Back on Payment link bottom left. This is not a good UX solution, we have discussed this in earlier issue tickets. So the solution was made only to duplicate the carts. Majority of the community wanted to navigate the "going back" actions by saving the carts. 

You mean, the clients get 2 emails of the cart left?

Best Regards.

**Comment by hknobbe** [comment]
Hi @SimonasB88,
I understand the UX standpoint.

No they don't receive 2 emails for the left cart, just 1.
They place the order get an confirmation mail, and after about 30 minutes they receive an email regarding the "new" unfinished cart.

![Schermafbeelding 2020-10-20 122335](https://user-images.githubusercontent.com/39634152/96574097-4f209e00-12cf-11eb-98a1-3877db4988e0.png)

This make the customer confused because they received the confirmation and an reminder for the exact same cart. Also not a great UX solution!

Let me know if I can get you some extra info.

Best Regards,

**Comment by SimonasB88** [comment]
Hey @hknobbe now that makes the point, that's right.
We have to discuss with the team and provide the satisfying overcome regarding this issue.

Best Regards.

**Comment by SimonasB88** [comment]
Hey guys,
After successful payment process memorized cart is now being removed by default. This behavior is added to ensure merchants wont have duplicated carts then they are not required.
We have tested and the functionality and cart duplication is no more in the next release.

Best Regards.
