### ISSUE TITLE
Missing information when no payment method chosen on Mollie.com

### ISSUE THREAD

**Issue by bmalynovytch** [mollie/PrestaShop#222]
### Expected behavior

A little reminder or warning when configuring the module and no payment method enabled on Mollie.com instead of a blank list misleading to a bug in the module.

### Actual behavior

When no payment method chosen on Mollie.com, the module get no payment method which leaves the "Payment method" block at the bottom of the configuration page empty.

### Steps to reproduce the behavior

- Install a brand new Prestashop
- Open a test account on Mollie.com (with no configuration)
- Install Mollie's PS module
- Configure the test key
- Configure Mollie plugin the be available as a payment method
- Loose 3 days digging the issues to understand why the plugin doesn't show up in the checkout process ...

### Environment
* PrestaShop version: 1.7.6.7 
* Mollie module version: 4.0.9 
* PHP version: 7.2.33

**Comment by SimonasB88** [comment]
Hello, thanks for the message @bmalynovytch,

Could you please provide us some screen-capture video how you reproduce the steps?

Best Regards.

**Comment by SimonasB88** [comment]
Hey @bmalynovytch 
We checked internally, it seems that kinda makes the sense from UX side.
We have backloged this, we will update you about the UX fix.

Best Regards.

**Comment by bmalynovytch** [comment]
Thats was the point 👍

**Comment by Goedkoopsteverf** [comment]
Advice don't install won"t work even what the develloper said, seach for a other PSP with betere payment plugins for Prestashop

**Comment by SimonasB88** [comment]
Hey @bmalynovytch sorry for a delay regarding this case.

We discussed with the our team, and it seems it will be included in the next upcoming release after 4.1.0 because there were many other top major bugs that the team was handling for a while.

I can assure we have backloged this in our TODO list. May we close this ticket for now?

Best Regards.

**Comment by bmalynovytch** [comment]
You may
