### ISSUE TITLE
Payment fails with coupon

### ISSUE THREAD

**Issue by hknobbe** [mollie/PrestaShop#223]
Hi all,

Just noticed a small bug with 4.0.9.
When you have a coupon selected, the order fails.

You can get through the whole order procces and after you selected for example ideal and click on pay.
You get a message saying there was an error please contact support team.

Coupon settings are:

- 10% discount and free shipping (also tried without free shipping, same result).
- voucers are vallid.
- 1 category selected under the product settings for the coupon.

Just rolled back to 4.0.7, same coupon, no problems.

Let me know if you need anything else!

Cheers,

Henk-Jan

**Comment by SimonasB88** [comment]
Hey @hknobbe thanks for your message,
Backloged this, we will replicate this and update you as soon as possible.

Best Regards.

**Comment by SimonasB88** [comment]
Hey @hknobbe we tried to reproduce the issue on PS1767 PHP 7.2 Mollie 4.0.9, but unfortunately couldn't successfully replicate the bug on iDEAL payment.
Could you please provide step-to-step video screen reproduction how you create a voucher and how you finalize the purchase via iDEAL payment?

Best Regards.

**Comment by AlexAlexE** [comment]
Yes, it's true. I get this error with 4.0.8 and 4.0.9
On screenshot was used voucer -10% 
![image](https://user-images.githubusercontent.com/20991267/96870449-351ec100-1471-11eb-8b69-a7b866680ddb.png)

**Comment by SimonasB88** [comment]
Hey @AlexAlexE and @hknobbe , we still can not recreate the discounting problem.

Could you check if I'm correct. I set the discounts through here:
![image](https://user-images.githubusercontent.com/29095235/97199656-eba7dc00-17b8-11eb-8b01-9178a66b3fbb.png)
![image](https://user-images.githubusercontent.com/29095235/97199755-09754100-17b9-11eb-958c-3169d79972e7.png)
![image](https://user-images.githubusercontent.com/29095235/97199796-17c35d00-17b9-11eb-9eb5-5121f6d5cf21.png)

![Kapture 2020-10-26 at 18 34 12](https://user-images.githubusercontent.com/29095235/97200783-5279c500-17ba-11eb-926f-343f4693aef8.gif)

Are you completing the same steps in Prestashop? 🤔 

Best Regards.

**Comment by Goedkoopsteverf** [comment]
Advice don't install won"t work even what the develloper said, seach for a other PSP with betere payment plugins for Prestashop

**Comment by SimonasB88** [comment]
@hknobbe any news on reproduction? 

Best Regards.

**Comment by SimonasB88** [comment]
Ticket was closed due to inactivity for some time. If the issue still appears in the newest releases, please raise a new ticket👍 

Best Regards.
