### ISSUE TITLE
js-mollie-alert "Locale is invalid"

### ISSUE THREAD

**Issue by greg-fr** [mollie/PrestaShop#225]
### Expected behavior
Test paiement for my prestashop site

### Actual behavior
I use the 4242 credit card. I configure molly with test API key, and Profile ID only.
I got a message in li.js-mollie-alert :
"Locale is invalid"

### Steps to reproduce the behavior
add a item to my basket and try to pay with a test credit cart

### Environment
* PrestaShop version: 1.7.6.8
* Mollie module version: 4.0.9
* PHP version: 7.3.20

**Comment by SimonasB88** [comment]
Hey @greg-fr thanks, we have backloged this.
Will update you about the fix.

Best Regards.

**Comment by SimonasB88** [comment]
Hey @greg-fr , we provide you an example about the German language.

Probably in BO there are the wrong language codes that are set wrong. 
If client is using the German language on his site, he should check if his Language code in BO is correct it should be **de-de** for the German language.

Please try, let us know the feedback.
And in case, we can close the issue as well after that.

Best Regards.

**Comment by greg-fr** [comment]
Well done !

My site language use 3 languages : fr/de/it.
and when i import the language pack for switzerland, i juste have fr code instead of fr-fr.

It's fixed now. Thank you!
