### ISSUE TITLE
european translation

### ISSUE THREAD

**Issue by pedalracer** [mollie/PrestaShop#229]
### Expected behavior
after nearly a year of developing V4.x I expect proper translations for European countries. I am from Germany and translation is missing.

### Actual behavior
backoffice modul translation is not wholly translated

### Environment
* PrestaShop version: 1.6.2.14
* Mollie module version: 4.0.9 
* PHP version: 7.4.x

**Comment by SimonasB88** [comment]
Hey @pedalracer , thanks for your insights.

We have agreed, referring to the user-friendly circumstances, that users can translate the module by themselves, navigating to:
![image](https://user-images.githubusercontent.com/29095235/97682080-b47b4880-1aa0-11eb-936f-ab5436e0a8f7.png)

Did you try to translate the strings?

Best Regards.

**Comment by pedalracer** [comment]
I get your point. However, since you represent a Payment Service Provider I had expected that your module would be made public with pre-translation. Perhaps something you can backlog.
