### ISSUE TITLE
Not working with PS 1.7

### ISSUE THREAD

**Issue by surudoiryu** [mollie/Prestashop#23]
The module gives an install error when trying to install it in PrestaShop 1.7.
Unable to use module, any plans to look at this and make it work ?

**Comment by ndijkstra** [comment]
Hi! We will look into it. I will let you know how to solve this problem.

**Comment by hostingnetwork** [comment]
De module werkt inderdaad niet in Prestashop 1.7. Is er een idee wanneer dit is opgelost?
Zou graag gebruik willen maken van Mollie in de nieuwe prestashop installatie!

Zou te gek zijn als dat probleem kan worden opgelost!

**Comment by Torrentus** [comment]
+1; Ook ik zou graag overgaan op PS 1.7, maar de onbeschikbaarheid van een Mollie-module houdt me tegen.

**Comment by lvgunst** [comment]
PrestaShop 1.7 is not released officially. They have only released an release candidate for developers.

Can you guys please explain what is not working? We'll look into it!

**Comment by JorritDiepstraten** [comment]
Prestashop 1.7 was released yesterday.

**Comment by GiveGreen** [comment]
Hopefully Mollie will update the module soon :). Would really like to use it in 1.7.

**Comment by GiveGreen** [comment]
I asked the Mollie support. Nick Dijkstra said it's unknown when a new version will be available.

**Comment by xBorderie** [comment]
Hey there Mollie team!

I work for the PrestaShop project, and want to know what's missing in the documentation for you to upgrade your module to 1.7. Don't hesitate to contact me!

**Comment by firstred** [comment]
PR for PrestaShop 1.7 here: https://github.com/mollie/Prestashop/pull/29

**Comment by xBorderie** [comment]
Thank you @firstred !

Mollie team, let us know if things can be improved on our part!

**Comment by staeren** [comment]
ik werk met prestashop 1.7.0.2. Is toch een officiële release intussen? Wanneer zal Mollie bruikbaar zijn aub?

**Comment by staeren** [comment]
i get this in log file: Mollie::__construct said: Betaalfout:Invalid API key: \'\'. An API key must start with \'test_\' or \'live_\'.

**Comment by lexzz** [comment]
@mollierobbert when will the mollie module be available for prestashop 1.7?

**Comment by firstred** [comment]
@ndijkstra @mollierobbert When will you merge my PR? :stuck_out_tongue_winking_eye: 
 
https://github.com/mollie/Prestashop/pull/29

**Comment by Martijn-SB** [comment]
Is there any fix yet to get this working with PS 1.7?
I managed to get it installed with the PR of firstred, but I am not able to see the payment method during checkout.

Any solution on this?

**Comment by firstred** [comment]
You might want to refrain from using PrestaShop 1.7

I've been trying to maintain the following modules for 1.7:
- Mollie
- Pay.nl
- Stripe
- (custom) PayPal

ALL of them BROKE from 1.7.0.0RC3 -> stable, 1.7.0.0 => 1.7.0.1 and now with 1.7.0.3 => 1.7.0.4

Therefore I'm just going to close the pull request. Screw PrestaShop and its unstable API!

**Comment by patrickdejongh** [comment]
Well, to all of you guys looking for a temporary solution (just been on the phone with Mollie for a PrestaShop 1.7.x plugin / same issues as OP), you can take a look at what this developer has to offer on [https://trendweb.nl/modules](https://trendweb.nl/modules). I bought the Mollie-extension for PS 1.7.x from this website for almost 16 Euro's and I can confirm it works on the most recent PrestaShop 1.7.0.6. 
I just hope this info will be useful for you guys. 
Still wishing that Mollie develops their own working plugin again.... Saving us cash and time! :) :)

**Comment by cmderks93** [comment]
Any news from mollie about the upgrade for using with 1.7?

**Comment by Lars-** [comment]
Would be great to see a new version, since Mollie looks very promising.

**Comment by willemstuursma** [comment]
We have released a [new version 2.0.0](https://github.com/mollie/Prestashop/releases/tag/v2.0.0) compatible with Prestashop 1.7.

Please let us know if it is working for you! If you have any issues, please open an issue here.

**Comment by willemstuursma** [comment]
I am sorry, the PS1.7 compatible version can be downloaded from our partner's web site: https://trendweb.nl/modules/mollie-betaalmodule-voor-prestashop-1-7/. 

We have pulled the release here because we don't want to risk P1.6 users installing the new version.
