### ISSUE TITLE
make payment options sortable

### ISSUE THREAD

**Issue by pedalracer** [mollie/PrestaShop#230]
### Expected behavior
In V3.5.5 payment option were sortable and in V4.x this is no more.
Moreover visually payment options in module settings look like if css is missing. In general I am missing coders love here :(

### Environment
* PrestaShop version: 1.6.2.14
* Mollie module version: 4.0.9 
* PHP version: 7.4.x

**Comment by SimonasB88** [comment]
Hey @pedalracer 
Backloged this and the sorting will be implemented in the next release. Thank you for you insights.

Best Regards.
