### ISSUE TITLE
Order canceled after being paid

### ISSUE THREAD

**Issue by mitchello** [mollie/PrestaShop#233]
Hello, 
There might be a strange behaviour with the management of  pending orders.

So here's what I'm facing.
I have some orders that have been paid and already shipped (for example, paid the 4th of October, shipped the 5th).

Today, while checking my orders, I saw that the one shipped on the 5th of October has been canceled so the 1st of November.
Note that I don't have any other modules that change the orders' status.

After some research, I have found some "new" features (July [WIP - adding order to pending cart association](https://github.com/mollie/PrestaShop/commit/75fd58de83a6c4236a846bc5729a99de78c00fcf)) that add the table mol_pending_order_cart and some associated services.

After having a look at the code, I saw that a temporary order is added in the database, with a cart number and so on.
Currently, the table contains every canceled orders, even the ones that have been paid and put in "Canceled".

That's the part where I'm not sure if the issue comes from the module or not.
I think the module "cleans" the table once in a while by checking the corresponding order and order status.
If it finds an order with a status that is different that "Payed" or "Shipped" (I don't really know), then it cancels the order.

At least, that's what I think.

Can you investigate to see if there's a possibility that this behaviour occurs in your module?

Thank you in advance.

Regards.

System information: 
Prestashop Version: 1.7.4.4
Mollie Version: 4.0.7

**Comment by Goedkoopsteverf** [comment]
Advice don't install won"t work even what the develloper said, seach for a other PSP with betere payment plugins for Prestashop

**Comment by SimonasB88** [comment]
Hey @mitchello thanks for your insights, we appreciate. 
I assure that team got your message, I have to check with the team, and come back to you with the reasonable answer.

By the way, have you tried the latest 4.0.9 version, and checked the code there?
And the Cancellation comes just only from Prestashop side or as well in Mollie account?

Best Regards.

**Comment by mitchello** [comment]
@SimonasB88 thanks for your answer.
I didn't try the latest version, maybe there's a fix regarding this point.
The cancellations are only visible from the back office of Prestashop, as paiements of canceled orders have already been transferred to my bank account.

Thanks again for investigating.

Regards.

**Comment by SimonasB88** [comment]
Hey @mitchello thank you,
This is really strange regarding the 4.0.7. 

What are your shipping conditions in Advanced Tab?
![image](https://user-images.githubusercontent.com/29095235/98214176-d9fbcc80-1f4e-11eb-8418-f2134f2aec50.png)

![image](https://user-images.githubusercontent.com/29095235/98214370-15969680-1f4f-11eb-9561-07cc400597b9.png)

Best Regards.

**Comment by mitchello** [comment]
Hi @SimonasB88 , 
Here are my advanced settings 
![image](https://user-images.githubusercontent.com/6321971/98229913-cc4c4400-1f5a-11eb-814c-df4c9d8477d4.png)

![image](https://user-images.githubusercontent.com/6321971/98229947-dbcb8d00-1f5a-11eb-868f-474e66c2841e.png)


Regards

**Comment by SimonasB88** [comment]
Hey @mitchello thank you for your insight. So as I understand you, you mean that Mollie is repeatedly checking the old order statuses? We are not sure if we are checking the old order statuses, unless it is a call from webhook from Mollie side.

Let's check this with our developers, I will try to get the technical answer.

Stay tuned!

Best Regards.

**Comment by mitchello** [comment]
Hi @SimonasB88 , it seems so but not for all orders. That's the tricky part as the behavior seems random, at least I haven't been able to identify a pattern.

Thanks again.

Regards.

**Comment by SimonasB88** [comment]
Hey @mitchello have you tried to check if the orders are randomly changing as well for your webshop on 4.0.9?

Best Regards.

**Comment by mitchello** [comment]
@SimonasB88 no I haven't tried yet.
I'll check that.

Regards.

**Comment by SimonasB88** [comment]
@mitchello check and let us know your feedback of course.

Best Regards.

**Comment by SimonasB88** [comment]
The ticket is closed due to inactivity for some time.
We sincerely advice to raise a new issue if in case the issue is still existing.

Best Regards.

**Comment by mitchello** [comment]
Hello @SimonasB88 , I have updated the module and the Prestashop version also.
The issue doesn't seem to be there, i'll open a new issue if this happen again.

Regards
