### ISSUE TITLE
Probelem with Mollie module

### ISSUE THREAD

**Issue by wkor86** [mollie/PrestaShop#235]
Hi,
I stack using Version 3.3.5 - that's the only version which works for me. All new version make issues everytime I try to upgrade your module. Today I completely deleted old module and installed 4.0.9 version. Unfortunately after some tests I had to uninstall it and instal 3.3.5 one more time

### Expected behavior
I set up everything on new instal of 4.0.9. I cleared cache...
I expected all payments which I have active will work

### Actual behavior
iDeal payment doesn't work for some languages of my store + even for main Dutch language it doesn't work for all the banks. It worked for ING but by KNAB I received error - that there is temporary problem with the connection with bank (later checked on v3,3,5 and no problem at all). On other languages it was often directly error with message - please contact shop support.

### Steps to reproduce the behavior
Hard to say. I set up to log all errors unfortunately no logs from Mollie module... No dev en prod logs either...

### Environment
* PrestaShop version: 1.7.6.4
* Mollie module version: 4.0.9
* PHP version: 7.1

**Comment by wkor86** [comment]
Maybe it is important - I always use 'Payment API' by payment options.

**Comment by SimonasB88** [comment]
Hey @wkor86 thank you for contacting us, I assure we have got your message.

Interesting, could you please navigate to your Module > Advanced tab> Enable the module Debug mode down there
![image](https://user-images.githubusercontent.com/29095235/98528792-77276f80-2285-11eb-86fb-9a012aa496c4.png)

And try to checkout again with KNAB payment and screenshot us what error message have you received.

Best Regards.

**Comment by wkor86** [comment]
Hi @SimonasB88 ,
as I see other issues which will get solved together with new release 4.1.0 I'll wait for that realease. Then I will try to install new version one more time with set Debug level on Log everything and provide all screenshots if errors will still occure...

**Comment by SimonasB88** [comment]
Hey @wkor86 yes sure you should definitely check our latest 4.1.0 release with the Debug level and check the logs of course.

Could you raise a new ticket if you detect an issue regarding 4.1.0? We could close this issue for now.

Best Regards.

**Comment by wkor86** [comment]
ok - no problem
