### ISSUE TITLE
Decimal problem when amount is 1000 or higher and decimal separator . is used

### ISSUE THREAD

**Issue by pswaab** [mollie/PrestaShop#236]
### Expected behavior
When making a payment of let's say 1,900.- with creditcard through mollie module using as a decimal sign . in stead of , customer only needs to pay 1.90 instead of 1900.

### Steps to reproduce the behavior
Order an item of 1,750.- with decimal separator ,

### Environment
* PrestaShop version: 1.7.6.7
* Mollie module version: 4.0.8
* PHP version: 7.2

**Comment by SimonasB88** [comment]
Hey @pswaab thanks for your activity!
Could you please explain, how you inputted the number in Prestashop product?
The Prestashop automatically changes the , to .
![Kapture 2020-11-09 at 13 37 43](https://user-images.githubusercontent.com/29095235/98537258-ac39bf00-2291-11eb-8f33-5a2db046dfe5.gif)

Thanks.
Best Regards.

**Comment by pswaab** [comment]
Hi @SimonasB88,

It is inserted without , and without .
On this site we only work with rounded prices.
But I have seen in version 4.0.9 that this was a bug fix, but Prestashop modules did not serve this update yet.
I think this is a major issue, almost sent this item to the customer, luckily someone checked the payment, and shipping was not automated.

![Screen Shot 2020-11-09 at 12 50 06](https://user-images.githubusercontent.com/18168933/98537867-341bcb00-228a-11eb-8547-40172f64499e.png)

But when going to mollie it showed 1.75 (in stead of 1750).

Kind regards,

Patrick Swaab

**Comment by SimonasB88** [comment]
Hey @pswaab 

Tried to reproduce the 1.75 on the testing environment, the transaction to Mollie seems to go smooth. It is really strange why. Yes once we have fixed the decimals error, you are right.

![image](https://user-images.githubusercontent.com/29095235/98657903-13677a00-234b-11eb-89a5-d8f143e03b29.png)

![image](https://user-images.githubusercontent.com/29095235/98658005-32fea280-234b-11eb-8ad6-d862b9c2a24d.png)


![image](https://user-images.githubusercontent.com/29095235/98657379-7a386380-234a-11eb-86d5-cee6c3c2fe0a.png)

Best Regards.

**Comment by pswaab** [comment]
Hi,

Here are two screenshots of my test with version 4.0.8 of the prestashop module.

The shopping cart is 1,760.00, and in Mollie the value is 1.76
![Screen Shot 2020-11-10 at 11 25 21](https://user-images.githubusercontent.com/18168933/98661993-79520280-2347-11eb-8ca2-89ac10dd93eb.png)
![Screen Shot 2020-11-10 at 11 24 15](https://user-images.githubusercontent.com/18168933/98661999-7a832f80-2347-11eb-9747-c006a1702b34.png)

Kind regards,

Patrick Swaab

**Comment by SimonasB88** [comment]
@pswaab could you upgrade module to 4.0.9 and test again this case?

Best Regards.

**Comment by pswaab** [comment]
Hi @SimonasB88 ,

That fixes the problem.

Thanks for your time and help.

Can this be a default test before releasing? This customer does not want to pay anymore, and we mis out on a big order.

Kind regards,

Patrick

**Comment by SimonasB88** [comment]
Hey @pswaab you are welcome, we are pleased to help our customers.

Yes, we will backlog this test case once again. Thanks.

Best Regards.
