### ISSUE TITLE
Users are redirected because payment can't be created

### ISSUE THREAD

**Issue by jacob-v-dam** [mollie/PrestaShop#238]
### Expected behavior
Users should be able to pay

### Actual behavior
Some users aren't able to create payments. They tried different computers but all seem to fail.

### Steps to reproduce the behavior
It is hard to reproduce. I'm able to create payments from different environments. But as said the users aren't. Nothing appears in my log file, even when loggin is enabled and set to `Everything`. The error happens when the user want to go to the payment page. If i check the `ps_mollie_payments` table i can't find the cart. So something is going on after the payment button.

### Environment
* PrestaShop version: 1.7.6.8.
* Mollie module version: 4.0.9.
* PHP version: 7.2.34

**Comment by SimonasB88** [comment]
Hey thanks for your message @jacob-v-dam sorry to hear this we believe that it is very annoying.

First thing, did you try to reset the module? I guess you did major upgrade from 3.5?

Second, is your order status set correctly to "Awaiting Mollie Payment"?
![image](https://user-images.githubusercontent.com/29095235/98693655-390b7800-2379-11eb-9fc5-1e296b708b67.png)

Best Regards.

**Comment by jacob-v-dam** [comment]
First I upgraded from the earlier version, but this gave some unexpected behavior, then we removed the module and reinstalled it. This is installation is uploaded 2020-10-21, so it is new.

I don't have the option "Send mails when Awaiting". To be sure I was running the latest version I downloaded the latest version from Github a second ago.

**Comment by SimonasB88** [comment]
Hey @jacob-v-dam so you downloaded Mollie 4.0.9 and now the users can do Orders?

Can you go to module Advanced Settings tab, and switch the Debug Levels 
![image](https://user-images.githubusercontent.com/29095235/98796430-09f61480-2414-11eb-858f-419974f90e0e.png)

And then please try to checkout and let us know what error do you get when redirected to the Mollie Payment page?

Thanks.
Best Regards.

**Comment by jacob-v-dam** [comment]
I already enabled this option. But nothing else then mollie webhooks appears in my log file. Even the files var/logs/ are not filled with mollie errors.

**Comment by SimonasB88** [comment]
Hey @jacob-v-dam ok, thanks for your information.

When you enable the Debug level, you can actually see what errors are appearing from API side when you click the final payment CTA button from Prestashop and when the module redirects the user to the Mollie payment 3D screen. Sometimes it is an essential part of many errors.

Could you please give us some video screen capture how the order is being made? 

Or in order to investigate your issue and help you efficiently, can you send us an access to your backoffice with its url and a FTP access to your store:

URL back office:
login back office:
password back office:

FTP host:
FTP login:
FTP password:
FTP port:

Send everything to support@invertus.eu. We will replicate the issue and provide you a conclusion.

Best Regards.

**Comment by jacob-v-dam** [comment]
After some more testing I found the error. It is the same as #227. When the user enters his mobile phonenumber in the number field the error raises by the Mollie API. This shouldn't be a problem.

On the other hand. I would expect this error to show up in the PrestaShop logs with error code 3 or 4. But this error is never logged! And yes I have enabled the debug info and logging set to everything:
![image](https://user-images.githubusercontent.com/310526/98963613-1b204d80-2508-11eb-8768-3bd05e77ee4e.png)

**Comment by jacob-v-dam** [comment]
I created a video due to privacy reasons this is send to your e-mail.

**Comment by SimonasB88** [comment]
@jacob-v-dam assuring that we got your video reproduction. Thanks.

Best Regards.

**Comment by SimonasB88** [comment]
Successfully fixed the phone issue for the client.
