### ISSUE TITLE
Missing payment methods depending on shipment option ( sendcloud pickup points )

### ISSUE THREAD

**Issue by krisvdb** [mollie/PrestaShop#239]
### Expected behavior
 All payment methods should be visible for all shipment options

### Actual behavior
We have different shipment options, ao 2 possible pickup point providers, selectable via the Sendcloud module
For 1 of the pickup point options, payment methods are suppressed.  All other options work fine as well. ( screenshot attached )
Only native PS Bankwire payment is visible.

Available carriers

![Available carriers checkout](https://user-images.githubusercontent.com/26024536/98729245-eb076c00-239a-11eb-9d54-7c341d460b6d.png)

Bpost

![available payment methods Pickup Bpost](https://user-images.githubusercontent.com/26024536/98729249-eba00280-239a-11eb-9986-196a6506784d.png)

DPD
![payment methods dpd pickup](https://user-images.githubusercontent.com/26024536/98729251-ec389900-239a-11eb-9b74-a1554f0cb756.png)

### Steps to reproduce the behavior
Shop is upgraded from 1.6 to 1.7.   Both sendcloud / mollie modules have been uninstalled/reinstalled.  shipment options recreated.

### Environment
* PrestaShop version: 1.7.5.0 
* Mollie module version: 4.0.9 
* PHP version: 7.1.33 
* Mollie : payment API is selected
* No cache ( smarty or apcu ) active

**Comment by jacob-v-dam** [comment]
Did you check the box when you go to "Verbeteren -> Betaling -> Instellingen" and then at the bottom?

Like this:
![image](https://user-images.githubusercontent.com/310526/98784330-3f423880-23fb-11eb-9eec-90f6032ca242.png)

**Comment by SimonasB88** [comment]
Hey @krisvdb sorry to hear about this annoying thing,

I have to agree with @jacob-v-dam and also, check the enabled Payments, are the countries set correctly to ALL or the ones you need?
![image](https://user-images.githubusercontent.com/29095235/98795171-98699680-2412-11eb-8556-617d7f42e6c9.png)

Best Regards.

**Comment by krisvdb** [comment]
Hey Jacob

Indeed,  mollie wasn't activated for these carriers generated by the
Sendcloud Module.
Thanks a million !


Kris

Op wo 11 nov. 2020 om 08:52 schreef Jacob van Dam <notifications@github.com

**Comment by SimonasB88** [comment]
@krisvdb @jacob-v-dam great community help!

Have a great day!

Best Regards.
