### ISSUE TITLE
landbeperkingen

### ISSUE THREAD

**Issue by Frankyet** [mollie/Prestashop#24]
Niet mogelijk bepaalde betaal methodes te beperken voor een land, zoald ideal alleen voor nederland, Bancontant aleen voor Belgie en Sofortbanking alleen voor duitsland.

**Comment by ndijkstra** [comment]
Bedankt voor je feedback. Op dit moment staat nog niet op de planning om onze Prestashop plugin aan te passen. Je zou natuurlijk wel altijd een PR kunnen doen zodat we hier naar kunnen kijken.
