### ISSUE TITLE
Problem With version 4.0.9 Mollie

### ISSUE THREAD

**Issue by LCEbxl** [mollie/PrestaShop#240]
I had the version 4.0.8 and everthings went good. I've upgraded Prestashop to 7.7.6.7 and after that Mollie ask me to updated its module to version 4.0.9
I have downloaded the Zip file and inserted it in the Prestashop backoffice (insert a module).
The download was refused because the file size was bigger than 2MB.
I went through filezilla to upgrade to version 4.0.9 and it worked.
Except that currently when someone wants to pay, a page error 500 appears.  

### Expected behavior

the payment page should have worked
### Actual behavior

currently when someone wants to pay, a page error 500 appears.  
### Steps to reproduce the behavior

here are the problems displayed quad I put the sit in debug mode : https://we.tl/t-5mYjiY7EQU
Tnak you in advance !
### Environment
* PrestaShop version: 1.7.6.7 
* Mollie module version: 4.0.9 
* PHP version: 7.4

**Comment by SimonasB88** [comment]
Hey @LCEbxl 
Assuring that the issue was registered. Stay tuned we will update!

Best Regards.

**Comment by SimonasB88** [comment]
Hey @LCEbxl 
It seems that the module is updated from 3.5.5 to 4.0.9 version. There was a bug when upgrading that one of Mollie statuses haven’t been installed. Resetting the module should do the fix. Or wait until we release 4.1.0 Mollie version and upgrade the module because this issue will be fixed with the 4.1.0 version release.

Could you please reset the module and try the purchasing process in your webshop and let us know the feedback!

Best Regards.

**Comment by LCEbxl** [comment]
Hey simonasB88,
thank you for your comment
I tried to update via the prestashop backoffice but an error message tells me that the file is too big (more than 2 MB).

I tried to upload the mollie via the ftp of my website (via fileZilla) and there is no more error 500.

However, now, when I place an order, if I choose Bpost (home delivery) mollie is not displayed as a means of payment.

Do you know why? 

Thank you in advance

**Comment by SimonasB88** [comment]
Hey @LCEbxl 

Regarding the file upload issue, you must increase the file uploading compatibility from server-side.

Regarding the Payment displaying, please check the payment Countries option

![image](https://user-images.githubusercontent.com/29095235/99795264-2856c100-2b34-11eb-9259-8db0e3195ff9.png)

And the Payment and Carrier Preferences in Prestashop for all required countries

![image](https://user-images.githubusercontent.com/29095235/99795497-8edbdf00-2b34-11eb-8e8e-52ce753e05c7.png)

Best Regards.

**Comment by LCEbxl** [comment]
Hey @SimonasB88 ,
Everythings works succesfully ! 

A lot of thanks 

Have a nice day, 

Patricia

**Comment by SimonasB88** [comment]
Hey @LCEbxl that's a great news!

Best of Luck!
