### ISSUE TITLE
More surcharge information

### ISSUE THREAD

**Issue by jacob-v-dam** [mollie/PrestaShop#245]
### Expected behavior
The surcharge ability is a nice function and should be kept in this module. But it would be better to inform the customers about the surcharge. At the moment the surcharge only appears when the customer goes to the checkout page, this is confusing and can lead to missing customers.

### Actual behavior
I would like to see that the surcharge is displayed after the payment option, like (+€ 1,99). The order total should be updated with the surcharge as well to inform the customer about the total price.

### Steps to reproduce the behavior
Enable surcharge and checkout.

### Environment
* PrestaShop version: 1.7.6.8
* Mollie module version: 4.1.0
* PHP version: 7.2.0

**Comment by SimonasB88** [comment]
Hey @jacob-v-dam thanks for your insights!

Yes it seems kinda good case you suggest.

We should recommend to check this improvement with info@mollie.com. All the design, UX, UI cases are dealt with them firstly.

Best Regards.

**Comment by SimonasB88** [comment]
The issue was closed, due to the inactivity for some time.
If other issues will occur, please raise a new ticket.

Best Regards.
