### ISSUE TITLE
Upgrading from 4.1 to 4.1.1 removed Mollie from the displayPaymentEu hook

### ISSUE THREAD

**Issue by Steven44223** [mollie/PrestaShop#248]
### Expected behavior
Display Mollie on the EU checkout page

### Actual behavior
Mollie is not displayed on the EU checkout page

### Steps to reproduce the behavior
Upgrade from 4.1 to 4.1.1

After upgrading from 4.1 to 4.1.1 Mollie was removed from the displayPaymentEu hook. Mollie does not show up anymore on the checkout page.

Solution:
Transplant a module option in modules -> positions -> transplant a module. Selected the Mollie module and Transplant to displayPaymentEu -> Save.

Now the module is showing again on the checkout page.

### Environment
* PrestaShop version: 1.6.1.24
* Mollie module version: 4.1.1
* PHP version: 7.2.34

**Comment by Maz-Invertus** [comment]
Hi @Steven44223 ,

Thanks a lot for the quick feedback. The release has been updated, please check it and let us know the outcome: https://github.com/mollie/PrestaShop/releases/tag/4.1.1

**Comment by Steven44223** [comment]
Hi @Maz-Invertus ,

The updated version works fine, it doesn't remove the displayPaymentEu hook if the Prestashop version is 1.6.x

**Comment by Maz-Invertus** [comment]
Hi @Steven44223 thank you for confirmation. We are going to close this ticket.
