### ISSUE TITLE
PS 1.6.1.7 geen orders in BO

### ISSUE THREAD

**Issue by yaya85** [mollie/Prestashop#25]
Heren,

Wij maken de overstap van Sisow naar Mollie en hebben de nodige instellingen doorgevoerd maar zowel met het test API als de Live API worden de orders niet ingeschoten in de webshop. 

Er wordt in alle tijden de onderstaande aangegeven.

_Welkom terug
Er is nog geen definitieve betaalstatus bekend. U wordt op de hoogte gesteld zodra de bank de status doorgeeft._

Please advice!

Thanks

Jason

**Comment by lvgunst** [comment]
Hallo Jason,

Waarschijnlijk kan Mollie de status van de betaling niet rapporteren aan je webshop. Is de website live en voor iedereen bereikbaar? 

Kan je een mail sturen naar info@mollie.com met je Mollie partner ID? Dan kunnen we kijken wat er precies verkeerd gaat.

Groet, Lennard

**Comment by yaya85** [comment]
Beste Lennard, 

Bedankt voor je snelle reactie, helemaal gelijk ik had de shop nog op maintenance staan.

Dank!!

**Comment by lvgunst** [comment]
Geen probleem. Succes met je webwinkel!
