### ISSUE TITLE
Can't load Order status

### ISSUE THREAD

**Issue by musicpanda** [mollie/PrestaShop#250]
Ik heb een webshop gekopieerd en ben bezig de kopie (een ander domein) in te richten.

Bij de Mollie module gekomen kreeg ik in de backoffice de dwingende optie om up te graden. De eerste poging mislukte maar de tweede slaagde (vreemd: dat gebeurde zowel op de server als op de localhost kopie). De resulterende versie is 4.0.9. Een beetje merkwaardig aangezien de laatste versie 4.1.1 is. De oorspronkelijke versie weet ik niet zeker. Het zou 3.5.4 kunnen zijn want dat is de versie van het originele domein.

Ik heb verder de configuratie settings nog niet veranderd.

Als ik nu naar de frontoffice ga en een bestelling plaats dan kom ik tot en met het punt waar ik mijn bank kies voor iDeal. Als ik dan op de button klik krijg ik bovenstaande error (zie ook bijgevoegd plaatje). 

De Prestashop versie is 1.7.6.1. PHP versie: 7.2 op server; 7,3 op localhost. 

In de errorlog van de server (maar niet van de localhost) vond ik een Mollie gerelateerde error:

> [Sat Nov 28 16:10:14.081365 2020] [proxy_fcgi:error] [pid 837012:tid 140660531238656] [client 88.86.44.41:53306] AH01071: Got error 'PHP message: PHP Fatal error:  Class '_PhpScoper5eddef0da618a\\Symfony\\Component\\DependencyInjection\\Container' not found in /var/www/vhosts/mysite.nl/httpdocs/modules/mollie/vendor/symfony/dependency-injection/ContainerBuilder.php on line 49\nPHP message: PHP Fatal error:  Interface '_PhpScoper5eddef0da618a\\Symfony\\Component\\DependencyInjection\\ResettableContainerInterface' not found in /var/www/vhosts/mysite.nl/httpdocs/modules/mollie/vendor/symfony/dependency-injection/Container.php on line 38\n', referer: https://mysite.nl/admin123/index.php/improve/modules/manage?_token=N7fVo5fUVNli6Eq4fEijAVnXBPvLEWHt1UMOxEWViaM

![mollie1](https://user-images.githubusercontent.com/13930107/100524590-add41400-31b9-11eb-835f-0a50cc50c01e.jpg)

**Comment by SimonasB88** [comment]
Hello @musicpanda 
We understand your issue, it sometimes happens when upgrading the module from 3.x.x version to the 4.x.x version.
Now, from 4.1.0 and 4.1.1 the upgrade problem should be fixed. There is double installation functionality, which allows to install the module successfully.

In your case, have you tried to reset the module after upgrade? Is it happening in 4.1.1 only? 

Best Regards,

**Comment by musicpanda** [comment]
"from 4.1.0 and 4.1.1 the upgrade problem should be fixed"

Very nice. But I have now 4.0.9 and it doesn't  show an option to upgrade. As I told it doesn't upgrade to the latest version.

**Comment by musicpanda** [comment]
I now have upgraded to 4.1.1 by installing that version over the old installation. 

Now I no longer get a crash. But...... for a test I went until the bank website. I didn't make a payment. Yet I got an email that I had paid and that my order was finished.

**Comment by Saimis777** [comment]
@musicpanda Hey, did everything work out the way you wanted? Or have you encountered any further issues? Let us know, we are here to help you out!

--
Invertus Support team

**Comment by musicpanda** [comment]
Hello Saimis,
Did you even read my last comment?

**Comment by Saimis777** [comment]
Correct, just wanted to confirm if the issue persists. And I understand this is frustrating, but could you clarify, after the update, which setting did you use? (from the added screenshot) As it allows you to choose when to send a confirmation email, before making the payment, when the order is created, or when it's paid, and by default Prestashop creates orders when customer is redirected to a payment screen.

Looking forward to your reply!

![image](https://user-images.githubusercontent.com/75423142/101456480-ca501900-393c-11eb-9287-242fad9905ec.png)

**Comment by Saimis777** [comment]
Hello again,

Due to inactivity we are going to close this issue for now, but if you are still encountering it, let us know, better yet you can contact us at - support@invertus.eu with your front office/back office details for further investigation, we would gladly help you out!

Best regards,
Invertus Support team
