### ISSUE TITLE
Payment methods not show up in checkout

### ISSUE THREAD

**Issue by Flightys** [mollie/PrestaShop#251]
### Expected behavior
All my payment methods should be showed for customer at check out

### Actual behavior
My payment methods  not appear

### Steps to reproduce the behavior
?

### Environment
* PrestaShop version:  1.7.6.4
* Mollie module version: 4.0.8
* PHP version: 7.1.26 ?????

**Comment by Flightys** [comment]
Dit zijn mijn instellingen:
![Naamloos](https://user-images.githubusercontent.com/64925367/100838265-6e841c80-3472-11eb-884c-209a5d1d0f45.png)
![Naamloos1](https://user-images.githubusercontent.com/64925367/100838274-70e67680-3472-11eb-94c2-dced28849259.png)
![Naamloos2](https://user-images.githubusercontent.com/64925367/100838281-72b03a00-3472-11eb-8a36-2b67f31be07e.png)

**Comment by SimonasB88** [comment]
Hello @Flightys 

Please select the countries that the payment should appear in.
![image](https://user-images.githubusercontent.com/29095235/100857457-5ffb2c80-3495-11eb-9f8a-de40c17c38e2.png)

Please select that and let us know.
Best Regards.

**Comment by Flightys** [comment]
Why this suddenly not work anymore? Before it always work fine, now you have to select countries in Mollie module. I check all the countries in my payment module. Now the Mollie payments work but not my custom payment for bank transfer.

**Comment by Saimis777** [comment]
@Flightys Hey, have you managed to resolve it? If not, would you be able to raise a separate ticket regarding this issue? Thanks in advance!

--
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

Due to inactivity we are going to close this issue for now, if you are still encountering, no worries, please contact our support team via email - support@invertus.eu with your front office/ back office details, and we will take a look at the issue from your environment! 

Best regads,
Invertus Support team
