### ISSUE TITLE
085 phonenumber not allowed

### ISSUE THREAD

**Issue by jacob-v-dam** [mollie/PrestaShop#253]
### Expected behavior
Allow any phonenumber even when it starts with 085.

### Actual behavior
See title

### Steps to reproduce the behavior
Enter a phone number which starts with 085, this is not allowed in the Netherlands. When you enter a local extension like 020 it works fine.

But 085 is used for companies, just like 088

### Environment
* PrestaShop version: 1.7.7.0
* Mollie module version: 4.1.1
* PHP version: 7.3.0

**Comment by Saimis777** [comment]
Hey, thanks for your message.

We've registered the error, and passed it to our engineers, and will update you on this thread.

--
Best Regards
Invertus Support Team

**Comment by Saimis777** [comment]
@jacob-v-dam We were not able to re-create the issue from our end. Would you be able to maybe share some detailed screenshots and steps of how we can reproduce this issue from our end? 

--
Best regards
Invertus Support team

**Comment by jacob-v-dam** [comment]
![image](https://user-images.githubusercontent.com/310526/101390827-b916f600-38c3-11eb-8aa6-ab6385099b23.png)
You can use my business number, this causes an error.

I use a one page checkout module, but this also happens with the normal checkout.

**Comment by Saimis777** [comment]
Thanks for that, will check further!

--
Best regards
Invertus Support team

**Comment by Saimis777** [comment]
Hey, unfortunately we could not encounter any errors, even when adding the same details as you've pasted above, we recreated the issue on PS1770 demo.

--
Best regards
Invertus Support team

**Comment by Saimis777** [comment]
Maybe you could also provide a screenshot of the error itself after you've done it with the same credentials from your end? It would definitely help us identifying the issue.

Thank you, and looking forward to your reply!

--
Best regards
Invertus Support team

**Comment by Saimis777** [comment]
@jacob-v-dam are you still encountering this issue? Or you've found a resolution? 

Looking forward to your reply!

--
Best regards
Invertus Support team

**Comment by jacob-v-dam** [comment]
![image](https://user-images.githubusercontent.com/310526/102007382-f1399100-3d28-11eb-99d5-bda977ba7ca3.png)
I still am. I updated to version 4.1.2.

**Comment by Saimis777** [comment]
Thank you for your update, we're continuing the research on why this is happening, and will fix it as soon as possible!

Thank you for your patience.

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @jacob-v-dam could you clarify if the issue persists with the latest Mollie version 4.1.3? You can download it here - https://github.com/mollie/Prestashop/releases

If 085 phone is still not allowed, please let me know!

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello, hope you're having a nice day!

The official Mollie 4.2.0 was just released, the fix was implemented, you can download the latest version here - https://github.com/mollie/PrestaShop/releases/tag/4.2.0

Any feedback regarding the updated version is greatly appreciated!

--
 Best regards,
 Invertus Support team
