### ISSUE TITLE
Exception on hook paymentOptions for module . Notice: Undefined index: isApplePayMethod

### ISSUE THREAD

**Issue by jacob-v-dam** [mollie/PrestaShop#254]
### Expected behavior
No error in log regarding this paymentoption

### Actual behavior
See title

### Steps to reproduce the behavior
Enable Apple Pay. This happend with all the versions and older prestashop versions to.

### Environment
* PrestaShop version: 1.7.7.0
* Mollie module version: 4.1.1
* PHP version: 7.3

**Comment by Saimis777** [comment]
Hey!

Could you clarify which currency are you using within your store? As Apple Pay is available with EUR currency.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
@jacob-v-dam Do you have any further questions? Was your issue resolved? Did you find a solution?

Looking forward t hearing back from you!

--
Best regards,
Invertus Support team

**Comment by jacob-v-dam** [comment]
I use EUR indeed. But since version 4.1.2 the issue has been solved.
