### ISSUE TITLE
installation gives error: Compile Error: Declaration of Mollie::getContainer

### ISSUE THREAD

**Issue by qualityangel** [mollie/PrestaShop#256]
### Expected behavior
Installation of the mollie module

### Actual behavior
Compile Error: Declaration of Mollie::getContainer($id = false) must be compatible with ModuleCore::getContainer(): Symfony\Component\DependencyInjection\ContainerInterface

[Symfony\Component\Debug\Exception\FatalErrorException 0]

### Steps to reproduce the behavior
try to install the module in to Prestashop 1.7.7.0

### Environment
* PrestaShop version: 1.7.7.0
* Mollie module version: 4.1.1
* PHP version: 7.3

**Comment by projexweb** [comment]
Hi
Same problem when trying to upgrade tp prestashop 1.7.7

**Comment by Saimis777** [comment]
Hey, thank you for your message, we are currently aware of the on-going issue, and working on resolving it, you can follow it here - https://github.com/mollie/PrestaShop/issues/252

Once it's resolved it will be updated in that thread!

Thank you for your patience.

--
Invertus Support team

**Comment by SimonasB88** [comment]
Closed because of duplication.
