### ISSUE TITLE
custom title is not added to setCallToActionText when set on configuration page

### ISSUE THREAD

**Issue by ijzershop** [mollie/PrestaShop#258]
### Expected behavior
in the payment.tpl for example at `<span class="calltoaction col-9 mt-2">{$option.call_to_action_text}</span>`
you should get the payment option title when this is set in the configuration page of the mollie module.

### Actual behavior
$option.call_to_action_text only returns payment option name not the title

### Steps to reproduce the behavior
Set an payment option title and check in the payment overview at the checkout

### FIX ###
I changed the lines 821, 871, 929 in de mollie.php file:
old: `->setCallToActionText($this->lang($methodObj->method_name))`
modified: `->setCallToActionText(!empty($methodObj->title) ? $methodObj->title : $this->lang($methodObj->method_name))`

### Environment
* PrestaShop version: 1.7.6.9 
* Mollie module version: 4.1.2 
* PHP version: 7.2.25

**Comment by Daaaaad** [comment]
Thank you @ijzershop ! Your solution works on PrestaShop 1.7 but not 1.6 😔

What's the purpose of the title field in the admin section? Should this field replace the method name if filled?

Regards,

David.

**Comment by Saimis777** [comment]
Hello, hope you’re having a good day.

Sorry for the late response, and thank you for your patience, this functionality was made on purpose by Mollie, we will get in touch with them personally to confirm if it will be changed, or it will stay as it is now, and will definitely update you regarding this matter!

Please follow this thread for further information!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello, hope you're having a great day so far!

I would like to not, that this functionality will be changed in the upcoming 4.3.0 release, I would like to also mention that that 4.2.0 version of Mollie was just released, and it can be downloaded here - https://github.com/mollie/PrestaShop/releases/tag/4.2.0

The 4.3.0 will be uploaded here once it's ready as well, so be sure to follow that repository!

I will close this issue for now, any feedback regarding the latest version is greatly appreciated!

Best regards,
Invertus Support team

**Comment by ijzershop** [comment]
No problem Saimis777 i can edit is when i update the mollie plugin. The question that keeps my interest is why put that option in the module if you are not using it? Is there an specific reason?

**Comment by Saimis777** [comment]
Hello,

I did not receive a full clarification on why this was implemented, but I can definitely confirm that it will be changed in the 4.3.0 release, and no specific reason was provided, sorry.

Best regards,
Invertus Support team
