### ISSUE TITLE
Resend payment link mail wrong template in multistore

### ISSUE THREAD

**Issue by imagicuus** [mollie/PrestaShop#259]
### Expected behavior
When you press on the resend payment link button from orders list page the send mail should be in the template of the store where the person placed the order from.

### Actual behavior
The template of this mail (logo and shop name) are now shown from the main store and not from the store the purchase was made.

### Steps to reproduce the behavior
When there is an unfinished order in a multistore environment and you press the button the resend the payment link the logo and shop name are from the main store and not from the store the order was placed from.

### Environment
* PrestaShop version: 1.7.7.0 
* Mollie module version: 4.1.2 
* PHP version: 7.3.25

**Comment by Saimis777** [comment]
Hello, thank you for your message.

We've registered your issue, and passed it to our team, we will look in to it, if any additional information will be needed, we will inform you, and get back to you with an answer ASAP!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @imagicuus sorry for the late reply. We've investigated this issue, and double checked, and confirmed that this is a multistore issue, as Mollie is created to be used with single store, this at the moment can't be changed, but it's in the future plans of making it fully compatible with multistores as well. Sorry for the inconveniences,I will close this issue for now, and if you will have any further questions or concerns, please let me know!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @imagicuus we're currently in progress of estimating the work for making multistores compatible with Mollie, and your encountered issue is without a doubt a priority as well, but for further investigation regarding your case, and to make sure we would implement all needed fixes, we would need to also test out your store, would you be able to send us your store zipped, database, and BO + FO + FTP details to - support@invertus.eu?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @imagicuus ,

As Mollie is planning to make multistores compatible in release version 4.3.0, I will close this issue for now, if you will need any further assistance at all, let us know!

By the way, the 4.2.0 version was just released, you can download the new version here - https://github.com/mollie/PrestaShop/releases/tag/4.2.0

Closing the issue for now.

Best regards,
Invertus Support team
