### ISSUE TITLE
Refund not possible

### ISSUE THREAD

**Issue by jrswebdesign** [mollie/PrestaShop#261]
### Expected behavior
When we do a return Standard / or Partial on Back Office of Prestashop, it’s not connecting automatically with Mollie Refund ? Before its was working automatically. Now we have to go to mollie and refund over there manually. We are using the latest version of the plugin.

### Steps to reproduce the behavior
Go to orders and open an order. When you are in the order details screen there is no mollie refund option.

### Environment
* PrestaShop version: 1.7.7.0
* Mollie module version: 4.1.2
* PHP version: 7.3.25

**Comment by Saimis777** [comment]
Hello, and thank you for your message.

We've registered your issue, and will take a look at it as soon as possible! Also, the button there before, right? And did it disappear just only after upgrading your versions of plugin/prestashop?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by jrswebdesign** [comment]
Hello,

Yes it was working before and disappear after the new Mollie upgrade to 4.1.2

Thank you and have a nice day!

**Comment by jrswebdesign** [comment]
Hello, is there any update about this problem?

Thanks!

**Comment by Saimis777** [comment]
Hello, we've reproduced the issue in our test environment, and the refund button seems to be in place, the version of the module we've tested was 4.1.2 (adding screenshots). Have you tried to install the latest version 4.1.3 of the module? Also, be sure to reset the module after updating it.

You can download the latest version here - https://github.com/mollie/Prestashop/releases

Looking forward to how it will go for you!

Best regards,
Simonas
![image](https://user-images.githubusercontent.com/75423142/102496663-5d492b80-4080-11eb-888f-b9a85fceb23c.png)

**Comment by jrswebdesign** [comment]
Hello Simonas,

I just check my webshop today and see that everything is working fine right now.

Maby it was a caching problem.

Thanks for you time.

This ticket can be closed.

Have a nice day!
