### ISSUE TITLE
Template "@PrestaShop/Admin/Common/Grid/Actions/Row/second_chance.html.twig" is not defined.

### ISSUE THREAD

**Issue by RobMeerwijk** [mollie/PrestaShop#262]
### Expected behavior
Working module 

### Actual behavior
Not working enviroenment: 
Error 500
   or 
"Template "@PrestaShop/Admin/Common/Grid/Actions/Row/second_chance.html.twig" is not defined."

### Steps to reproduce the behavior
Plain 1.7.7 prestashop, default theme and 4.1.2 mollie, happening in several locations, e.g. Orders

### Environment
* PrestaShop version: 1.7.7.0 
* Mollie module version: .4.1.2 
* PHP version: 7.3.19-1~deb10u1

**Comment by Saimis777** [comment]
Hello, and thank you for your message.

Maybe you could elaborate a bit more with this error, are you receiving it just by entering "orders" section or any others? Or you've done any specific steps to encounter it? Any further information or screenshots would be great help, thank you!

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by RobMeerwijk** [comment]
Hi, 
I was a bit to hasty by claiming multiple locations. Probably it happened twice at the same location: "Orders". 
I think it happened after I cancelled a payment and then I switched to orders. Then the order list failed because second_chance.twig is not defined in the default Prestashop template. I grepped all the source-code in the shop-dir and the only call using `second_chance `is from mollie 

`
![Uploading error msg.png…]()
/mollie/mollie.php:            ->addBefore('date_add', (new \PrestaShop\PrestaShop\Core\Grid\Column\Type\Common\ActionColumn('second_chance'))`
and 
`/mollie/mollie.php:            ->addBefore('date_add', (new \PrestaShop\PrestaShop\Core\Grid\Column\Type\Common\ActionColumn('second_chance'))`

Error in [shopdir]/var/logs/prod.log:

`[2020-12-15 13:18:58] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Template "@PrestaShop/Admin/Common/Grid/Actions/Row/second_chance.html.twig" is not defined." at /mnt/disks/disk_1/www/sauna-bouwen/shop/src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/action.html.twig line 53 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Template \"@PrestaShop/Admin/Common/Grid/Actions/Row/second_chance.html.twig\" is not defined. at /mnt/disks/disk_1/www/sauna-bouwen/shop/src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/action.html.twig:53)"} []`

**Comment by Saimis777** [comment]
Thank you for that, will pass this to our team to check further, and let you know with the outcome, your patience is greatly appreciated!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Also, could you clarify, have you tried clearing your cache fully? If yes, did nothing change?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by RobMeerwijk** [comment]
Clearing the cache did not fix it. I think you are calling a "twig" that is not defined in the default Prestashop template. I suggest you check the excistence of this specific twig in the template before you call it.

**Comment by Saimis777** [comment]
Thank you for that, we will check further, and will let you know, thanks for your patience!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Installed fresh PS 1.7.7.0 and released 4.1.2 mollie

Made some payments to get second chance email icon, seems to be working correctly. During development of this functionality i received such error but when i cleared cache it disappeared.

As you can see there is second_chance.html.twig file
![image](https://user-images.githubusercontent.com/75423142/102238118-12070f80-3efe-11eb-9701-ffb4caf2cc95.png)

Orders with icon:
![image](https://user-images.githubusercontent.com/75423142/102238258-36fb8280-3efe-11eb-9d09-301d54166647.png)

Best regards,
Invertus Support team

**Comment by RobMeerwijk** [comment]
I tried a different browser on a different computer on which I have never opened the prestashop admin account. There I had the same error, so it came to me that you maybe meant server cache, so I tried to clear out the template cache in stead of browser cache. I actually switched of cache all together. Still the same error. Then I deinstalled and removed mollie completely. Reinstalled again, and now it is working. It seems something went wrong. After the 500 error (Prestashop 1.7.7 error #252) I could only remove mollie by removing the mollie subdir in modules. Apparently you need to manually install / reinstall / install in stead of just install... Problem solved.
