### ISSUE TITLE
Klarna Belgium

### ISSUE THREAD

**Issue by pantoffelke** [mollie/PrestaShop#267]
### Expected behavior
klarna in payment methods front for address Belgium

### Actual behavior
It show when country Netherlands or Germany but when have Belgium it won't show. 

### Steps to reproduce the behavior
Make Klarna available for Belgium in front

### Environment
* PrestaShop version: 1.7.7.0 also on 1.6.1.24
* Mollie module version: 4.1.3 
* PHP version: 7.1.33
* All countries are selected for Pay later in mollie module, even when select just Belgium it won't show.

**Comment by Saimis777** [comment]
Hello and thank you for your message.

We will check this issue out, and will get back to you with an update regarding it!

Please follow this thread for the updates.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
@pantoffelke Could you also clarify please if in the preferences tab Belgium doesn't have any restrictions for making payments via Mollie? Adding a screenshot of what I have in mind.

![image](https://user-images.githubusercontent.com/75423142/102980434-3c655800-4510-11eb-9c7b-6d8b38a9fd1b.png)


--
Best regards,
Invertus Support team

**Comment by pantoffelke** [comment]
Its active, because other payments work for Belgium.
![Schermafbeelding 2020-12-23 om 10 19 09](https://user-images.githubusercontent.com/75521527/102980884-80ecf580-4508-11eb-838e-04178a04ab9b.png)

**Comment by Saimis777** [comment]
Thank you for that.

We will take a closer look with the team, and update you regarding this case.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello, 

Just a quick update, the fix will be implemented in the next release, please follow the news, and updates here - https://github.com/mollie/Prestashop/releases

As the latest version will be uploaded there really soon.

I will close this issue for now, let me know if you will need any other assistance!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello, hope you're having a nice day!

The official Mollie 4.2.0 was just released, the fix was implemented, you can download the latest version here - https://github.com/mollie/PrestaShop/releases/tag/4.2.0

Any feedback regarding the updated version is greatly appreciated!

--
Best regards,
Invertus Support team
