### ISSUE TITLE
Slow loading of AdminOrders page

### ISSUE THREAD

**Issue by 30knees** [mollie/PrestaShop#268]
### Expected behavior
AdminOrders should load normally quickly like other pages.

### Actual behavior
There's often a couple of seconds loading time, sometimes more, sometimes less.

### Steps to reproduce the behavior
Navigate to AdminOrders with Mollie installed and running and often (not always), it takes noticeably longer to load than other pages. I think this happens mostly when there are a couple of new orders to process. This issue has already been raised here https://github.com/mollie/PrestaShop/issues/203 for PS 1.7 but closed. I'm running PS 1.6.

### Environment
* thirtybees 1.1.x bleeding edge
* Mollie module version: 4.1.1
* PHP version 7.3.25, Memory limit 2048M, Max execution time 259200
* MySQL version 10.4.17-MariaDB-1:10.4.17

**Comment by Saimis777** [comment]
Hello, and thank you for the raised issue.

We will look in to it, and I will get back to you if any further information will be needed, or if I will have an update regarding this!

--
Best regards
Invertus Support team

**Comment by Saimis777** [comment]
Could you also clarify if you are certain that the slow loading is because of Mollie? Because I can see a bug fix was implemented in version 4.0.8. You can test it by disabling Mollie module and checking loading time in admin orders. Maybe upgrading to latest mollie would help as well.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by 30knees** [comment]
It was definitely Mollie because disabling Mollie made the page load quickly again. I think updating to the latest version fixed it! I'll post again if I notice anything. Thank you!

**Comment by Saimis777** [comment]
Thank you for that!

Be sure to let us know if you will notice any issues or bugs, we will be here to assist!

--
Best regards,
Invertus Support team

**Comment by 30knees** [comment]
Unfortunately, I was premature in my assessment. It's still there. It's the 'first time' in a session that it loads that it's slow. 
(Merry Christmas!)

**Comment by Saimis777** [comment]
Thank you for that, Merry Christmas to you as well!

To check further, we would need download your shop to our local testing environment, would you be able to provide us with your credentials for Front Office/Back Office and FTP to our email - support@invertus.eu? We could then check the issue further!

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by jacob-v-dam** [comment]
> Unfortunately, I was premature in my assessment. It's still there. It's the 'first time' in a session that it loads that it's slow.
> (Merry Christmas!)
> 
> p.s. Perhaps it's also related to the number of orders in the database? I have about 9000 orders in case it's helpful for reproducing the issue.

Is this happening when you load the dashboard page? We had the same problem and it had something to do with the dashboard modules of PrestaShop. We disabled them all to get a faster website.

This happend once a day indeed, when you revisited the backoffice it would be fast again since it was cached.

**Comment by 30knees** [comment]
@jacob-v-dam I'll test that and see whether it affects the orders page, too. Thanks!
@Saimis777 I'll report after testing Jacob's suggestion.

**Comment by Saimis777** [comment]
Sure thing, let us know how it will go!

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @30knees, how are you?

Have you managed to test the offered method? Does the issue persist? And do you need any further assistance?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by 30knees** [comment]
I'll be able to let you know tomorrow or the day after. Happy New Year!

**Comment by 30knees** [comment]
Yes, the issue is still there. I'll share login. Thanks!

**Comment by Saimis777** [comment]
Thank you for that,

And could you maybe give the exact steps for us to reproduce the issue? As from the description, we've understood that it happens only once a day, so we would need to be sure how to 100% correctly reproduce it, as at the moment it's a bit of a guessing game if the issue will occur or not, so to save time, it would be best to have a clear path of the issue reproduction.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by 30knees** [comment]
I'd suggest going to the order overview page on Tuesday and then filtering by the statuses: Shipped, Delivered, Shipped - Amazon, Paid, DHL - erfasst. I think one of them should trigger the delay. Thank you!

**Comment by Saimis777** [comment]
Thanks for your message, but are there any more specific steps to reproduce it? As this is more of a guessing thing at the moment, we would need to know exactly when, and in what circumstances the issue occurs in order to continue the investigation + would it be possible to receive the database with the orders via email as well with the reproduction steps? 

Thank you for your understanding, and looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by 30knees** [comment]
Unfortunately, no. Opening one of those statuses the first time typically triggers the delay. I understand if you're unable to investigate.

**Comment by 30knees** [comment]
Actually, I just realised that whenever I search for any customer name the response time is very slow. It's very fast when I disable the Mollie module. It's slow when I enable it. Can you test this in my backend?

**Comment by Saimis777** [comment]
Hello @30knees,

We could test the backend, however the database is still needed + and the whole shop zipped, and sent via email, as it would need to be tested locally. All of that would need to be sent to support@invertus.eu

Best regards,
Invertus Support team

**Comment by 30knees** [comment]
Could you please point me first to where the script is? Maybe the fix in #203 got dropped again in the newest version (as happened with #232) or it didn't get implemented to the PS 1.6 version?  Thanks

**Comment by Saimis777** [comment]
Hello @30knees No, it's not safe to delete that piece of code because it will not attach information of mollie payments in Admin Order page. The only option in this case is to download the shop locally, as mentioned in my last message, and test it to see if we can replicate the issue.

Will be looking forward to your reply!

Best regards,
Invertus Support team

**Comment by 30knees** [comment]
Thanks, I asked a developer who wrote this:

> The problem is that your database select bad plan to execute this query. The solution is to help the database -- create index that it can use to optimally retrieve data. Something like this:
> 
`> CREATE INDEX mp_order_reference ON tb_mollie_payments(order_reference);`
> With such index the query will run much faster, probably

What do you think? If you agree, where would I add that in the file https://github.com/mollie/PrestaShop/blob/master/mollie.php I'd give it a try and hopefully it'll save us all time compared to troubleshooting the issue.

**Comment by Saimis777** [comment]
Hello @30knees,
There is already an index on order_reference column:

$sql[] = 'CREATE TABLE IF NOT EXISTS `'._DB_PREFIX_.'mollie_payments` (
				`transaction_id`  VARCHAR(64)  NOT NULL PRIMARY KEY,
				`cart_id`         INT(64),
				`order_id`        INT(64),
				`order_reference` VARCHAR(191),
				`method`          VARCHAR(128) NOT NULL,
				`bank_status`     VARCHAR(64)  NOT NULL,
				`created_at`      DATETIME     NOT NULL,
				`updated_at`      DATETIME     DEFAULT NULL,
				 INDEX (cart_id, order_reference)
			) ENGINE='._MYSQL_ENGINE_.' DEFAULT CHARSET=utf8;';

In https://github.com/mollie/PrestaShop/blob/master/src/Install/DatabaseTableInstaller.php , so this index will not change anything.

Best regards,
Invertus Support team

**Comment by 30knees** [comment]
Thanks! The developer says:

`INDEX (cart_id, order_reference)`
That's composed index, based on two columns. This index would be used only if the join contained cart_id column as well.

But in this case, the join contains order_reference only, so db will happily ignore it.

It's possible that there is bug in php code -- maybe the join should contain cart_id.

Or if the php code is ok, then there should be standalone index with this order_reference column only.

**Comment by Saimis777** [comment]
@30knees Thank you for you notices!

I've passed this to our development team, we'll investigate it, and let you know!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @30knees 

Could you try changing mollie.php line: 1003: 
- $params['join'] .= ' LEFT JOIN `' . _DB_PREFIX_ . 'mollie_payments` mol ON mol.`order_reference` = a.`reference`';
+$params['join'] .= ' LEFT JOIN `' . _DB_PREFIX_ . 'mollie_payments` mol ON mol.`order_reference` = a.`reference` 
AND mol.`cart_id` = a.`id_cart`';

And tell us if that helped. As we don't have such big database to feel the change.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by 30knees** [comment]
Hi @Saimis777, thanks for the code. It gives me this error when I try to open the orders page:
```
×
Bad SQL query
Not unique table/alias: 'mol'
```

**Comment by Saimis777** [comment]
@30knees Thank you for the clarification, checking further!

Best regards,
Invertus Support team

**Comment by 30knees** [comment]
I think this may be related to https://github.com/mollie/PrestaShop/issues/277

**Comment by Saimis777** [comment]
@30knees Thank you, will get back to you once I have a solution to this.

Best regards,
Invertus Support team

**Comment by supersophisticated22** [comment]
The same happened after I updated to PS 1.7.7.1 the orders page load went from 2sec to ~1min.
Took me a while to find the issue but I found the solution.

in the file src/Grid/Query/Modifier/OrderGridQueryModifier.php i've added cart_id to the left join condition like:
``mol.`order_reference` = o.`reference` and  mol.`cart_id` = o.`id_cart``

and in mollie.php on line 1003
`
$params['join'] .= ' LEFT JOIN `' . _DB_PREFIX_ . 'mollie_payments` mol ON mol.`order_reference` = a.`reference` and  mol.`cart_id` = o.`id_cart`';
`

now the page load is back to 2sec

**Comment by 30knees** [comment]
Thanks! But that would still give 
```
×
Bad SQL query
Not unique table/alias: 'mol'
```
@Saimis777 Does your fix in #277 address this or are they separate?

**Comment by Saimis777** [comment]
Hello,

#277 issue is unrelated to this one, we're currently still investigating this, as we need a database with large amount of orders to exactly find what could cause the slow loading, I will keep you posted once we find a further resolution to this.

Best regards,
Invertus Support team

**Comment by 30knees** [comment]
I meant for the error below, as I would like to test your solution https://github.com/mollie/PrestaShop/issues/268#issuecomment-761003429
```
×
Bad SQL query
Not unique table/alias: 'mol'
```

**Comment by supersophisticated22** [comment]
@30knees my src/Grid/Query/Modifier/OrderGridQueryModifier.php now looks like:

![image](https://user-images.githubusercontent.com/63910432/105333798-6de84680-5bd6-11eb-91cf-bf4b39497b22.png)

**Comment by 30knees** [comment]
Thanks. I tried it but I think something is incorrect with the ' and ` signs in the mollie.php code because I get an error.

**Comment by Saimis777** [comment]
Hello @30knees,

We've managed to resolve this issue, we're currently testing everything, and the fix will be included in the 4.2.1 release, we're hoping to launch it this week, or the next one, I will definitely notify you once it's out! Thank you for your patience.

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello, the new version of Mollie - 4.2.1 was just released,

Please find the link for the download here - https://github.com/mollie/Prestashop/releases

And let us know with any feedback regarding the new version!

--
Best regards,
Invertus Support team

**Comment by 30knees** [comment]
Awesome! Just installed and it looks great! Thanks :)

**Comment by Saimis777** [comment]
Excellent news!

In case the issue will still persist, please let us know! Or any bugs in general, your feedback is greatly appreciated!

--
Best regards,
Invertus Support team
