### ISSUE TITLE
Order reference in back office is different then the one in the mail merchant gets

### ISSUE THREAD

**Issue by Nickovitshj** [mollie/PrestaShop#270]
### Expected behavior
Order reference in back office in the order overview should be the same as the one sent out in mails.

### Actual behavior
Order reference in back office is a different combination of characters from the one in the initial mail.

### Steps to reproduce the behavior
Place an order, proceed to payment.
Click on for example bancontact or any other payment option. In that payment option click cancel.
Merchant gets a mail with an order reference that is different from the one in prestashop back office

### Environment
* PrestaShop version: 1.7.6.5
* Mollie module version: 4.1.2
* PHP version: 7.2.31

**Comment by Saimis777** [comment]
Hello, and thank you for your message.

Would you firstly be able to download and install Mollie version 4.1.3? You can download the latest version here- https://github.com/mollie/Prestashop/releases

Just be sure to remove the old version before installing the new one.

And let me know how it will go!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @Nickovitshj , how are you?

Have you managed to update Mollie to the latest version? Did it sort out the issue?

Kindly looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Nickovitshj** [comment]
Hey @Saimis777 

Do you want me to uninstall the module through PS backoffice?
Or remove the module folder through ftp.

I want to make sure all our settings are saved.

**Comment by Nickovitshj** [comment]
Hey @Saimis777 

I have just updated plugin, the 4.1.3 version is the one being used right now.

However the issue still remains.
In the standard email sent out by prestashop the order reference is: TTPESEBOW
<img width="813" alt="Screenshot 2020-12-28 at 13 38 10" src="https://user-images.githubusercontent.com/64839875/103214865-f2b2ae00-4911-11eb-8f3f-589917b31500.png">



However in the Prestashop backend the order reference is: FSEVSXACA
Same for the credit card screen from mollie itself: 
![Screenshot 2020-12-28 at 13 37 18](https://user-images.githubusercontent.com/64839875/103214899-06f6ab00-4912-11eb-9ab5-c7e276c461cd.png)

**Comment by Saimis777** [comment]
@Nickovitshj Could you also clarify if you are using multistores?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Nickovitshj** [comment]
Hey @Saimis777 

Yes, I am using multistores!

**Comment by Nickovitshj** [comment]
Hey @Saimis777 

Are you guys currently looking into this issue?

Kind regards,
Nick

**Comment by Saimis777** [comment]
Hey,

Sorry for the late reply, yes, I've investigated this issue with the team, basically this issue is coming from the Prestashop multistores itself, since you're running multistores, the reference ID's will be different, the modules won't align the ID's to be the same, sorry for the inconveniences, and let me know if you will have any further questions!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @Nickovitshj we've had discussions, and it was decided to start working on full compatibility with multistores, as it will be a big update, it will be included not in the upcoming release as it will be out really soon, but the one after that, so it should be 4.3.0, the latest versions can always be found here - https://github.com/mollie/Prestashop/releases so be sure to follow for the latest updates there. I will close this issue for now, and if you will encounter any issues in the meantime, please let us know, we are here to help!

--
Best regards,
Invertus Support team

**Comment by Nickovitshj** [comment]
Hey @Saimis777 

That's good to hear. Within that update my error should be fixed then?
Is there an eta for this 4.3.0 update?

Thanks in advance,
Nick

**Comment by Saimis777** [comment]
Hello @Nickovitshj !

Correct, I've raised a ticket regarding your case specifically, so a fix will be included. At the moment we are working on small fixes that are being implemented in 4.2.1 release, we are hoping to test it tomorrow, and maybe release it next week, and after that, continue working on 4.3.0. I can't really give an ETA on it, as often times something unexpected happens, or bugs appear in testing environment, so it's difficult to guess the release date 😁 

I will definitely keep everyone posted regarding the 4.3.0 situation, and will inform you if I'll have the exact release date!

--
Best regards,
Invertus Support team

**Comment by Nickovitshj** [comment]
Hey @Saimis777 

Is there any rough estimate on the timeline of the 4.3 patch?

**Comment by Saimis777** [comment]
Hello @Nickovitshj Due to unforeseen errors, we are currently working on 4.2.2 release with bug fixes from 4.2.1 version, I will definitely keep you posted once I will have further news, sorry for the long wait.

--
Best regards,
Invertus Support team

**Comment by Nickovitshj** [comment]
Hey @Saimis777 

I have another related question.
A potential new feature that I would request if possible.

Would it be possible to let us choose our order reference prefix?
Such as for example: QT-10022021

Thanks in advance,
Nick

**Comment by Saimis777** [comment]
Hey @Nickovitshj 

Thank you for the idea! Maybe you could just raise a new issue regarding this, and call it as a "feature request"? I could then pass it to the team for further discussions if we could implement the changes! 

--
Best regards,
Invertus Support team

**Comment by Nickovitshj** [comment]
Hey @Saimis777 

Is it possible this issue has been fixed in the 4.2.3 release?

**Comment by Saimis777** [comment]
Hey @Nickovitshj ,

Sorry for the late reply, unfortunately no, currently we're working on releasing the 4.2.4 version, I will definitely inform you once this will be solved, and released!

--
Best regards,
Invertus Support team

**Comment by Nickovitshj** [comment]
Hey, I saw 4.2.4 has been release a few hours ago.
Any word on 4.3 and this partical issue?
