### ISSUE TITLE
Bug in PhoneNumberProvider->getFromAddress

### ISSUE THREAD

**Issue by mitchello** [mollie/PrestaShop#271]
### Expected behavior
Have a correct formated phone number (+[ISO_EXT][PHONE_NUMBER])

### Actual behavior
The phone numbe isn't correctly formated. For instance, we have the following phone number: 0697112404 (valid french mobile phone number). When we look at the code of PhoneNumberProvider, we can see that the phone number will become +697112404, which is not a correct phone number. The expected one should be either +33697112404 or 0697112404.

### Steps to reproduce the behavior
Execute the method getFromAddress with a address that contains the phone number.

### Remarks
Why should the module check the phone number as this information isn't used in the client dashboard of mollie?
And even if it's mandatory, it shouldn't be the responsability of the module to check the phone number.

### Edit
More information: 
The issue doesn't occur when it's a new client.
The error message I get is the following: "Cart Dump: [2021-01-03T16:08:34+0100] Error executing API call (422: Unprocessable Entity): The 'phone' field should contain a valid phone number, in E.164 format. Field: billingAddress.phone."

### Environment
* PrestaShop version: 1.7.6.9
* Mollie module version: 4.1.3
* PHP version: 7.2.x

**Comment by Saimis777** [comment]
Hello, and thank you for your message.

I will check this out with the team, and with Mollie, and will get back to you once I will be updated regarding this case.

Thank you for your patience!

--
Best regards,
Invertus Support team

**Comment by mitchello** [comment]
@Saimis777  thank you for checking.
If you need more detailed information, do not hesitate.
I can provide you the complete error message if needed.

Regards

**Comment by mitchello** [comment]
Hello @Saimis777, did you have any feedback from the team or Mollie?
Regards

**Comment by Saimis777** [comment]
Hello @mitchello thanks for checking in, we're currently discussing this topic, estimating the work that needs to be done, as there are other fixes and improvements we want to implement, we're trying to bundle everything up in one release, I will definitely keep you updated regarding this case!

--
Best regards,
Invertus Support team

**Comment by mitchello** [comment]
@Saimis777 thank you for your answer.
Regards

**Comment by Saimis777** [comment]
@mitchello The fix will be included in the 4.2.0 release, it's coming out very soon this month, it will be uploaded firstly here - https://github.com/mollie/Prestashop/releases so be sure to follow that repository, I will close this issue for now, and if you will encounter any other issues, please let us know, we are here to help!

--
Best regards,
Invertus Support team

**Comment by mitchello** [comment]
@Saimis777 thanks for the update, waiting for the release then.

Regards

**Comment by Saimis777** [comment]
Hello @mitchello , hope you're having a nice day!

The official Mollie 4.2.0 was just released, a new number validation was implemented, you can download the latest version here - https://github.com/mollie/PrestaShop/releases/tag/4.2.0

Any feedback regarding the updated version is greatly appreciated!

--
Best regards,
Invertus Support team
