### ISSUE TITLE
Send emails when payement failed

### ISSUE THREAD

**Issue by davidsmoker** [mollie/PrestaShop#278]
Why if a payment fails, why do we get a new order email?

VB customer places order, I receive an email (new order) and I surf to my back office and I see that the order has been cancelled. (problem with payment) but i have receive the mail

Same when product is almost out of stock, we get an email ( email product out of stock) even though the payment failed

### Environment
* PrestaShop version: 1.7.6.8 
* Mollie module version: 4.2.0

**Comment by Saimis777** [comment]
Hello @davidsmoker,

So order confirmation email is sent by Prestashop core when the order is being validated.  

To avoid sending order confirmation we implemented the setting in mollie in “ADVANCED SETTINGS” tabs there is a “Send order confirmation email” setting where the client can select when to send an order confirmation email. So he can set to send order confirmation emails when the order is Paid only.

![image](https://user-images.githubusercontent.com/75423142/104894837-d983a700-597d-11eb-842f-9708456381d3.png)

Best regards,
Invertus Support team
