### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by pic16f876** [mollie/PrestaShop#279]
### Expected behavior
Normal installation in Module Management

### Actual behavior
Unable to install in Module management. I get the error "Dit bestand lijkt niet op een zip-bestand van een module" (This file does not appear to be a module zipfile)

### Steps to reproduce the behavior
Normal installation in Module manager. I tried to install over 4.1.3 and also a clean install (uninstalling old module and delete the mollie folder with FTP). Same error. Reinstalled 4.1.3 without problems.

### Environment
* PrestaShop version: 1.7.6.5
* Mollie module version: 4.1.3
* PHP version: 7.1.33

**Comment by Saimis777** [comment]
Hello @pic16f876,

Have you tried installing the latest version of the module? You can download it here - https://github.com/mollie/Prestashop/releases

Be sure to remove the previous one completely from your Prestashop files, and try installing the new one.

Keep me updated of how it will go!

Best regards,
Invertus Support team

**Comment by pic16f876** [comment]
Just tried again, now it "magically" works. Not a clue why it would not work before as I had tried many times and many ways. Anyway, case closed.
