### ISSUE TITLE
Mollie does not show up page checkout

### ISSUE THREAD

**Issue by ninefingersodnd** [mollie/Prestashop#28]
I have a clean install of prestashop 1.6.1.9 and installed the mollie module,

This is not showing up on checkout, but it is configured good in modules/payment.
Everything is set right for showing up for the country, currency etc.

![settings](https://cloud.githubusercontent.com/assets/23555131/20431605/340ad146-ad9b-11e6-99d2-43bec737e303.jpg)

**Comment by ninefingersodnd** [comment]
I see it shown a class but with nothing in it, see pic.
![settings2](https://cloud.githubusercontent.com/assets/23555131/20431862/9ed07804-ad9c-11e6-86e4-7541a16b2089.jpg)

**Comment by ninefingersodnd** [comment]
The older 1.2.6 does not have this issue!

**Comment by ndijkstra** [comment]
Hi!
Can you send an email to techsupport@mollie.com with the login details of Prestashop?

**Comment by Stoffel79** [comment]
I have same problem with upgrdae from 1.6.1.4 to 1.6.1.12
whe you click at the payment icon, you go to the homepage instead of the mollie payment page ???

is here a solution ??

**Comment by Trendweb** [comment]
Hi @ninefingersodnd,

Have you managed to solve this problem?

**Comment by ninefingersodnd** [comment]
@Trendweb 

US:
We used an earlier version of this app. Butt it has been solved i think in the latest version.

NL:
We gebruikten een eerdere versio van de module, maar ik geloof dat het in de laatste versie was opgelost.

Greatz,
Ninefingers / ODND

**Comment by Trendweb** [comment]
@ninefingersodnd 

Thank you for informing us! Could you please mark this issue as closed?

Regards!
