### ISSUE TITLE
order confirmation mail does not contain rows of products

### ISSUE THREAD

**Issue by petrovv77** [mollie/PrestaShop#283]
### Expected behavior
product rows (order_conf_product_list.tpl) on order_conf mail is not shown to customers.

### Actual behavior
if I use another payment module such as 'ps_wirepayment', the mail will be displayed correctly to customers.
I've tried everything and also the entire build of the original tree prestashop of both theme and core, but nothing helps.
I'm not sure if version 4.1.3 had this too, but version 4.1.2 was fine.

![screenshot mail](https://user-images.githubusercontent.com/77987971/105751066-cce6ec00-5f45-11eb-9dc3-308a38365bca.png)
![different numbers](https://user-images.githubusercontent.com/77987971/105752012-11bf5280-5f47-11eb-8411-ba1a9cf6f5ef.png)
I see that 2 different order numbers appear in the log for the same order.

### Steps to reproduce the behavior
Options: 
Send order confirmation by e-mail: when the order has been paid.
Send a new order e-mail to the webshop: when the order has been paid. (tried on and off).
checked all mail templates, and if I test them in the built-in prestashop (/improve/design/mail_theme/preview/),
then they look good.

### Environment
* PrestaShop version: 1.7.7.1 
* Mollie module version: 4.2.0
* PHP version: 7.2.24-0ubuntu0.18.04.7

**Comment by Saimis777** [comment]
Hello @petrovv77, thank you for your message.

We will take a look at your issue, and get back to you as soon as possible!

--
Best regards,
Invertus Support team

**Comment by petrovv77** [comment]
I made a fresh installation of 1.7.7.1 in a test environment with minimal modifications.
Same problem, but with another payment module such as wirepayment it works fine.
The log also shows the same errors, in the fresh installation.

**Comment by Saimis777** [comment]
Hello, thank you for the clarification, as soon as I will receive an answer from the development team, I will get back to you!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

Just wanted to inform that we are still investigating the issue, I will inform you once I will receive any further information!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @petrovv77,

We've managed to resolve this issue, we will include the fix in the upcoming 4.2.2 update release!

If everything is going to be okay, tested, and no further bugs found, we are planning to release it next week, but of course, that's with an "if" everything is going to go smoothly, the new release will be uploaded here - https://github.com/mollie/Prestashop/releases

For now I will close this issue, be sure to follow the release page, and once it's released to provide any feedback regarding it, as it's greatly appreciated, and helps us to improve!

Have a nice day.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @petrovv77 , hope you're having a nice day so far!

We've just launched the 4.2.2 Mollie version, maybe you could try and install it, and provide any feedback regarding the new version?

You can download the latest version here - https://github.com/mollie/Prestashop/releases

As we tested, no order_conf issues in 4.2.2 branch were found.

Looking forward to your feedback!

--
Best regards,
Invertus Support team

**Comment by petrovv77** [comment]
I have updated the module to 4.2.2. The customer names are now displayed  #289 , but not yet the list of purchased products.

**Comment by Saimis777** [comment]
Thank you for reporting that @petrovv77 !

We are checking the issue further!

--
Best regards,
Invertus Support team

**Comment by petrovv77** [comment]
Great, it has been fixed with 4.2.3
