### ISSUE TITLE
Feature Request: add option to hide Resend Link column from orders page

### ISSUE THREAD

**Issue by Xesau** [mollie/PrestaShop#286]
Many other modules also add columns to the Orders page, and Mollie's column is very wide, because there is much text in the column header.

To make the orders screen less crammed, I think it would  be a good idea to make this column toggleable from the options page.

**Comment by Saimis777** [comment]
Hello @Xesau,

Thank you for your idea!

I will pass this to our team, to work on the improvement!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @Xesau ,

In the release 4.2.4 we made the image smaller as well as header. For now these are the changes that we made, and that were approved by Mollie, for the time being, everything will be left as is it, you can download the latest version of the module here - https://github.com/mollie/PrestaShop/releases

Thank you for your understanding, and let me know if you will have any further questions!

--
Best regards,
Invertus Support team
