### ISSUE TITLE
Unable to save Mollie module configuration

### ISSUE THREAD

**Issue by Joosiej89** [mollie/PrestaShop#287]
### Expected behavior
When click the save button in the Mollie module configuration the configuration should be saved.

### Actual behavior
When try to save the Mollie module configuration in the Prestashop administrator page an error is shown. Please see the print-screen of the error attached.

### Steps to reproduce the behavior
Open the Mollie module configuration and hit the save button.

### Environment
* PrestaShop version: 1.6.1.9 
* Mollie module version: 4.2.1
* PHP version: 7.0
<img width="1050" alt="Error-mollie-module" src="https://user-images.githubusercontent.com/78217757/106286331-d1f9b300-6245-11eb-8a55-6e72d7597d36.png">

**Comment by Saimis777** [comment]
Hello, and thank you for your message.

Would you be able to send us your front/back office + FTP credentials to support@invertus.eu? As we haven't encountered such issue with the given steps of reproduction. 

And before that, maybe you could reset the module and try again?

Let me know if it will help!

--
Best regards,
Invertus Support team

**Comment by Joosiej89** [comment]
Thank for your very fast reply! I have reset the module and everything seems to work fine again! I have not thought of that option.
Thanks for your tip.

**Comment by Saimis777** [comment]
No problem, glad that helped!

Let me know if you will need any other assistance!

--
Best regards,
Invertus Support team
