### ISSUE TITLE
Test api doesn't work under PS 1.7.7.0

### ISSUE THREAD

**Issue by musicpanda** [mollie/PrestaShop#290]
Klikken op de "Test API key" button de backoffice resulteert in een javascript error "Unexpected token < at position 0". Analyse van de geretourneerde Ajax string levert op dat deze het volgende bevatte:
_```
<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
							Pagina niet gevonden
					</div>
```_
 

### Environment
* PrestaShop version: 1.7.7.0 
* Mollie module version: 4.2.1 
* PHP version: 7.3 

![mollie2](https://user-images.githubusercontent.com/13930107/106767060-c7bb2880-663a-11eb-8a8b-cd7e2da5e1f0.jpg)
![mollie1](https://user-images.githubusercontent.com/13930107/106767062-c8ec5580-663a-11eb-8ff8-3c8602599545.jpg)
![mollie3](https://user-images.githubusercontent.com/13930107/106767177-e3263380-663a-11eb-9977-a292609766a2.jpg)

**Comment by Saimis777** [comment]
Hello @musicpanda,

Thank you for your message, I will pass this to our team for further investigation, and will keep you updated regarding this matter!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

Just wanted to inform that we are still working on this case, and I will update you once I receive news from the development team.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @musicpanda ,

Maybe you would be able to provide your back office + FTP credentials to - support@invertus.eu for further investigation? As we're trying but can't replicate the issue from our end.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by musicpanda** [comment]
I went back to module version 4.1.3 and that solved it for me. I saw the bug on two platforms.

**Comment by Saimis777** [comment]
Thank you for the clarification @musicpanda,

Have you tried upgrading the version to 4.2.2? We've just released it yesterday, you can download it here - https://github.com/mollie/Prestashop/releases

Also, should we continue the investigation? As we would need to see inside the shop for the further, it would be greatly appreciated, as it helps us improve the module!

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by musicpanda** [comment]
I can't justify it to my customer to give you access at this stage. So no, if you can't find it then the issue stops here.

**Comment by Saimis777** [comment]
@musicpanda thank you for your message,

We would love to solve this issue, as the quality of the module is our top priority, and I understand now that you can't give out the credentials, in that case maybe you can clarify which platforms you've had in mind? You mean different versions of the module? Or which exactly platforms you've had in mind? Maybe there's more information that you could provide regarding this case, that could help us replicate this issue? Or maybe you have a test environment that can be used to debug this?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by musicpanda** [comment]
Sorry, I can't help you any further.

With different platform I meant that I installed the module both on the server and on a localhost test copy. Both times with exactly the same result

**Comment by Saimis777** [comment]
@musicpanda Understood.

Could you also clarify if resetting the module didn't help neither on the server nor localhost?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
@musicpanda,

And can you clarify exactly if 4.2.2 version resolved the issue? Or you haven't tried it yet?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by musicpanda** [comment]
I didn't try resetting. I never thought about it.

I used the latest version at that moment. As I said before I use now an older version and I certainly won't try another 4.2 version.

**Comment by Saimis777** [comment]
@musicpanda ,

Let me know once you've tried resetting it if that helped or not! I completely understand that you don't want the 4.2 version, but I would highly suggest at least giving it a try for the 4.2.2 version, in case you will change your mind, you can download it here - https://github.com/mollie/Prestashop/releases, and if you'll want, you can always roll back to an older version!

Let me know how it will go, we are here to help!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @musicpanda,

Have you managed to try resetting the module? Did it resolve the issue?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @musicpanda hope you're having a good day so far.

Just wanted to double check if you've had the chance to reset the module, and if so, did it help?

Your feedback is greatly appreciated!

P.S. Let us know if we should continue the investigation, as in other case we would need to close this issue due to inactivity.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

Due to inactivity, I will close this issue for now, please let me know if you would like to continue the investigation!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @musicpanda ,

The latest version of Mollie has just been released with an improved error handling when API key is expired.

You can find the latest version here - https://github.com/mollie/Prestashop/releases

Let us know once you've installed and tested it, as your feedback is greatly appreciated!

--
Best regards,
Invertus Support team
