### ISSUE TITLE
Forgot "wenn" word 

### ISSUE THREAD

**Issue by Daaaaad** [mollie/PrestaShop#291]
### Expected behavior

I juste tested the 4.2.1 release and I noticed the german word "wenn" that is displayed everywhere... I think it's a debug information that needs to be removed 🤔

### Steps to reproduce the behavior

1. Go to BO > Modules
2. Find the mollie module and click on "configure"
3. Select the second tab "advanced parameters"
4. The "wenn" word is present in front of some parameters

<img width="1110" alt="Capture d’écran 2021-02-08 à 12 25 07" src="https://user-images.githubusercontent.com/167037/107213455-baba8280-6a08-11eb-9eac-9376fd287893.png">

### Environment
* Mollie module version: 4.2.1

**Comment by Saimis777** [comment]
Hey @Daaaaad!

Thank you for your message, we will investigate this further, and let you know regarding the process of this issue!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

Just wanted to inform you that we are still working on this case, and figuring out how this has happened, I will keep you posted with the updates.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey,

Just here informing that we are working on this case, and will keep you updated once I'll receive further information!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @Daaaaad ,

Currently we've implemented a fix to this issue, and will be testing it shortly, so I will keep you updated with the process, and when the fix will be confirmed and released!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @Daaaaad ,

The issue fix will be included in the 4.2.3 release, I will let you know once I will have further information on when it will be released! 

Maybe you have any other questions in the meantime?

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @Daaaaad !

Mollie 4.2.3 version was just released, with the updated translations please find the latest version here - https://github.com/mollie/Prestashop/releases

Let us know once you've downloaded and tested it!

Your feedback is greatly appreciated.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

As this issue was resolved, the translations were updated, I am going to close it for now, please let me know if you will have any further questions or will need assistance!

--
Best regards,
Invertus Support team
