### ISSUE TITLE
The "code" field is missing

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop#292]
### Expected behavior
Wanneer je de status op verzonden wilt zetten van een bestelling die betaald is met klarna (afterpay) kon je in eerdere versies dat doen zonder tracking code te invullen.

### Actual behavior
Een error 500 wanneer je de status wilt veranderen naar "verzonden" zonder een tracking code te hebben ingevuld.
![klarna](https://user-images.githubusercontent.com/49270150/107504119-22a0d280-6b9b-11eb-859e-edd9e5fe6952.png)

### Steps to reproduce the behavior
Klarna betaling starten en plaatsen, de bestelling op status "verzonden" te zetten zonder een tracking code te hebben ingevuld.

### Environment
* PrestaShop version: 1.7.6.9
* Mollie module version: 4.2.1
* PHP version: 7.2.34

**Comment by Saimis777** [comment]
Hello @Maikel726,

Thank you for your message.

We've already implemented a fix regarding this issue, we're currently testing it, I will let you know once it's going to get released if that's okay with you!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

This issue was resolved in the 4.2.2 branch, maybe you could install the latest version of Mollie, and give us any feedback regarding it?

You can download the latest version here - https://github.com/mollie/Prestashop/releases

Let me know how it will go!

--
Best regards,
Invertus Support team

**Comment by Maikel726** [comment]
Hi,

The issue has been resolved for me with version 4.2.2

**Comment by Saimis777** [comment]
Hello!

Glad to hear that! Please let us know any further feedback regarding the module!

I will close this issue for now, let me know if you will need any further help!

--
Best regards,
Invertus Support team
