### ISSUE TITLE
Feature request: order reference prefix

### ISSUE THREAD

**Issue by Nickovitshj** [mollie/PrestaShop#293]
### Expected behavior
User can choose his own order reference prefix
For example: "QUOTEWEBSHOP-"HALEK72kL
User would be able to type out the order prefix he/she wishes in an input field and is able to save it.

**Comment by Saimis777** [comment]
@Nickovitshj thank you for your message, and the suggestion!

I'm passing this to our team, and we will check further if this new feature is possible to implement!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

As I've received clarifications, this feature request was denied. I am closing this issue for now, please let us know if you have any further questions!

--
Best regards,
Invertus Support team

**Comment by Nickovitshj** [comment]
Hey @Saimis777 , 

Is it possible this has been fixed in the latest release?

**Comment by Saimis777** [comment]
Hello @Nickovitshj!

Sorry, but this feature request was not approved by Mollie. 

Sorry for the inconveniences.

--
Best regards,
Invertus Support team
