### ISSUE TITLE
Paid state assigned twice?

### ISSUE THREAD

**Issue by jacob-v-dam** [mollie/PrestaShop#297]
### Expected behavior
Once a payment is set as payed the same state should not occur again.

### Actual behavior
The order state change to payed twice:
![image](https://user-images.githubusercontent.com/310526/108555686-17b21480-72f6-11eb-81d3-1ed81e535e18.png)

### Steps to reproduce the behavior
Change the state to a not payed state. This isn't always happening. As you can see the order is registered once as payed:
![image](https://user-images.githubusercontent.com/310526/108555809-47f9b300-72f6-11eb-8eba-64690249d201.png)

### Environment
* PrestaShop version: 1.7.7.1
* Mollie module version: 4.2.2
* PHP version: 7.4

**Comment by Saimis777** [comment]
Hello @jacob-v-dam,

Thank you for the message, I will pass this to our team for further investigation, and will get back to you as soon as possible!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @jacob-v-dam ,

Could you also clarify if this happens only when the status is changed manually?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @jacob-v-dam ,

Would you be able to clarify if the issue persists only when changing the status manually?

Let me know!

--
Best regards,
Invertus Support team

**Comment by jacob-v-dam** [comment]
At the moment this only happens on the Klarna orders. Customer now receives two e-mails.

**Comment by Saimis777** [comment]
Thank you for your message @jacob-v-dam ,

Could you also clarify what are those 2 emails that the customer received? And could you give us more information on this issue please?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @jacob-v-dam ,

Would you be able to clarify the 2 emails that the customer has received? And provide us with further information regarding this case?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @jacob-v-dam !

Mollie 4.2.3 version was just released, please find the latest version here - https://github.com/mollie/Prestashop/releases

Let us know once you've downloaded and tested it!

Your feedback is greatly appreciated.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @jacob-v-dam ,

Did you have the time to install the latest version, and check if everything is okay, and if our further help is needed?

Let us know!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
@jacob-v-dam ,

As this issue was resolved and the fix was merged in to the 4.2.3 release which you can download and install here - https://github.com/mollie/Prestashop/releases

We are going to close this issue for now. Let us know if you notice any misbehaviour or if you  need assistance with it and we will reopen the issue!

Have a nice day,

--
Best regards,
Invertus Support team
