### ISSUE TITLE
Feature request: Exclude specifc payment methods for a specific shipping method

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop#298]
Hi,
I have a request for an feature that really useful for in the future. In the settings of Prestashop you can exclude certain payment methods from certain shipping methods but because Mollie is 1 module instead of separate modules for each payment method you can't exclude a specific shipping method for a certain payment method. Can this be an feature in the future that i can change this in the Mollie module.

![afbeelding](https://user-images.githubusercontent.com/49270150/108691964-5b766b00-74fc-11eb-9d8c-8fed2e92453c.png)

**Comment by Saimis777** [comment]
Hey @Maikel726 ,

Thank you for the suggestion, and contribution on improving the module! I will definitely pass this feature request to our and Mollie team for further investigation if it's possible to implement it, and if it will be confirmed, and added to the next or some other release, I will notify you!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @Maikel726,

I've clarified this with Mollie, and at the moment this feature request will be denied, however thank you very much for your contribution, and if you will have any other feature ideas, please be sure to post them in GitHub, and I will definitely make sure to clarify if the feature could be added!

Have a nice day!

--
Best regards,
Invertus Support team
