### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by dariusakafest** [mollie/PrestaShop#299]
### Expected behavior
https://github.com/mollie/PrestaShop/blob/master/src/Service/CartLinesService.php

Do you understand here what kind of nonsense you've done? In my list of goods, the wrong lines are sent to the mollie that the customer ordered and the wrong amounts, after which I cannot make a normal return?

For example, a customer bought five items at 21.491
Why does the system create 4 products at 21.49
And 5 for 21.50 is not wrong!
Moreover, these are already two different products and then how to track all this?

### Environment
* PrestaShop version: 1.7.6.4
* Mollie module version: 4.0.2
* PHP version: 7.2

**Comment by Saimis777** [comment]
Hello @dariusakafest ,

Thank you for your message,

We are aware of this situation, and I understand your frustration, we're currently discussing this issue with Mollie, and evaluating the best solution that we can implement for this case, sorry for the inconveniences, I will get back to you as soon as I'll know the further details regarding this.

--
Best regards,
Invertus Support team

**Comment by dariusakafest** [comment]
I solved while this problem so:  i calculate  calc_total_price =  unit_price * qty, after calculate diff = total_price - calc_total_price, 
and diff plus to Payment Fee, usally this value = 0.01

**Comment by Saimis777** [comment]
@dariusakafest ,

Thank you for the solution, our team is informed, we are working on a resolution regarding this case, and I will definitely keep you updated regarding this matter!

Your patience is greatly appreciated!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

Just wanted to inform that we are still working on the case, and are testing it internally, will clarify regarding this matter on Monday.

--
Best regards,
Invertus Support team

**Comment by dariusakafest** [comment]
@Saimis777  ok)

**Comment by Saimis777** [comment]
Hello @dariusakafest ,

Our team is currently testing the fix, and confirmed that we will include it in the 4.2.3 release, which is getting released really soon! I will notify you once it's out, and ready to download!

Your patience is greatly appreciated.

Have a nice day!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @dariusakafest !

Mollie 4.2.3 version was just released, please find the latest version here - https://github.com/mollie/Prestashop/releases

Let us know once you've downloaded and tested it!

Your feedback is greatly appreciated.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @dariusakafest ,

Did you have the time to check the 4.2.3. version and if everything is okay?

Let us know!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
@dariusakafest  ,

As this issue was resolved and the fix was merged in to the 4.2.3 release which you can download and install here - https://github.com/mollie/Prestashop/releases

We are going to close this issue for now. Let us know if you notice any misbehaviour or if you need assistance with it and we will reopen the issue!

Have a nice day,

--
Best regards,
Invertus Support team
