### ISSUE TITLE
After a successful payment order-history is shown instead of the order-confirmation

### ISSUE THREAD

**Issue by paetor** [mollie/PrestaShop#3]
In correct operation Prestashop will – with or without the Mollie plugin – display an order confirmation page to customers returning to the shop from making a payment. Some customers will notice a change here when they use a version of Prestashop ≤ **1.6.0.7** and the Mollie plugin ≥ **1.0.3**. The anomaly is that under these circumstances the customers are shown their order-history instead. Not a giant problem, but both unexpected and undesirable.

**Comment by codepoppo** [comment]
Hi- I have this issue still where all orders are redirected from Paypal to order history. I desperately need these to fire scripts, have no clue why. My Prestashop is 1.6.1 and website is www.bedandwood.com.  I have attached the first data.php file. Order confirm contr.php has ->name as one would expect.
