### ISSUE TITLE
Make module check for https instead of http?

### ISSUE THREAD

**Issue by janoroh** [mollie/Prestashop#30]
I have the same problem as the two users in the closed "Status not sent to Prestashop" issue at https://github.com/mollie/Prestashop/issues/9 (payments work, but no order is created and no status sent), but my site is not in maintenance mode. I guess in my case it's because the site runs fully on SSL (not just checkout and user account), so the URLs that the module checks are not correct. In the Mollie dashboard, I see these lines for a test payment I made:
redirection URL: http://www.myurl.de/module/mollie/return?cart_id=5666&utm_nooverride=1
webhook URL: http://www.myurl.de/module/mollie/webhook

I guess it's correct that the "module" folder doesn't actually exist (only "modules") and neither the "webhook" subfolder since another poster in that old thread had that same issue but it worked nevertheless when he turned off maintenance mode.

But is there a way to add some code to the module so that it actually checks for https://www.myurl instead of http://? This would be very helpful and probably solve the problem (at least I can't think of anything else that might be wrong). Thanks!

**Comment by Trendweb** [comment]
Hi @janoroh ,

Do you still need support on this problem / need help in order to get the Mollie Module working properly?

Regards

**Comment by janoroh** [comment]
Yes, please. I've still had no way of getting the module to work (and still believe that it's due to my using of SSL on my server). Thanks!

**Comment by Trendweb** [comment]
Hi @janoroh ,

Could you please provide us with the following information:

- server information (especially your PHP version) and your prestashop version (Choose: advanced settings >> information);
- the version number of the Mollie Module you are currently using (Choose: Modules >> Modules & Services);
- if you choose "Settings >> General", do you have "activate SSL" set to "yes" and do you have "activate SLL on all pages" set to "yes";
- are you currently using a so called "clean url's" module which removes all id's from the url? These are known to conflict / cause problems with other modules. If so, please disable the clean url's module and make a test payment;
- have you tried debugging by disabling all non-native Prestashop Modules while keeping the Mollie Module enabled, and then do a test payment;
- could you please post the link to your test-store?

Regards

**Comment by Trendweb** [comment]
Hi @janoroh ,

Have you had a chance to try our suggestions? Please let us know so we can solve your problem as soon as possible.

Regards

**Comment by Trendweb** [comment]
Hi @janoroh  ,

We are closing this issue. You can still place comments to let us know if you still need support. We will close comments after 1 week.

Regards
