### ISSUE TITLE
Wrong order reference in emails sent after an order is completed

### ISSUE THREAD

**Issue by dcdepartamentocreativo** [mollie/PrestaShop#301]
### Expected behavior
The emails sent both to the customer or the owner of the website show in the subject and the body of the message the order reference

### Actual behavior
In some orders paid with iDeal, the reference showing in the emails is wrong, the module does not show the actual reference of the order, but another one

* PrestaShop version: 1.7.4.2
* Mollie module version: 4.2.2
* PHP version: 7.3.27

**Comment by Saimis777** [comment]
Hello @dcdepartamentocreativo ,

Thank you for your message.

Could you give us more details about the issue, and cases when this happens, when it does not happen, and how exactly we can reproduce it?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by dcdepartamentocreativo** [comment]
Hello Saimis

I've been researching through prestashop and I've seen that this is happening in all the orders placed with ideal

Whenever a customer places an order with iDEAL as payment method, the order is stored in prestashop with a reference, but the emails sent both to the customer and the owner of the web the reference included in the e-mail is different. With other payment methods we are not having such issue, both the orders tab in prestashop and the e-mail are showing the same reference.

**Comment by petrovv77** [comment]
Hello @dcdepartamentocreativo 
This problem was there a few months ago, but we have been doing well for a long time (also with Ideal). I think you should clean up the database tables of this module. If you use multistores it could possibly be because of that, I don't use that myself.

**Comment by Saimis777** [comment]
@petrovv77 Thanks for the additional tips, indeed regarding the clean up of database, and running multistores could be the case.

@dcdepartamentocreativo are you running multistores?

And maybe you could provide us with your BO/FTP credentials to support@invertus.eu for further investigation of the issue?

Let us know!

--
Best regards,
Invertus Support team

**Comment by dcdepartamentocreativo** [comment]
Actually no, we are not running any multistore, so that wouldn’t be the case

These are the credentials:

https://toral-shoes.com/stores/admin732djp8bk/

u: web@departamentocreativo.com
p: adm_T0R4L19


And for the FTP:

toral-shoes.com

U: clidptocreativo
P: 0Br!N0q97QVb

pablo alonso DC

✆:  965  305 971 / 966 342 399
@:  web@departamentocreativo.com ·  www.DepartamentoCreativo.com

DC DEPARTAMENTO CREATIVO
#AÑADIENDOVALOR #VUELTAATOPE---------------------------------------------------------------
Le informamos que sus datos personales están incluidos en un tratamiento, cuyo responsable es ESTRATEGIAS DEL DEPARTAMENTO CREATIVO, S.L.. Creado con la finalidad de gestionar comercial y administrativamente la relación que, en su caso, nos une y de informarle sobre productos, servicios o eventos de nuestra empresa que pudieran ser de su interés por medios tradicionales o electrónicos. Cuya legitimidad recae en la ejecución de un contrato o en su consentimiento previo. Cuyos destinatarios serán únicamente, otras empresas del mismo grupo, en su caso, u otros terceros sobre los que recaiga algún tipo de obligación legal para su cesión. Los datos se conservarán durante el periodo durante el cual exista una relación contractual y/o comercial establecida o mientras no nos lo solicite. Sobre el que podrá ejercitar los derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad de sus datos, remitiendo una solicitud por escrito a la dirección anteriormente indicada, acompañando un documento para su identificación. Si tiene cualquier tipo de consulta, comentario o inquietud sobre cómo tratamos la información de carácter personal puede consultar nuestra Política de Privacidad en www.departamentocreativo.com. Puede también ponerse en contacto con nosotros en el teléfono 965305971 y/o en el correo electrónico info@departamentocreativo.com. Si no desea recibir información de carácter comercial de nuestra empresa rogamos nos lo comunique por ese mismo canal.

**Comment by Saimis777** [comment]
@dcdepartamentocreativo 

I have received the credentials via email, thank you.

I am passing them to our development team, I've noticed that a comment was left once you've sent an email reply, therefore I've deleted it on Github. 

I will notify you once I will receive further information regarding this case.

--
Best regards,
Invertus Support team

**Comment by dcdepartamentocreativo** [comment]
Thanks a lot!

pablo alonso DC

✆:  965  305 971 / 966 342 399
@:  web@departamentocreativo.com ·  www.DepartamentoCreativo.com

DC DEPARTAMENTO CREATIVO
#AÑADIENDOVALOR #VUELTAATOPE---------------------------------------------------------------
Le informamos que sus datos personales están incluidos en un tratamiento, cuyo responsable es ESTRATEGIAS DEL DEPARTAMENTO CREATIVO, S.L.. Creado con la finalidad de gestionar comercial y administrativamente la relación que, en su caso, nos une y de informarle sobre productos, servicios o eventos de nuestra empresa que pudieran ser de su interés por medios tradicionales o electrónicos. Cuya legitimidad recae en la ejecución de un contrato o en su consentimiento previo. Cuyos destinatarios serán únicamente, otras empresas del mismo grupo, en su caso, u otros terceros sobre los que recaiga algún tipo de obligación legal para su cesión. Los datos se conservarán durante el periodo durante el cual exista una relación contractual y/o comercial establecida o mientras no nos lo solicite. Sobre el que podrá ejercitar los derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad de sus datos, remitiendo una solicitud por escrito a la dirección anteriormente indicada, acompañando un documento para su identificación. Si tiene cualquier tipo de consulta, comentario o inquietud sobre cómo tratamos la información de carácter personal puede consultar nuestra Política de Privacidad en www.departamentocreativo.com. Puede también ponerse en contacto con nosotros en el teléfono 965305971 y/o en el correo electrónico info@departamentocreativo.com. Si no desea recibir información de carácter comercial de nuestra empresa rogamos nos lo comunique por ese mismo canal.

**Comment by Saimis777** [comment]
Hello,

Just wanted to inform that we are still working on the case, and are testing it internally, will clarify regarding this matter on Monday.

--
Best regards,
Simonas

**Comment by Saimis777** [comment]
Hello,

Just wanted to inform that we are still testing the fix, but it will be included in the 4.2.3 release, which is getting released soon, and I will notify you once it's released!

Thank you for your patience!

--
Best regards,
Invertus Support team

**Comment by dcdepartamentocreativo** [comment]
Hello

I’ve updated the mollie module on our prestashop

Will get back with any feedback I have

Thanks for your help

pablo alonso DC

✆:  965  305 971 / 966 342 399
@:  web@departamentocreativo.com ·  www.DepartamentoCreativo.com

DC DEPARTAMENTO CREATIVO
#AÑADIENDOVALOR #VUELTAATOPE---------------------------------------------------------------
Le informamos que sus datos personales están incluidos en un tratamiento, cuyo responsable es ESTRATEGIAS DEL DEPARTAMENTO CREATIVO, S.L.. Creado con la finalidad de gestionar comercial y administrativamente la relación que, en su caso, nos une y de informarle sobre productos, servicios o eventos de nuestra empresa que pudieran ser de su interés por medios tradicionales o electrónicos. Cuya legitimidad recae en la ejecución de un contrato o en su consentimiento previo. Cuyos destinatarios serán únicamente, otras empresas del mismo grupo, en su caso, u otros terceros sobre los que recaiga algún tipo de obligación legal para su cesión. Los datos se conservarán durante el periodo durante el cual exista una relación contractual y/o comercial establecida o mientras no nos lo solicite. Sobre el que podrá ejercitar los derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad de sus datos, remitiendo una solicitud por escrito a la dirección anteriormente indicada, acompañando un documento para su identificación. Si tiene cualquier tipo de consulta, comentario o inquietud sobre cómo tratamos la información de carácter personal puede consultar nuestra Política de Privacidad en www.departamentocreativo.com. Puede también ponerse en contacto con nosotros en el teléfono 965305971 y/o en el correo electrónico info@departamentocreativo.com. Si no desea recibir información de carácter comercial de nuestra empresa rogamos nos lo comunique por ese mismo canal.

**Comment by dcdepartamentocreativo** [comment]
Hello

Since the update of the module yesterday, I don’t have access to the back office of the website

I don’t know if it has something to do with the module, but at least it’s suspicious

Could you confirm me if that’s the case?

It’s really urgent please

pablo alonso DC

✆:  965  305 971 / 966 342 399
@:  web@departamentocreativo.com ·  www.DepartamentoCreativo.com

DC DEPARTAMENTO CREATIVO
#AÑADIENDOVALOR #VUELTAATOPE---------------------------------------------------------------
Le informamos que sus datos personales están incluidos en un tratamiento, cuyo responsable es ESTRATEGIAS DEL DEPARTAMENTO CREATIVO, S.L.. Creado con la finalidad de gestionar comercial y administrativamente la relación que, en su caso, nos une y de informarle sobre productos, servicios o eventos de nuestra empresa que pudieran ser de su interés por medios tradicionales o electrónicos. Cuya legitimidad recae en la ejecución de un contrato o en su consentimiento previo. Cuyos destinatarios serán únicamente, otras empresas del mismo grupo, en su caso, u otros terceros sobre los que recaiga algún tipo de obligación legal para su cesión. Los datos se conservarán durante el periodo durante el cual exista una relación contractual y/o comercial establecida o mientras no nos lo solicite. Sobre el que podrá ejercitar los derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad de sus datos, remitiendo una solicitud por escrito a la dirección anteriormente indicada, acompañando un documento para su identificación. Si tiene cualquier tipo de consulta, comentario o inquietud sobre cómo tratamos la información de carácter personal puede consultar nuestra Política de Privacidad en www.departamentocreativo.com. Puede también ponerse en contacto con nosotros en el teléfono 965305971 y/o en el correo electrónico info@departamentocreativo.com. Si no desea recibir información de carácter comercial de nuestra empresa rogamos nos lo comunique por ese mismo canal.

**Comment by Saimis777** [comment]
Hello @dcdepartamentocreativo ,

Could you clarify if there's an error when trying to access it or what does it show when trying to access the back office? 

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by dcdepartamentocreativo** [comment]
Actually I can’t enter the website either

The message is ERR_CONNECTION_REFUSED

pablo alonso DC

✆:  965  305 971 / 966 342 399
@:  web@departamentocreativo.com ·  www.DepartamentoCreativo.com

DC DEPARTAMENTO CREATIVO
#AÑADIENDOVALOR #VUELTAATOPE---------------------------------------------------------------
Le informamos que sus datos personales están incluidos en un tratamiento, cuyo responsable es ESTRATEGIAS DEL DEPARTAMENTO CREATIVO, S.L.. Creado con la finalidad de gestionar comercial y administrativamente la relación que, en su caso, nos une y de informarle sobre productos, servicios o eventos de nuestra empresa que pudieran ser de su interés por medios tradicionales o electrónicos. Cuya legitimidad recae en la ejecución de un contrato o en su consentimiento previo. Cuyos destinatarios serán únicamente, otras empresas del mismo grupo, en su caso, u otros terceros sobre los que recaiga algún tipo de obligación legal para su cesión. Los datos se conservarán durante el periodo durante el cual exista una relación contractual y/o comercial establecida o mientras no nos lo solicite. Sobre el que podrá ejercitar los derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad de sus datos, remitiendo una solicitud por escrito a la dirección anteriormente indicada, acompañando un documento para su identificación. Si tiene cualquier tipo de consulta, comentario o inquietud sobre cómo tratamos la información de carácter personal puede consultar nuestra Política de Privacidad en www.departamentocreativo.com. Puede también ponerse en contacto con nosotros en el teléfono 965305971 y/o en el correo electrónico info@departamentocreativo.com. Si no desea recibir información de carácter comercial de nuestra empresa rogamos nos lo comunique por ese mismo canal.

**Comment by Saimis777** [comment]
The shop seems to be active from my end:
![image](https://user-images.githubusercontent.com/75423142/110617862-d4352280-819e-11eb-8082-cd6891b13ddc.png)

Could you try clearing your browsers cache, or try to enter it via a different device?

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
I've also tested the back office log in with the same credentials as
provided, seems to be active as well:
[image: image.png]

I would suggest clearing your cache and try to enter it via a different
device.

Also, be sure to change your back office credentials ASAP.

--
Best regards,
Invertus Support team

**Comment by dcdepartamentocreativo** [comment]
I’ve done all that with no success

On my mobile phone I can access (only sometimes) when connected via 4G, but not via WIFI.

I don’t know if that’s asking too much, but could you please roll back to the previous version of the mollie plugin so I can make further investigations?

Anyway, thanks for your help

pablo alonso DC

✆:  965  305 971 / 966 342 399
@:  web@departamentocreativo.com ·  www.DepartamentoCreativo.com

DC DEPARTAMENTO CREATIVO
#AÑADIENDOVALOR #VUELTAATOPE---------------------------------------------------------------
Le informamos que sus datos personales están incluidos en un tratamiento, cuyo responsable es ESTRATEGIAS DEL DEPARTAMENTO CREATIVO, S.L.. Creado con la finalidad de gestionar comercial y administrativamente la relación que, en su caso, nos une y de informarle sobre productos, servicios o eventos de nuestra empresa que pudieran ser de su interés por medios tradicionales o electrónicos. Cuya legitimidad recae en la ejecución de un contrato o en su consentimiento previo. Cuyos destinatarios serán únicamente, otras empresas del mismo grupo, en su caso, u otros terceros sobre los que recaiga algún tipo de obligación legal para su cesión. Los datos se conservarán durante el periodo durante el cual exista una relación contractual y/o comercial establecida o mientras no nos lo solicite. Sobre el que podrá ejercitar los derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad de sus datos, remitiendo una solicitud por escrito a la dirección anteriormente indicada, acompañando un documento para su identificación. Si tiene cualquier tipo de consulta, comentario o inquietud sobre cómo tratamos la información de carácter personal puede consultar nuestra Política de Privacidad en www.departamentocreativo.com. Puede también ponerse en contacto con nosotros en el teléfono 965305971 y/o en el correo electrónico info@departamentocreativo.com. Si no desea recibir información de carácter comercial de nuestra empresa rogamos nos lo comunique por ese mismo canal.

**Comment by dcdepartamentocreativo** [comment]
It seems there was a problem with the php configuration, and now I can access

Thanks for your help

pablo alonso DC

✆:  965  305 971 / 966 342 399
@:  web@departamentocreativo.com ·  www.DepartamentoCreativo.com

DC DEPARTAMENTO CREATIVO
#AÑADIENDOVALOR #VUELTAATOPE---------------------------------------------------------------
Le informamos que sus datos personales están incluidos en un tratamiento, cuyo responsable es ESTRATEGIAS DEL DEPARTAMENTO CREATIVO, S.L.. Creado con la finalidad de gestionar comercial y administrativamente la relación que, en su caso, nos une y de informarle sobre productos, servicios o eventos de nuestra empresa que pudieran ser de su interés por medios tradicionales o electrónicos. Cuya legitimidad recae en la ejecución de un contrato o en su consentimiento previo. Cuyos destinatarios serán únicamente, otras empresas del mismo grupo, en su caso, u otros terceros sobre los que recaiga algún tipo de obligación legal para su cesión. Los datos se conservarán durante el periodo durante el cual exista una relación contractual y/o comercial establecida o mientras no nos lo solicite. Sobre el que podrá ejercitar los derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad de sus datos, remitiendo una solicitud por escrito a la dirección anteriormente indicada, acompañando un documento para su identificación. Si tiene cualquier tipo de consulta, comentario o inquietud sobre cómo tratamos la información de carácter personal puede consultar nuestra Política de Privacidad en www.departamentocreativo.com. Puede también ponerse en contacto con nosotros en el teléfono 965305971 y/o en el correo electrónico info@departamentocreativo.com. Si no desea recibir información de carácter comercial de nuestra empresa rogamos nos lo comunique por ese mismo canal.

**Comment by Saimis777** [comment]
No problem @dcdepartamentocreativo !

Do you have any other questions, or need help or we can close the issue?

Let me know!

--
Best regards,
Invertus Support team

**Comment by dcdepartamentocreativo** [comment]
Yes, the issue can be closed

Thanks for your help

pablo alonso DC

✆:  965  305 971 / 966 342 399
@: ***@***.*** ·  www.DepartamentoCreativo.com

DC DEPARTAMENTO CREATIVO
#AÑADIENDOVALOR #VUELTAATOPE---------------------------------------------------------------
Le informamos que sus datos personales están incluidos en un tratamiento, cuyo responsable es ESTRATEGIAS DEL DEPARTAMENTO CREATIVO, S.L.. Creado con la finalidad de gestionar comercial y administrativamente la relación que, en su caso, nos une y de informarle sobre productos, servicios o eventos de nuestra empresa que pudieran ser de su interés por medios tradicionales o electrónicos. Cuya legitimidad recae en la ejecución de un contrato o en su consentimiento previo. Cuyos destinatarios serán únicamente, otras empresas del mismo grupo, en su caso, u otros terceros sobre los que recaiga algún tipo de obligación legal para su cesión. Los datos se conservarán durante el periodo durante el cual exista una relación contractual y/o comercial establecida o mientras no nos lo solicite. Sobre el que podrá ejercitar los derechos de acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad de sus datos, remitiendo una solicitud por escrito a la dirección anteriormente indicada, acompañando un documento para su identificación. Si tiene cualquier tipo de consulta, comentario o inquietud sobre cómo tratamos la información de carácter personal puede consultar nuestra Política de Privacidad en www.departamentocreativo.com. Puede también ponerse en contacto con nosotros en el teléfono 965305971 y/o en el correo ***@***.*** Si no desea recibir información de carácter comercial de nuestra empresa rogamos nos lo comunique por ese mismo canal.

**Comment by Saimis777** [comment]
Thank you for the clarification @dcdepartamentocreativo , closing the issue now.

--
Best regards,
Invertus Support team
