### ISSUE TITLE
Failed status in Mollie not updated into Prestashop / still awaiting mollie payment

### ISSUE THREAD

**Issue by Ditwo** [mollie/PrestaShop#302]
### Expected behavior
After some time (max a few minutes), orders with failed status in  Mollie should be reflected in Prestashop, with the cancelled order status.  

### Actual behavior
But some orders are still in "awaiting mollie payment", even after some days, weeks, or months.

### Steps to reproduce the behavior
Not every order...

### Environment
* PrestaShop version: 1.7.6.5
* Mollie module version: 4.2.2
* PHP version: 7.2.34

Thank you for your help!
Best regards
Denis

**Comment by Saimis777** [comment]
Hello @Ditwo ,

Thank you for your message, could you give us a bit more details on the issue? Maybe share some screenshots, and further steps of which orders fail?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Ditwo** [comment]
Hello,

 

Please find attached the latest examples. Some orders are correctly updated, but not all of them. I’m afraid I can't find any correlation.

 

Regarding the order QEHVKMOJI, stiil awaiting Mollie payment, the transaction status sis « failed », at 9 :31am. 

 

 

 

In the log : 

 [08/Mar/2021:09:31:46 +0100] "GET /fr/module/mollie/return?ajax=1&action=getStatus&transaction_id=tr_RNDt…&key=…&cart_id=235029 HTTP/1.1" 200 4500 "https://www.../fr/module/mollie/return?cart_id=235029&utm_nooverride=1&rand=...&key=...&customerId=..." "Mozilla/5.0 (iPad; CPU OS 12_4_9 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1"

 

 

Do you need more info? 

 

Best regards

Denis 

 

De : Saimis777 [mailto:notifications@github.com] 
Envoyé : vendredi 5 mars 2021 17:38
À : mollie/PrestaShop
Cc : Ditwo; Mention
Objet : Re: [mollie/PrestaShop] Failed status in Mollie not updated into Prestashop / still awaiting mollie payment (#302)

 

Hello @Ditwo <https://github.com/Ditwo>  ,

Thank you for your message, could you give us a bit more details on the issue? Maybe share some screenshots, and further steps of which orders fail?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello, thank you for the additional information!

Would be best if you could provide your back office/FTP details to -support@invertus.eu for further investigation.

Let me know if that is possible!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

Just wanted to keep you updated that we are still working on the case, and I will notify you once I will receive further information from our team.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @Ditwo ,

I will notify you via email as previously once we will come to a resolution to this.

Thank you for your patience!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @Ditwo ,

We've resolved the issue, I've also sent you an email as well.

I will close this issue for now, as it's resolved, and be sure to let me know if anything else comes up, we will then investigate further!

--
Best regards,
Invertus Support team
