### ISSUE TITLE
PHP Notice:  Undefined index: isApplePayMethod

### ISSUE THREAD

**Issue by wzzly** [mollie/PrestaShop#324]
### Expected behavior
This seem to work, but we don't use Applepay right now.

### Actual behavior
We still get php notice
[lsapi:warn] PHP Notice:  Undefined index: isApplePayMethod in /home/u56000p87797/domains/ha-ma.nl/public_html/modules/mollie/src/Service/PaymentMethod/PaymentMethodRestrictionValidation/ApplePayPaymentMethodRestrictionValidator.php on line 101\n, referer: https://www.edenberg.store/nl/bestelling

Looks like these notices started after updating to 1.7.7.3 from 1.7.6.9

### Environment
* PrestaShop version: 1.7.7.3
* Mollie module version: 4.2.3
* PHP version: 7.3.26

**Comment by Saimis777** [comment]
Hello, thank you for your message!

Could you clarify the issue a bit? You mena you have Apple pay disabled, yet this error still comes up is that correct? In the folloiwng link that you've provided, how can I replicate this issue?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
Yes Apple pay is disabled, but everytime somebody visits the checkout page, this php notice is being logged. 
Looks like a variable is not being defined in ApplePayPaymentMethodRestrictionValidator.php?

**Comment by Saimis777** [comment]
Thank you for that!

Do you use any sort of one page checkout modules?

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
Yes, we use One Page Checkout module. Is this the problem with this update?

**Comment by Saimis777** [comment]
Which One Page checkout module are you using could you clarify?

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
The Checkout
https://addons.prestashop.com/nl/bestelproces/42005-the-checkout.html

**Comment by Saimis777** [comment]
Hello thank you for that,

Could you also clarify if you are using multistore? Also, we would need your BO/FTP credentials to investigate this further, could you send them to - support@invertus.eu?

Just be sure when ending, to create the email as a new one, so it woudn't get replied in Github.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
Yes we use multistore. We have 2 storefronts. 
BO/FTP credentials send

**Comment by Saimis777** [comment]
Thank you for the additional details,

I've already forwarded them to the developers, waiting on their response, and will clarify your further question from the email!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey!

The 4.3.0 version was released, and your  fix is included!

I've included the pull request, you can download the new version here - https://github.com/mollie/PrestaShop/releases/tag/4.3.0

Any feedback provided is greatly appreciated!

--
Best regards,
Invertus Support team
