### ISSUE TITLE
"Er is geen definitieve betaalstatus bekend" v1.3.0 met PrestaShop 1.6.1.11

### ISSUE THREAD

**Issue by muyncky** [mollie/Prestashop#33]
Na het updaten van PrestaShop 1.6.0.4 naar 1.6.1.11 heb ik ook de Mollie module geüpdatet van 1.0.8 naar 1.3.0. De betalingen werden niet geregistreerd, ik heb het eerst gezocht bij de update van PrestaShop (natuurlijk!). 

Na wat zoeken zag ik de volgende error:
`PHP Catchable fatal error:  Argument 1 passed to Swift_Mime_SimpleMessage::__construct() must be an instance of Swift_Mime_HeaderSet, none given in /home/*/public_html/tools/swift/classes/Swift/Mime/SimpleMessage.php on line 27`
Hierop heb ik gezocht en toen kwam ik op het volgende forum topic van PrestaShop:
https://www.prestashop.com/forums/topic/535929-unable-to-send-email/
Waarin `monkPL` zei "When I removed parent::initContent() in initContent, then everything it's ok now", zo doende heb ik dus `parent::initContent();` gecomment in `modules/mollie/controllers/front/webhook.php`. Nu kom ik gewoon op een succesvolle order confirmation pagina. en de betaling is geregistreerd.

Ik vraag me ook af wat de toegevoegde waarde is van initContent(). Wellicht worden er onwenselijke data meegegeven in de response van `initContent()`.

Edit: regelmatig komen de orders toch nog binnen op status "OPEN". De webhook wordt wellicht niet (op tijd) aangeroepen.

**Comment by Trendweb** [comment]
Beste @muyncky ,

Hartelijk dank voor jouw feedback. We zijn dit zowel voor Prestashop 1.6 als 1.7 aan het onderzoeken en bezig met de nodige aanpassingen. Op korte termijn zal er een nieuwe versie beschikbaar zijn van de Mollie Module.
