### ISSUE TITLE
Klarna payment_fee problem at checkout

### ISSUE THREAD

**Issue by petrovv77** [mollie/PrestaShop#332]
### Expected behavior
Payments via Klarna are not going well.

### Actual behavior
At checkout and choice klarna with a small extra amount (fee). there is a problem with the "ajax controllers and decimal numbers". klarna payments are canceled / or cannot be processed.

When turning off the extra fee, it seems to be going well.

### Error Log Apache:
`... PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PrestaShop\\Decimal\\Operation\\Addition::compute() must be an instance of PrestaShop\\Decimal\\Number, instance of PrestaShop\\Decimal\\DecimalNumber given, called in .../modules/mollie/vendor/prestashop/decimal/src/DecimalNumber.php on line 306 and defined in .../vendor/prestashop/decimal/src/Operation/Addition.php:42\nStack trace:\n#0 .../modules/mollie/vendor/prestashop/decimal/src/DecimalNumber.php(306): PrestaShop\\Decimal\\Operation\\Addition->compute(Object(PrestaShop\\Decimal\\DecimalNumber), Object(PrestaShop\\Decimal\\DecimalNumber))\n#1 .../modules/mollie/controllers/front/ajax.php(44): PrestaShop\\Decimal\\DecimalNumber->plus(Object(PrestaShop\\Decimal\\DecimalNumber))\n#2 .../classes/controller/Controller.php(295): MollieAjaxModuleFrontController->postProcess()\n#3 .../classes/Dispatcher.php(518): ControllerCore->run()\n#4 .../index.php(28): in .../vendor/prestashop/decimal/src/Operation/Addition.php on line 42`

### Environment
* PrestaShop version: 1.7.7.3
* Mollie module version: 4.2.4
* PHP version: 7.2.24

**Comment by Saimis777** [comment]
Hello @petrovv77 ,

Thank you for your message!

I've passed the information to our team, I will get back to you as soon as we will go through your reported issue!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @petrovv77 ,

We've managed to fix the issue, and will include this fix in the next release (4.3.0)!

Let me know if you have any further questions!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey!

The 4.3.0 version was released, and your fix is included!

I've included the pull request, you can download the new version here - https://github.com/mollie/PrestaShop/releases/tag/4.3.0

Any feedback provided is greatly appreciated!

--
Best regards,
Invertus Support team
