### ISSUE TITLE
No payment available in FO

### ISSUE THREAD

**Issue by fredoche1810** [mollie/PrestaShop#333]
### behavior
Since the upgrade to prestashop 1.7.7.3, the customers have an error 500 after they have chosen their payment method. I upgraded from 4.2.2 to 4.2.4 to solve it but now there are no payment visible in the front office for the customers.

### Environment
* PrestaShop version: 1.7.7.3 
* Mollie module version: 4.2.4 
* PHP version: 7.1.33 

If I downgrade to 4.2.2, the payments reappear in the FO ... but with error 500

**Comment by Saimis777** [comment]
Hello @fredoche1810 !

Thank you for your message, can you check if the payment methods are even enabled and if they have any country restrictions in the back office? Also, have you checked the steps in our Wiki to troubleshoot the issue, and confirm that none of the steps from this page helped?
- https://github.com/mollie/PrestaShop/wiki/Troubleshooting#payment-method-does-not-appear-in-front-office 

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by fredoche1810** [comment]
Hello,

I checked all those before I sent you the message.

I downgrade to 4.2.2 and all the payments reappears.

If I use 4.2.3 or 4.2.4 all the payments are invisible in the front and 
the options are correctly configured.

Thanks in advance,



Le 05-05-21 à 12:08, Saimis777 a écrit :

**Comment by Saimis777** [comment]
Hi @fredoche1810,

Would you be able to provide us with your BO/FTP credentials for further investigation? Just be sure to send them separately as a new email at - support@invertus.eu and not reply via Github, to avoid them being shown on Github as a reply.

Let me know if you would be able to do so!

--
Best regards,
Invertus Support team

**Comment by fredoche1810** [comment]
Hello,
Mollie solved the problem ... but they can't explain it.
The only thing they have done is to put the module in test in case of live and then again in live and the payments reappears.
Thanks,
