### ISSUE TITLE
Not receiving cancelled email after the cancellation of a payment or order

### ISSUE THREAD

**Issue by QuintenDeDecker** [mollie/PrestaShop#342]
### Expected behavior
When the client cancels a payment or order to get an order cancelled mail

### Actual behavior
No mail or notification is send

### Steps to reproduce the behavior
Place and cancel the order or payment

### Environment
* PrestaShop version: 1.7.7.4
* Mollie module version: 4.2.4
* PHP version: 7.3.27

**Comment by Saimis777** [comment]
Hello Quinten!

Thank you for your message!

We will check with this issue internally if we can replicate it, and let you know!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @QuintenDeDecker ,

Tested “Cancel Order” functionality. If order is canceled from BO then prestashop sends mail to customer. 
In module settings you can't enable mail sending when order status changed to cancelled.
If you use some specific module on his project, to provide an opportunity to cancel order to customers, then we need to test this module interaction with Mollie module.

Maybe you could share your shop and FTP credentials to support@invertus.eu so we would check within your shop? Just be sure not to reply to this thread, so they wouldn't get published.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by QuintenDeDecker** [comment]
Hello,

The problem is that the customer places an order and we get an email that the order is placed. But then the customer doesn’t finish paying and we don’t get notified from that.
This cancels the order automatically but we don’t get a mail from that, the last mail we receive relevant to that order is “order placed”.

Met vriendelijke groeten,
Kind regards,

[IT Experts logo]

[facebook logo]<https://www.facebook.com/itexpertsbvba/>  [linkedin logo] <https://www.linkedin.com/company/it-experts-bvba/>
Quinten De Decker
DevOps Engineer

***@***.******@***.***>
+32 (0) 9 395 04 04
Leopoldlaan 41, 9900 Eeklo
www.itexperts.be<https://www.itexperts.be>

[VoIP]<https://www.itexperts.be/#contact>
Van: Saimis777 ***@***.***>
Verzonden: dinsdag 1 juni 2021 13:58
Aan: mollie/PrestaShop ***@***.***>
CC: Quinten De Decker ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [mollie/PrestaShop] Not receiving cancelled email after the cancellation of a payment or order (#342)


Hello @QuintenDeDecker<https://github.com/QuintenDeDecker> ,

Tested “Cancel Order” functionality. If order is canceled from BO then prestashop sends mail to customer.
In module settings you can't enable mail sending when order status changed to cancelled.
If you use some specific module on his project, to provide an opportunity to cancel order to customers, then we need to test this module interaction with Mollie module.

Maybe you could share your shop and FTP credentials to ***@***.******@***.***> so we would check within your shop? Just be sure not to reply to this thread, so they wouldn't get published.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @QuintenDeDecker ,

We assume that you are using the “mail alerts” module to get the new order emails and as Mollie we do no send any emails to the merchant. We can only stop the new order email from sending to the merchant if the new order is created with the module. 
So functionality that you get new order emails comes from another module and it doesn’t have the functionality to send an email when order is being canceled.
![image](https://user-images.githubusercontent.com/75423142/120609016-77be6800-c45a-11eb-860d-c15eff43d071.png)



Let me know if you have any further questions!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @QuintenDeDecker ,

Do you need further assistance? Or do you have any other questions? If you do, please let me know!

I will close this issue for now, if you'll need help, we can always re-open it!

--
Best regards,
Invertus Support team
