### ISSUE TITLE
Locale is invalid (French language)

### ISSUE THREAD

**Issue by pantoffelke** [mollie/PrestaShop#343]
### Expected behavior
Pay credit card with French language

### Actual behavior
When have language French and want pay credit card they get Locale is invalid, when select English language no error anymore.

[Capture d’écran 2021-05-28 à 08.02.17.pdf](https://github.com/mollie/PrestaShop/files/6561750/Capture.d.ecran.2021-05-28.a.08.02.17.pdf)

### Steps to reproduce the behavior
Add French? Automatically change to English?

### Environment
* PrestaShop version: 1.7.7.4
* Mollie module version: 4.2.4 
* PHP version: 7.3

**Comment by Saimis777** [comment]
Hi @pantoffelke ,

Thank you for your message! 

We will check with this issue and let you know! 

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Aldo,

Did you try the method that was described in the wiki? Did it help? You can find it here:

https://github.com/mollie/PrestaShop/wiki/Known-Issues#Locale-is-invalid

Let me know if it's helpful!

--
Best regards,
Invertus Support team

**Comment by pantoffelke** [comment]
OK thx, in test mode had no problem now.

**Comment by Saimis777** [comment]
Hey @pantoffelke ,

Only in test mode no problems or live as well?

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @pantoffelke ,

Do you need any further assistance? Or we can close the issue?

--
Best regards,
Invertus Support team

**Comment by pantoffelke** [comment]
can close

**Comment by Saimis777** [comment]
Thanks.

Closing the issue, let us know if further help is needed!

--
Best regards,
Invertus Support team
