### ISSUE TITLE
Mollie payments options do not show at checkout in prestashop paying step

### ISSUE THREAD

**Issue by abdel23421** [mollie/PrestaShop#344]
### Steps to reproduce the behavior

Everything is configuert correctly and api are connected succesfully, but still mollie is showing a error code in log information dashboard with adminmollie error ?

### Environment
* PrestaShop version: 1.7.7.4 
* Mollie module version: 4.2.4 
* PHP version: 7.2

**Comment by Saimis777** [comment]
Hi @abdel23421,

Thank you for your message!

Have you tried checking out our wiki? We have an article regarding your situation that I believe will resolve your issue! Please find it here - https://github.com/mollie/PrestaShop/wiki/Troubleshooting#payment-method-does-not-appear-in-front-office

Let me know if it's helpful or not!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @abdel23421 ,

Did you managed to get your payment methods to show or not?

Let us know!

--
Best regards,
Invertus Support team

**Comment by abdel23421** [comment]
Yes, it worked. Thank you for that. But some other problem accurate with the speed of the website when loading. It takes a long time to load mollie, after did a scan i saw that the javascript used for this module, Is old and is upgradeable. If it 's possible could the javascript get an update so it will be faster when loading.

**Comment by Saimis777** [comment]
Hey @abdel23421 ,

Thank you for the feedback! 

I will definitely check what are the possibilities of that happening, inform Mollie team, and we will see what can be done.

I am marking this issue as resolved, if you'll have any other issues, let us know by raising a new issue!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
@abdel23421 ,

Could you also clarify the name of your website? And maybe clarify a bit further where exactly is the js getting blocked and slows the website down?

--
Best regards,
Invertus Support team
