### ISSUE TITLE
Feature request: Being able to ignore ISO codes

### ISSUE THREAD

**Issue by Bahbv** [mollie/PrestaShop#345]
### Feature
I would like to request an option for ignoring ISO codes.

### Why
Mollie only allows valid ISO codes with a max character count of 2. For my usecase I needed to make extra country's for each province in the Netherlands so I could set up diffferent shipping costs for each province. First I used ISO codes like NZH for Netherlands - Zuid Holland. But like I said, that doesn't work with Mollie.

**Comment by Saimis777** [comment]
Hi @Bahbv ,

Thank you for your message!

We will discuss this internally with Mollie and get back to you as soon as possible if it will be possible to approve such feature or not!

--
Best regards,
Invertus Support team

**Comment by SimonasB88** [comment]
Dear @Bahbv very sorry to say, but according to Mollie Team, they are not planning any of the improvements referring to this topic.

Have a great day!

Best Regards,
Invertus Support Team
