### ISSUE TITLE
No "double" orders please?

### ISSUE THREAD

**Issue by tajriba** [mollie/PrestaShop#346]
HI,

We have mollie module 4.2.3.

Orders are created before payment is done.
So we have like, 1 order with "pending state" and second order same customer with paid state.
How to prevent the pending / failed payments as order in the backoffice?

**Comment by Saimis777** [comment]
Hi @tajriba ,

Thank you for your message. 

Orders being created before payment is a default Prestashop function, you can read about it and understand why it is done so here - https://github.com/mollie/PrestaShop/wiki/Known-Issues#Order-is-created-before-successful-payment

Let me know if you have any more questions regarding it!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
HI,

Due to this issue being known, and well written in the wiki page, I will close it for now, let me know if you have any further questions!

--
Best regards,
Invertus Support team
