### ISSUE TITLE
Missing lines Error while canceling klarna order

### ISSUE THREAD

**Issue by vanengers** [mollie/PrestaShop#347]
### Expected behavior
Successfull cancellation of order (all lines).

### Actual behavior
No lines are cancelled

### Steps to reproduce the behavior
Order with Klarna pay later method. Cancel order (all lines).

### Environment
* PrestaShop version: 1.7.6.0
* Mollie module version: 4.2.4 
* PHP version: 7.3.27 

![mollie_error](https://user-images.githubusercontent.com/39123706/120456668-1f259700-c396-11eb-8f4a-dfecd9da2b5b.JPG)

**Comment by Saimis777** [comment]
Hi @vanengers ,

Could you please provide more information on this please? Is it just 1 order that was cancelled which was paid with Klarna? Does it happen with other payment methods or not?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by vanengers** [comment]
This happens with all orders which are authorized at Klarna. 
When i press cancel i select the items (this case: all items) and press OK.

**Comment by vanengers** [comment]
If you need further information please contact me at george@dewebsmid.nl

**Comment by Saimis777** [comment]
Hi @vanengers ,

I've just sent an email for you!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Issue resolved, fix added to the client's shop.
