### ISSUE TITLE
Backorder status set to (Paid) without accepted payment

### ISSUE THREAD

**Issue by fredoche1810** [mollie/PrestaShop#349]
Describe the bug
When ordering products with 0 stock or less and the option to allow orders is set to true in BO the order status is set to Backorder (unpaid) when the customer try to pay and change into Backorder (paid) when the customer failed to pay or cancel the payment.

Expected behavior
When ordering out of stock products, the correct status should be Backorder (Unpaid)

Steps to Reproduce

Place order with 0 stock product
Let the order go through
Select a mollie payment.
Don't pay and cancel it.
Check order status

Additional information
PrestaShop version: 1.7.7.3
Php version: 7.1.33

The same problem seems to appears with other payment modules :  https://github.com/PrestaShop/PrestaShop/issues/23953

Status in prestashop
![image](https://user-images.githubusercontent.com/13088049/120997217-4cec5080-c787-11eb-985b-5828f617fe52.png)

History in Mollie
![image](https://user-images.githubusercontent.com/13088049/120997449-7dcc8580-c787-11eb-980d-4853cfaaf855.png)

Thanks in advance for your help.

**Comment by Saimis777** [comment]
Hey @fredoche1810 ,

Thank you for the message! Could you also clarify please which version of the module you are using? Have you tried firstly updating the module to 4.3.0? You can download it here - https://github.com/mollie/PrestaShop/releases/tag/4.3.0

Also, as we could not replicate this issue, we would need the shop credentials, BO logins and FTP, could you send them to the same email you've sent us earlier today?

--
Best regards,
Invertus Support team

**Comment by fredoche1810** [comment]
Hey @Saimis777 ,
I was not using the latest version. I just upgrade from 4.2.4 to 4.3.0 to test it again and unfortunately it's still the same issue.
The upgrade didn't solve the problem.
I send you an mail with our credentials.
Best regards,

**Comment by Saimis777** [comment]
Hi @fredoche1810 ,

We found the issue and after debugging and managed to fix it. Added a fix to the your shop, you can now check it out, test it, and let us know if further help is needed, or if we can close the issue!

--
Best regards,
Invertus Support team

**Comment by fredoche1810** [comment]
Hi @Saimis777,
Happy that you finally found an issue and that you have fix it.
I just made the same test as when I had a problem and now it works...
![image](https://user-images.githubusercontent.com/13088049/121523590-aad29f80-c9f6-11eb-8760-87738bc4fb05.png)

After cancelling the payment, the order is going to the state canceled.
I suppose you will add it in the next upgrade for everybody.
For me you can close the issue.

Best regards,

**Comment by Saimis777** [comment]
Nice!

Yes, will add the fix.

Let us know if you need any further help!

Have a nice day!

--
Best regards,
Invertus Support team
