### ISSUE TITLE
payment allowed from country doesn't work

### ISSUE THREAD

**Issue by Spiros333** [mollie/PrestaShop#350]
### Expected behavior
Include a country for a payment option

### Actual behavior
When including the county it doesn't show on the checkout the payment option with the country we just included.

### Steps to reproduce the behavior
Included the country The netherlands for iDeal, when going to the checkout and having in the shipping address the country The Netherlands. The iDeal option isn't shown.

### Environment
* PrestaShop version: 1.7.6.2
* Mollie module version: 4.3.0 
* PHP version: 7.2

**Comment by Saimis777** [comment]
Hey @Spiros333 !

Thank you for your message!

We have an article regarding this topic already, you can find it here - https://github.com/mollie/PrestaShop/wiki/Troubleshooting#payment-method-does-not-appear-in-front-office

Please check it out, try the given steps and let me know if it's helpful!

--
Best regards,
Invertus Support team

**Comment by Spiros333** [comment]
First dot:
Payment is enabled on the Mollie Dashboard

Second dot:
Uninstalled molie, deleted the folder plugin also on the server and installed mollie again.

back office -> Payment -> Preferences -> Country restrictions, 
No Country restriction for the Netherlands

Same issue still

**Comment by Saimis777** [comment]
Hello,

For Apple Pay, be sure that you are using Safari or a device that is compatible with Apple pay, you can check if it's compatible or not via this site here - https://applepaydemo.apple.com/

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Spiros333** [comment]
This has nothing to fo with my repported problem.
I did speak about Apple Pay.
My problem is when I allow a country in the plugin for example iDeal for the Netherlands the payment option disapear.
It only works when selecting the option allow ALL countrys.

**Comment by Spiros333** [comment]
Correction: This has nothing to do with my repported problem.
I did speak about Apple Pay.
My problem is when I allow a country in the plugin for example iDeal for the Netherlands the payment option disapear.
It only works when selecting the option allow ALL countrys.

**Comment by Saimis777** [comment]
Hey!

And is it an issue keeping all the countries as allowed with the payments? For which countries you want to disabled the payment?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by jean-philippeansel** [comment]
Same issue here.
Already followed the steps there: https://github.com/mollie/PrestaShop/wiki/Troubleshooting#payment-method-does-not-appear-in-front-office

I'm trying to enable Giropay for Germany only.
If I select "payment allowed for all countries", Giropay is show for all customers, including german customers.
If I select "payment allowed for selected countries" and then I put "all countries" or "Germany" in the field below, Giropay won't show for anybody.

**Comment by Spiros333** [comment]
Saimis777 can you make an point of this and come with a fix?

And is it an issue keeping all the countries as allowed with the payments? 
>>Yes it is.

For which countries you want to disabled the payment?
I want to change the question in which countries I want it to show, so you will know which countrys I do want to disable.
Shown only :
>> iDeal the ony netherlands (so only for the country(s) it works for)
>> Klarna only Germany, netherlands, finland, belgium, austria. (so only for the country(s) it works for)
>> KBC belgium only (so only for the country(s) it works for)
>> bancontact belgium only (so only for the country(s) it works for)
>> belfius belgium only (so only for the country(s) it works for)
>> cartes bancaires only france  (so only for the country(s) it works for)

**Comment by Saimis777** [comment]
Hi @jean-philippeansel @Spiros333 ,

We investigated and found the issue and managed to fix it. This will be released in the next release. 
Here’s a module with a fix in the meantime:

https://ufile.io/sjf6qk21

Let me know if everything works!

--
Best regards,
Invertus Support team

**Comment by jean-philippeansel** [comment]
Hi @Saimis777 ,

That's great! I installed the module and it works perfectly.
Thanks!

**Comment by Spiros333** [comment]
When will we receive an stabile mollie module? Where the known(old) features will work and keep on working.
Everytime there is something missing or wrong with it.
This is kinda amateuristic to be honnest.
Im updating an new version of mollie to have a beter module with newer features, sometimes don't even want to update thinking of what for problems the new version will bring.

Can you do something about this?
Thanks

**Comment by Saimis777** [comment]
Glad to hear that everything works, thank you! @jean-philippeansel 

Thank you for your feedback @Spiros333 !

The fact that 4.3.0 release has multistores compatibility with multiple shops integrated for the first time, it required different approaches on ID's that are being taken from the database, and as this is a very big update, customers feedback is well important to make the release even more stable than it is now, therefore thank you again for the feedback, and we will keep on improving the module everyday for a better customer experience!

--
Best regards,
Invertus Support team

**Comment by SimonasB88** [comment]
Hello, 
This issue is being closed now for the inactivity for some time. Please raise a separate ticket in Mollie Issues if the issue still occurs.
Thank you for understanding!
Have a great day.

Best Regards,
Invertus Support Team
