### ISSUE TITLE
New order : Order is created before order is actually paid

### ISSUE THREAD

**Issue by loetje88** [mollie/PrestaShop#356]
### Expected behavior
Order should be put through as new order if it is really paid and when customer has being redirected to thank you page.

### Actual behavior
order is created and put through as "awaiting bank" as soon as mollie is initialised

### Steps to reproduce the behavior
Place an order

### Environment
* PrestaShop version: 1.7..7.3 
* Mollie module version: 4.2.4
* PHP version: : 7.3.28

**Comment by crezzur** [comment]
You can try to change following settings in your Mollie module?

1. Go to Prestashop back-office
2. Open Mollie module
3. Click on tab **Advanced settings**
4. Change the setting of **Send order confirmation via email** and **Send a new order email to the webshop** to **When the order is paid**

**Comment by loetje88** [comment]
Hi,

Thaka for your reply.

At the moment send new order email is already set on when order is paid.

Unfortunately, mollie sees a new order directly on the moment customer 
enters payment screen before customers can actually pay.

crezzur schreef op 2021-06-12 12:32:

**Comment by Saimis777** [comment]
Hey @loetje88 ,

Thanks for your message!

Order being created instantly is standard Prestashop functionality, and at the moment this can't be changed, sorry, you can read more about it here - https://github.com/mollie/PrestaShop/wiki/Known-Issues#Order-is-created-before-successful-payment

Be sure to let me know if you have any more questions!

Or if we can close the issue!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @loetje88 ,

Do you have any further questions regarding this case, or need assistance?

Let me know!

--
Best regards,
Invertus Support team

**Comment by SimonasB88** [comment]
This case is closed due to inactivity for some time.
Please raise another ticket if you encounter issue again.

Best Regards
Invertus Support Team

**Comment by AnatoleRozan** [comment]
Hello guys,

I've seen that point with Prestashop core team.

Mollie says : _"It is a Prestashop default and suggested process for order creation"_. 
**==> But actually this information hasn't been formalized by Prestashop team.**

You should give the option to register only paid orders in the BO (as all payement solutions).
For me, you've done that to match with your own order creation process.

But for "big" e-commerce, it is really bad to have tone of expired orders...

Could you check that with your team?
