### ISSUE TITLE
Customer cant return to checkout once payment is initialised

### ISSUE THREAD

**Issue by loetje88** [mollie/PrestaShop#357]
### Expected behavior
When mollie is initialised and opens in new screen, customer should be able to just return to the previous checkout page where they would be able to cgange/edit their order

### Actual behavior
customer return to hanging screen which keeps saying "afwaiting payment status".
Order is being put through as new order while order is not paid nor will be paid since customer cant do anything anymore

### Steps to reproduce the behavior
place order, return to previous page when mollie opens in new screen (issuer list) by using "previous arrow" or click "payment methods".

### Environment
* PrestaShop version: 1.7..7.3 
* Mollie module version: 4.2.4
* PHP version: : 7.3.28

**Comment by Saimis777** [comment]
Hi @loetje88 ,

Thank you for your message!

We will check with the issue internally, and let you know if we'll be able to reproduce it!

Also, is it the same with the 4.3.0 version?

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @loetje88 ,

I've just received further information from the development team, and this is how prestashop works when we press the “Order” button on the last checkout step and get redirected to the Mollie payment page the order is being created in prestashop. When we click payment methods the order should get canceled order status. And when using the previous arrow payment should be canceled in some time when Mollie system cancels payment and calls our webhook.

Let me know if you have any further questions or if we can close the ticket!

--
Best regards,
Invertus Support team

**Comment by SimonasB88** [comment]
This case is closed due to inactivity for some time.
Please raise another ticket if you encounter the issue again.

Best Regards
Invertus Support Team
