### ISSUE TITLE
Manual backoffice order payment email not send

### ISSUE THREAD

**Issue by Adekonl** [mollie/PrestaShop#361]
### Expected behavior

The customer receiving an email with payment-link when the order is created from the backoffice is merchant chooses to do so. 

### Actual behavior

Email is not send and the mollie-column doesn't appear in the backoffice. Making it impossible to send a second-chance email to the customer.

### Steps to reproduce the behavior

Backoffice->Order->create new order -> choose Mollie at the payment-section, check checkbox to send a payment-link -> Create order.
![image](https://user-images.githubusercontent.com/20944577/122537214-a2e1b380-d025-11eb-95ac-efdab1664037.png)

### Environment
* PrestaShop version: 1.7.7.2, 1.7.7.4 
* Mollie module version: 4.2.4, 4.3.0 
* PHP version: 7.3.x

**Comment by SimonasB88** [comment]
Hello @Adekonl thank you for the submission here, I can assure that the Support team has received and registered this case for development investigation.

I will update you ASAP about the investigation status.

Best Regards
Invertus Support Team

**Comment by Saimis777** [comment]
Hi @Adekonl ,

Maybe you could provide us with your BO/FTP credentials for further investigation? If yes, please send them to - support@invertus.eu

Just be sure to not reply to this message.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @Adekonl ,

Could you clarify if you would be able to send further needed details for the investigation?

Thank you!

--
Best regards,
Invertus Support team

**Comment by Adekonl** [comment]
Hi Saimis, 
Thanks for the heads-up, i've just emailed you the credentials.

**Comment by Saimis777** [comment]
Hi @Adekonl ,

Managed to reproduce the issue on the local machine and added a fix to your dev environment. Unfortunately, the provided  shop doesn’t load for us and we couldn’t test it on you dev environment. 
Files that were changed shop_folder/modules/mollie/mollie.php line 1064 if ('AdminOrders' === $this->context->controller->controller_name &&` replaced with if (!empty(Tools::getValue('mollie-email-send')) &&` 

Let us know if everything is okay!

--
Best regards,
Invertus Support team

**Comment by Adekonl** [comment]
Works like a charm, thanks!!

Met vriendelijke groet / With kind regards,
Jeroen Kodde
Developer
+31 (0)30 69 13 905 <tel:+31 (0)30 69 13 905>
www.adeko.nl <https://www.adeko.nl/>
Facebook <https://www.facebook.com/www.adeko.nl/> 	Instagram 
<https://www.instagram.com/adeko_promotional_products/> 	Linkedin 
<https://www.linkedin.com/company/adeko-zeist>

Adeko voor on- & offline zichtbaarheid 	Adeko Promotional Products 	
Adeko is opzoek naar nieuw talent!
Bekijk vacatures <https://www.adeko.nl/vacatures//>

Klik hier voor de verkoops- leverings- en betalingsvoorwaarden van 
Adeko. 
<https://www.adeko.nl/wp-content/uploads/2020/08/Voorwaarden-Adeko-V_8.2020-2.pdf>

**Comment by Saimis777** [comment]
@Adekonl ,

Thanks for the clarification!

Marking issue as resolved.

Be sure to re-open the issue if you'll need further help or raise a new one for other questions!

Have a nice day!

--
Best regards,
Invertus Support team
