### ISSUE TITLE
Klarna payment additional fee not updated total price order overview

### ISSUE THREAD

**Issue by petrovv77** [mollie/PrestaShop#378]
Klarna payment additional fee not updated total price order overview.
It gives no problems when processing the order, invoice or mail, it's just a little bug in the order overview.

![orderscreentotalprice](https://user-images.githubusercontent.com/77987971/125059951-284c0700-e0ac-11eb-8c3f-9f5908428b7a.png)
![orderscreentotalprice2](https://user-images.githubusercontent.com/77987971/125059962-2bdf8e00-e0ac-11eb-8960-d9eb3956db53.png)

### Environment
* PrestaShop version: 1.7.7.5 
* Mollie module version: 4.3.0
* PHP version: 7.2.24

**Comment by Saimis777** [comment]
Hi @petrovv77 ,

Thanks for your message!

We will check with this issue internally on 1.7.7.5 version, as for now we could not replicate this issue on other versions of PS, could be that Prestashop version specific, I will provide feedback as soon as I will have it from the developers. 

Thank you.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
@petrovv77 ,

We've setup the same environment as you've provided, made some test orders with Klarna and with the additional fee added, but could not reproduce the issue on our end:
![image](https://user-images.githubusercontent.com/75423142/125070446-a2868680-e0c0-11eb-8303-4a8031f9c695.png)


Maybe you could provide us with you BO+FTP credentials for further investigation? If yes, please send them to - support@invertus.eu and be sure to net reply to this message, yet create a separate email so it would not get shared within GitHub.

--
Best regards,
Invertus Support team

**Comment by petrovv77** [comment]
@Saimis777 
remote research with us is a bit complicated because we don't use regular ftp.
I use percentage and fixed costs. 
![klarna](https://user-images.githubusercontent.com/77987971/125071746-0063a000-e0ba-11eb-9e48-78cb7f25195a.png)
maybe it was a decimal thing...
I'll wait for the next Klarna payment, and see if the same occurs there.
Earlier version 4.2.4 went well.

**Comment by Saimis777** [comment]
Thanks for the clarification @petrovv77 ,

We will try to replicate it one more time by your example, and will let you know with the outcome!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @petrovv77 ,

Unfortunately we could not reproduce the issue after trying again, maybe there were more Klarna payments within your shop that we could investigate?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by petrovv77** [comment]
@Saimis777 

no payment received through Klarna after reporting. So you can close this issue for now
