### ISSUE TITLE
.env.dist does not contain SENTRY_ENV

### ISSUE THREAD

**Issue by WBNet-Wout** [mollie/PrestaShop#379]
With v4.3.2 installed, I'm getting the following warning:

```
PHP message: PHP Warning:  constant(): Couldn't find constant Mollie\Config\Config::SENTRY_ENV in /var/www/html/modules/mollie/src/Config/Env.php on line 32
```

`.env.dist` indeed only contains `GITHUB='MARKETPLACE'`, which I assume was accidentally typed instead of `SENTRY_ENV='MARKETPLACE'`.

**Comment by SimonasB88** [comment]
Hello @WBNet-Wout thank you for your insight, sorry for a delay,

Strange, it might be the mistype problem. I have to check with dev team and get back to you.

Best Regards
Invertus Support Team

**Comment by SimonasB88** [comment]
Hello @WBNet-Wout 

We asume that it should be `SENTRY_ENV='GITHUB'` if module is from github. And `SENTRY_ENV='MARKETPLACE'` if module is from marketplace.

Upladed the updated Mollie.zip here, please try it out, and give us feedback: https://drive.google.com/file/d/1vyNZ2wfIr4-B7mL5Fi4dBnDdyYPeTA_E/view?usp=sharing

Best Regards
Invertus Support Team

**Comment by WBNet-Wout** [comment]
That updated `mollie.zip` indeed does not have the warning.
