### ISSUE TITLE
Open orders are considered as "On backorder (paid)" during the payement process

### ISSUE THREAD

**Issue by AnatoleRozan** [mollie/PrestaShop#380]
### Expected behavior
The customer confirm the order, and is redirected to the Mollie payement page.
The order is now considered as "opened". The order should be "Awaiting for payement" or "Opened" in the Prestashop back-office.
I have changed the status to "Opened" to "Awaiting for payement" in the module configuration.

<img width="1189" alt="Capture d’écran 2021-07-20 à 13 51 17" src="https://user-images.githubusercontent.com/38098728/126319161-619ea686-404f-4a60-a934-ba3c6c581723.png">

### Actual behavior
The order is considered as "Waiting for restocking" during the payement process, even if the customer didn't finalize it.
The order changed its statuts to "canceled" after the expiry time. But it shouldn't be considered as "Waiting for restocking" during the payement process.

I think it is because Mollie module is not working with the advanced stock gestion.

### Environment
* PrestaShop version: 1.7.7.4
* Mollie module version: 4.3.2
* PHP version: 7.2.34

**Comment by SimonasB88** [comment]
Hi @AnatoleRozan, thank you for your insights, I can confirm, that we got your message.

Are you using some stock management related modules in your Prestashop? "Waiting for restocking" seems like not default Prestashop Order status.

Best Regards
Invertus Support Team

**Comment by AnatoleRozan** [comment]
Hi Simon, sorry I mean the default Prestashop status for an out of stock product. The official name is : "On backorder (paid)".
The Prestashop websites have this status when you enable the functionality "Accept orders even if the product is out of stock" (https://doc.prestashop.com/display/PS17/Orders).

**Comment by AnatoleRozan** [comment]
But the default status "On backorder (paid)" is a status which consider the order as paid.

**Comment by SimonasB88** [comment]
Hi @AnatoleRozan thanks for update, I have passed the information to the dev team, I will let you know the investigation results, referring to this Mollie version. We will try to reproduce exactly as you describe.

Best Regards
Invertus Support Team

**Comment by AnatoleRozan** [comment]
Thank you for your answer.

To reproduce the bug :
1. Enable the stock functions
2. Enable the option to accept orders on out of stock products
3. Launch the order process

**Comment by SimonasB88** [comment]
@AnatoleRozan 
Thank you for your steps.
Seems like regular and default ones.
We will update you.

Best Regards
Invertus Support Team

**Comment by SimonasB88** [comment]
Hello @AnatoleRozan 

Thanks for your patience. 
If a customer orders products that are out of stock, the status should be set to “On backorder (not paid)”. If you checked the order page information you should see that status and the first status is “Awaiting Mollie payment” and the second is set to “On backorder (not paid)”.

![image](https://user-images.githubusercontent.com/29095235/126628601-601f9a09-f5ab-4b18-a861-8ae94ddce5bf.png)

And this is how the module works, we create an order before the customer finalizes it. So that means if the customer finishes all checkout steps and gets redirected to the Mollie payment page the order in PrestaShop is already created and by the customer's actions we change that order's status via webhooks.

Best Regards,
Invertus Support Team

**Comment by AnatoleRozan** [comment]
Hello @SimonasB88,

Thank you for your quick reply. Ok, I understand the process, it makes sense.
But I guess you've specified the "On backorder (not paid) status" for the opened orders in the Mollie plugin configuration.

But what would be the behavior for an in stock product? Would it apply the "On backorder (not paid)" status which is reserved for out of stock products?

Ps : I think it is not really a great idea to use a status which consider the payement as accepted and do a sort of refund action at the end if the customer doesn't finalize the payement. What do you think? Sorry, I really want to have the best plugin which follows the Prestashop guidelines.

Thanks for your support,

Anatole.

**Comment by AnatoleRozan** [comment]
Ok, I think we're not talking about the same status. Have you made your own one? Or is it the default one?

**Comment by SimonasB88** [comment]
Hi @AnatoleRozan ,
No, we do not set "On backorder (not paid)" status. It is set via PrestaShop it’s a default order status when creating an order with "out of stock" products. 
The "On backorder (not paid)" status should be only set when an order is being created with "out of stock" products.
"On backorder (not paid)" doesn’t mean that payment is accepted, is means that in order there are out of stock products, and it is not paid. When order is paid, order status is being set to "On backorder (paid)". 
If you're asking about "On backorder (not paid)"  and "On backorder (paid)"  statuses they are default PrestaShop statuses.
And our recommendation would be to set default Mollie configuration status for opened orders “Awaiting mollie payment”.

Best Regards,
Invertus Support Team

**Comment by AnatoleRozan** [comment]
Everything is clear now. Thank you for your time. You can close the issue :)

**Comment by Saimis777** [comment]
Hey @AnatoleRozan ,

Thanks for the clarification!

Marking the issue as resolved, let us know if you need further assistance!

-
Best regards,
Invertus Support team
