### ISSUE TITLE
Only one status for 2 type of completed orders (with the "accept orders for out of stock products")

### ISSUE THREAD

**Issue by AnatoleRozan** [mollie/PrestaShop#381]
### Expected behavior
When you enable the option "accept orders for out of stock products", you have 2 type of orders :
• In stock product order => After the payement you have the status : "Payement accepted"
• Out of stock product order => After the payement you have the status : "On backorder (paid)"

But in Mollie plugin configuration, you can specify only one status for the validate order.

And if I ignore the status, it will keep on the "Awaiting Mollie payement" status.

### Actual behavior

If I apply the default status "Payement accepted" for paid orders in Mollie plugin configuration, then for an out of stock product order you will apply the wrong status. (Payement accepted instead of On backorder (paid))

### Steps to reproduce the behavior
1. Apply the default status "Payement accepted" for paid orders in Mollie plugin configuration.
2. Make an order of an out of stock product
3. You will have the "Payement accepted" status instead of "On backorder (paid)" status.

You should let Prestashop default functionality for paid orders.
For example it is the case of Paypal plugin. 

### Environment
* PrestaShop version: 1.7.7.4
* Mollie module version: 4.3.2
* PHP version: 7.2.34

**Comment by SimonasB88** [comment]
Hello @AnatoleRozan 
Thanks for your message, the ticket is assigned for our developers.

I will update you about the investigation status.

Best Regards
Invertus Support Team

**Comment by AnatoleRozan** [comment]
Hello @SimonasB88,

Thank you !

Best regards,

Anatole.

**Comment by SimonasB88** [comment]
Hello @AnatoleRozan

Reproduced this issue only this way:
- Set product stock to 0.
- Buy the product
- Product quantity becomes -1
- And status is set to “Payment accepted”

![image](https://user-images.githubusercontent.com/29095235/126791042-d59089bb-cf06-4dd6-9989-ec3ebe7db26a.png)

When buying a product that has less than zero products, for example -1 the status is being set to “On backorder (paid)”

Fixed the issue when buying products that have 0qty to set order status to “On backorder (paid)”. And this will be released in next upcoming version.

Best Regards,
Invertus Support Team

**Comment by AnatoleRozan** [comment]
@SimonasB88 I validate the issue of your previous message.

It is working when stock is < 0.
It is also working when the stock is > 0.
But it doesn't work properly for stock at 0.

Do you have any release date for the patch? We planned to launch our new website version on mid-august.

Best regards,

Anatole.

**Comment by Saimis777** [comment]
Hi @AnatoleRozan  ,

Thank you for your message!

We will check with the team regarding the fix, and let you know!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @AnatoleRozan  ,

I've clarified with the team regarding this case, the fix was implemented, and merged, and will be in the next release!

I will notify you immediately once the new release will be out!

Thank you for your patience!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @AnatoleRozan ,

The new release is now out - https://github.com/mollie/PrestaShop/releases/tag/4.3.3

As I've mentioned before the issue now is resolved, and you can download the new version!

For now I will mark this issue as resolved, if you will need further help, let me know, and we will re-open the issue!

--
Best regards,
Invertus Support team
