### ISSUE TITLE
Order not set in outofstock if a product is out of stock

### ISSUE THREAD

**Issue by jcvoyeux** [mollie/PrestaShop#382]
### Expected behavior
When an order with a product in out of stock is created and paid with Mollie, the order should set "Payment accepted" then "outofstock".

### Actual behavior
The order stays "Payment accepted". It doesn't become "outofstock".

### Steps to reproduce the behavior
The operation runed well in 1.7.4 and Mollie 4.2
We just have upraded to 1.7.7.3 and we use now Mollie 4.3.2

### Environment
* PrestaShop version: 1.7.7.3
* Mollie module version: 4.3.2 
* PHP version: 7.3.29
 
![outofstock](https://user-images.githubusercontent.com/48982383/126748075-c7e29452-9017-4e1e-8e76-f23dc6e40d90.JPG)

**Comment by SimonasB88** [comment]
Hello @jcvoyeux 
Thanks for your message, the ticket is assigned for our developers.

I will update you about the investigation status.

Best Regards
Invertus Support Team

**Comment by SimonasB88** [comment]
Hi @jcvoyeux 

It seems from your order photo that you have ordered the last product, that's why the order is set to “Payment accepted”.

And when an order is made when the products' quantity is 0 or less than zero, the order status is being set to “On backorder (not paid)” or “On backorder (paid)” depending on if it is paid or not.

![image](https://user-images.githubusercontent.com/29095235/126756896-ddc27093-448d-4457-920e-ec8a0f27dec8.png)

Best Regards
Invertus Support Team

**Comment by jcvoyeux** [comment]
Hello @SimonasB88 
How do you see the product was in stock ? 0 in disponible ?

**Comment by jcvoyeux** [comment]
You are rigth my sample is not good.
Here an other case.
SO0168 is available
SO01653 is not available.
Order stayed in
![outofstock2](https://user-images.githubusercontent.com/48982383/126777377-c96b49c9-bd29-4d87-bcf3-e5f8f7816313.JPG)
 "Payment accepted"

**Comment by SimonasB88** [comment]
Hi @jcvoyeux 

As we see that both products have the quantity available  0 could it be that both products were last in stock?
By the way, could it be similar to your case when there is 0 product in stock and the product is bought then it will be payment accepted? If there is less than zero, for example -1 it sets correct status “On backorder (paid)”?

Best Regards,
Invertus Support Team

**Comment by jcvoyeux** [comment]
Hello,
First, thank you for trying to help me.
I must tell you that our prestashop is filled by our ERP (with API), this is why the stock comes back to 0.
In fact, each time we touch the stock of the ERP, the stock of PS is automaticly synchronized (because we have also a true shop).
I'm sure the stock was 0 before the order (99,9%).
When an order is inserted, a mail is sent to our webshop manager.
Stock became -1 (but status stayed "Payment accepted").
The manager verifies in the backoffice if the order is OK then inserts it in our ERP.
Stock in the ERP becomes : stock=0, requested=1.
This change is sent to prestashop so this is why you see available 0 and not -1. This change is made a long moment after the creation of the order (few hours) so status should have been "outofstock" (because it is done after few seconds).
Like I told you, it worked fine with 1.7.4.4 and mollie 4.1.3.
It doens't work anymore seens the update to 1.7.7.3 and mollie 4.3.2.
We have keep the old config (in case of emergency). I verified the orders and fortunetly there was an old order in "outofstock" !
You can see that stock was 0 and the status is however correct.
Could you verify ?
I'm going to ask to manager not to trait next case before I verify and take a printscreen of its status to show you.
![outofstock3](https://user-images.githubusercontent.com/48982383/126810962-0b802d2d-6ff2-4f3c-b4b3-807eead564b0.JPG)

**Comment by Saimis777** [comment]
Hi @jcvoyeux ,

Thank you for the further details, we will check with the team, and let you know!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @jcvoyeux ,

I've clarified with the team regarding this case, the fix was implemented, and merged, and will be in the next release!

I will notify you immediately once the new release will be out!

Thank you for your patience!

--
Best regards,
Invertus Support team

**Comment by jcvoyeux** [comment]
Super.
I'm waiting your signal to update the module.

Thank you.

________________________________
De : Saimis777 ***@***.***>
Envoyé : mardi 27 juillet 2021 13:13
À : mollie/PrestaShop ***@***.***>
Cc : jcvoyeux ***@***.***>; Mention ***@***.***>
Objet : Re: [mollie/PrestaShop] Order not set in outofstock if a product is out of stock (#382)


Hey @jcvoyeux<https://github.com/jcvoyeux> ,

I've clarified with the team regarding this case, the fix was implemented, and merged, and will be in the next release!

I will notify you immediately once the new release will be out!

Thank you for your patience!

--
Best regards,
Invertus Support team

**Comment by jcvoyeux** [comment]
Hello Saimis777,
I don't know when you make the test of the stock.
It should be :
If (qte_dispo_before_the_order - qte_in_order < 0) -> out_of_order
or
If (qte_dispo_after_the_order < 0) -> out_of_order

If you have 2 in stock and the customer order 3, there is a problem !

Have a nice day.

JC

**Comment by Saimis777** [comment]
Hey @jcvoyeux ,

The 4.3.3 release was made today, it should no longer contain this issue, a simple test case was made for this case in the latest release:

Product has 2qty. 
customer orders 3 products.

Order is being set to “On backorder (paid)”.

You can download the latest version here - https://github.com/mollie/PrestaShop/releases/tag/4.3.3

For now I will mark this issue as resolved, if you will still encounter the issue, let me know, and we will re-open the issue!

--
Best regards,
Invertus Support team
