### ISSUE TITLE
Order reference not in sync with order ID

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop#388]
### Expected behavior
Order reference should have the same number as Order ID
![afbeelding](https://user-images.githubusercontent.com/49270150/127990498-56dc80cd-8b5a-4492-9291-a1060c9847fa.png)

### Actual behavior
Order reference has an different number after updating than order ID

### Steps to reproduce the behavior
Upgrade mollie to the latest version.

### Environment
Prestashop 1.7.7.5
* Mollie module version: 4.3.2
* PHP version: 7.2.34

**Comment by Saimis777** [comment]
Hello @Maikel726 ,

The Order reference and Order ID should not be the same according to the module, they are generated randomly, unless there is some custom logic in your shop to make them the same? If yes, we would need your credentials sent to - support@invertus.eu for further investigation.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Maikel726** [comment]
Hello,

We used custom code in order.php but that doesn't work anymore.

**Comment by Saimis777** [comment]
Hey @Maikel726 ,

In that case we would need your BO + FTP credentials to investigate further, as from the given information no relevant changes or suggestions could be made. If possible, please send them to - support@invertus.eu for further investigation!

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @Maikel726 ,

As we've discussed this topic via email, should we close this issue for now?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Maikel726** [comment]
Hi,

You can close this topic for now.
