### ISSUE TITLE
SENTRY_ENV

### ISSUE THREAD

**Issue by kairnejeff** [mollie/PrestaShop#389]
### Environment
* PrestaShop version: 1.7.7.2 
* Mollie module version: 4.3.2 
* PHP version: 7.2.34 

hello i have a greate problem when i activate the debug mode inPrestashop, your module bloque our site. Even when enable le debug mode, i cant see my orders in my BO. it gave me a sql eror

Thank u for ur help

![image](https://user-images.githubusercontent.com/74318908/128042650-f6122407-5e51-45e9-af4e-c3af4c547426.png)

**Comment by Saimis777** [comment]
Hello @kairnejeff ,

Was the module downloaded from addons marketplace?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by kairnejeff** [comment]
yes we have juste done a update, so i come back to the version 4.3.1 and everthing is ok now.

**Comment by Saimis777** [comment]
Hey @kairnejeff ,

Have you tried downloading the latest version from GitHub (4.3.2)? As it should have no issues, since there were no similar ones reported since the release in GitHub.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @kairnejeff ,

Do you need any further assistance regarding this case?

Let us know!

--
Best regards,
Invertus Support team

**Comment by kairnejeff** [comment]
Hello

Thanks very much

We dont need anymore. We have returned to the version 4.3.1 and everything
is fine now

Yours,

**Comment by kairnejeff** [comment]
ps: I think to download the verison from github is also a good solution but
i haven't tried it.

**Comment by Saimis777** [comment]
Hi @kairnejeff ,

Thank you for your reply.

I will mark the issue as resolved for now, let me know if you'll need further help!

Be sure to checkout the latest version 4.3.3 which was released yesterday - https://github.com/mollie/PrestaShop/releases/tag/4.3.3

--
Best regards,
Invertus Support team
