### ISSUE TITLE
Enable/disable payment methods per product category and/or min/max cart price

### ISSUE THREAD

**Issue by Spiros333** [mollie/PrestaShop#391]
### Expected behavior
 1. I really want to be able to enable and disable the payment methods every category.
    SO that for example to have the choice for paypal to disable it for the category "wholesales".

2. I want to be able to put every payment methode an Min and/or an Max totaal price.
SO for example klarna is only available above the 100euro.
And Paypal is not available above the 900euro as example.

Could you give us in the plugin multiple option possibilities were we could decide the control of the payment methods our selfs?

Please let me know...

### Actual behavior

Its not existing yet

### Environment
* PrestaShop version: 1.7.6.2
* Mollie module version: 3.3.4 
* PHP version: 7.1.2

**Comment by Saimis777** [comment]
Hi,

Thank you for the request, we will check if it's possible, and if we can do such changes, and will inform you!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @Spiros333 ,

Just wanted to inform you that this request as clarified per Mollie is postponed for now, it might be coded and added in the future, for now, I'm adding the label "Wishlist", and I will update you once it will be approved and added.

Have a nice day.

--
Best regards,
Invertus Support team

**Comment by Spiros333** [comment]
Okay thanks

**Comment by Saimis777** [comment]
Hi,

This ticket is listed in the inner board of Invertus-Mollie as a future feature.

Once it's out, I will notify you.

For now I will mark this as closed, to keep the cases that are solved at the moment.

--
Best regards,
Invertus Support team
