### ISSUE TITLE
The locale is invalid.

### ISSUE THREAD

**Issue by Shoprunners** [mollie/PrestaShop#393]
### Expected behavior
Payment methods are shown in checkout

### Actual behavior
No payment methods are shown in checkout

### Steps to reproduce the behavior
not sure

### Environment
* PrestaShop version: 1.7.6.9 
* Mollie module version: 4.3.3
* PHP version: 7.3.

Looking in the logs of PS, I can find this:
_

> Exception on hook paymentOptions for module . [2021-08-09T09:08:22+0200] Error executing API call (400: Bad Request): The locale is invalid. Documentation: https://docs.mollie.com/overview/handling-errors. Field: locale

_

adding some "stacktrace": this gets thrown in mollie.php "hookPaymentOptions" when calling

$methods = $paymentMethodService->getMethodsForCheckout();

both settings: browser and shop locales produce same error.

**Comment by SimonasB88** [comment]
Hello @Shoprunners 

Thanks for the feedback. Please check the information here in repo WIKI https://github.com/mollie/PrestaShop/wiki/Known-Issues#locale-is-invalid, and please try to configure your Prestashop as follows and let us know the feedback here.

Best Regards,
Invertus Support Team

**Comment by Saimis777** [comment]
Hello @Shoprunners ,

Did the WIKI article help? Do you need any further assistance?

Let us know!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

Due to inactivity I am closing this issue for now.

Let us know if you need any further assistance!

--
Best regards,
Invertus Support team
