### ISSUE TITLE
Klarna (Afterpay) reopen order after being expired

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop#394]
### Expected behavior
Order should remain closed after Klarna's invoice has expired.

### Actual behavior
Webhook call from Mollie changes the status from "Cancelled" to Backorder (Paid), see screenshots.

### Steps to reproduce the behavior
Create order with Klarna payment and let the invoice expire, takes around 14 days i think.

### Environment
* PrestaShop version: 1.7.76
* Mollie module version: 4.3.3
* PHP version:  7.2.34

![mollie-api-call](https://user-images.githubusercontent.com/49270150/130581832-cee6ec88-28e5-47fa-9e26-abc408456ac9.JPG)

![prestashop-api-call](https://user-images.githubusercontent.com/49270150/130581835-7134f7dc-9117-413e-9a06-66150c91b414.JPG)

**Comment by Saimis777** [comment]
Hi @Maikel726 ,

Thanks for your message!

Did you cancel it manually? Nevertheless, the next Mollie release will contain an update where the orders will only be created after a payment is done, so this issue will not exist anymore.

--
Best regards,
Invertus Support team

**Comment by Maikel726** [comment]
Hi,

Did not cancel it manually the webhook call from Mollie did that, at 17:50 the status was changed to "Expired" in Mollie and also at the exact time the order changed to Backorder (paid) in Prestashop.

**Comment by Saimis777** [comment]
Hi @Maikel726 ,

I would suggest waiting for 4.4.0 release, in this next release the issue will no longer be valid.

Would that work for you?

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @Maikel726 ,

The new beta version of the module is now released! You can download it here - https://github.com/mollie/PrestaShop/releases

The new update has been implemented - order creation after payment which should resolve your case, let us know with any feedback you'll have regarding the new update!

I will mark the issue as resolved for now, let us know if you need any help, we can reopen the issue if needed!

--
Best regards,
Invertus Support team
