### ISSUE TITLE
Error on payment module kills ALL payment modules

### ISSUE THREAD

**Issue by Ashley-Butcher** [mollie/PrestaShop#395]
### Expected behavior
If the Mollie module encounters an error, it should gracefully shut itself down, not kill all other payment modules (paypal/stripe/etc).

### Actual behavior
If Mollie module encounters an error, the customer sees the error message explaining that no payment methods are availabble, even if multiple payment methods are configured along side Mollie

### Steps to reproduce the behavior
 - Ensure multiple payment methods are available, served by multiple payment method modules
 - Induce an API error, for example a locale error - change a language code to be "nl" instead of "nl-nl" 
 - Result: No payment methods available, including the non-Mollie methods

### Environment
* PrestaShop version: 1.7.7.7
* Mollie module version: 4.3.3
* PHP version: 7.3.29-1

--------

Specifically today we noticed that payments were not working for language codes FR and DE - we never changed these, so this must be a legacy from Prestashop defaults (it is debatable whether the Mollie Module should automatically take a language code of "fr" and just make it "fr-fr" for example, but that's another topic...)

The error we received in the logs was:
Exception on hook paymentOptions for module . [2021-08-26T09:45:08+0200] Error executing API call (400: Bad Request): The locale is invalid. Documentation: https://docs.mollie.com/overview/handling-errors. Field: locale

However, we use Stripe for credit card payments, PayPal for PayPal directly, etc. and this issue caused ALL payment methods to become unavailable, not just Mollie. That's a bit rude :) So I think it would be better if the Mollie module was more graceful and just removed itself in the event of an error.

**Comment by toyoted** [comment]
Hey,

We got same log error and same behaviour (killing all other payment) we are unable to use Mollie again on our new Prestashop upgrade 1.7.7.5

PS : 1.7.7.5
Mollie : 4.3.3

Log error : Exception on hook paymentOptions for module . [2021-08-31T09:41:13+0200] Error executing API call (400: Bad Request): The locale is invalid. Documentation: https://docs.mollie.com/overview/handling-errors. Field: locale

We hope you'll have a fix soon ?

**Comment by Ashley-Butcher** [comment]
Hi @toyoted,

I posted the bug report (I'm not the dev) - we resolved the "locale is invalid" in our shop by changing the language code to ensure they were in the format of xx-yy (language + variant) instead of xx (just the language code). For example, we had to rename "fr" to "fr-fr" and "de" to "de-de" in internationalisation settings.

See more in issue #393 (specifically https://github.com/mollie/PrestaShop/wiki/Known-Issues#locale-is-invalid).

I hope you manage to get back up and running quickly :)

 - Ash

**Comment by Saimis777** [comment]
Hey @Ashley-Butcher ,

So if I understood correctly, as you've fixed the locale is invalid error, the killing of the other modules does not appear? Is that correct?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Ashley-Butcher** [comment]
Hi @Saimis777

Yes, correcting the locale error allows the Mollie module to work correctly, however it does not solve the problem, it only solves a symptom.

To be clear: the problem is that the error killed *all* payment modules - that's not cool. If something is wrong with the Mollie module, then it should disable itself and not all payment modules. This is the problem I am reporting.

We encountered the problem because of the locale error, but the problem is still valid. For example, if for whatever reason Mollie's server returns a 4xx error (i.e. maintenance or other technical fault) then the Mollie module will probably also then kill all other payment methods on our shop. 

That's unacceptable to us, and we think that should the module fail, it should do so gracefully - the failure of the module or Mollie's API should be isolated.

Thanks,

 - Ashley

**Comment by Saimis777** [comment]
Hey @Ashley-Butcher ,

Thank you for the detailed information!

Just one more thing, maybe you could clarify in your case which other payment modules you have installed? I see you have Stripe/PayPal, any others? Does it kill for you the default payment methods as well? Or the default ones stay?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @Ashley-Butcher ,

We've managed to find the issue, and we will add it in the next release. If you doesn’t want to wait for the release you can add this fix by simply changing this:

PaymentMethodServices.php: line 190


$mollieMethods = $this->getSupportedMollieMethods();
->
try {
    $mollieMethods = $this->getSupportedMollieMethods();
} catch (\Exception $e) {
    return [];
}

Let us know if you have any other questions or if we can resolve the issue!

--
Best regards,
Invertus Support team

**Comment by Ashley-Butcher** [comment]
Hey #Saimis777,

Sorry for the delay in getting back to you but this is perfect! Thank you for your help, and for the patch :)

Kind regards,

 - Ashley

**Comment by Ashley-Butcher** [comment]
Follow-up for anyone who is wanting to apply the patch, the code to edit listed above is actually in the file src/Service/PaymentMethodService.php in the function getMethodsForCheckout()

**Comment by Saimis777** [comment]
Hey @Ashley-Butcher  ,

The new beta version of the module is now released! You can download it here - https://github.com/mollie/PrestaShop/releases

We've added the tolerance for other payment methods if Mollie API is not responsive on the checkout page. Also, the new order creation logic is now out in the latest release, let us know with any feedback you'll have regarding the new update!

I will mark the issue as resolved for now, let us know if you need any help, we can reopen the issue if needed!

--
Best regards,
Invertus Support team
