### ISSUE TITLE
3-4 times cancel klarna order before 1 approves and confirms

### ISSUE THREAD

**Issue by Spiros333** [mollie/PrestaShop#396]
Ive placed an paylater order, completed and confirmed. order JQLODFJNP #7798
I try again to place with the same account an order and now the system is seeing me as "Test test" and not by the name I have placed minuts ago an confirmed order and approved by klarna.

Something is not working correctly with the paylater.

It took 3-4 canceld order before it reqognized my current name,

### Environment
* PrestaShop version: 1.7.6.2
* Mollie module version: 4.3.3 
* PHP version: 7.2

**Comment by folkertsmit** [comment]
I experience the same

![Knipsel](https://user-images.githubusercontent.com/28303275/131255655-2a2c75dc-a501-4308-b1b8-bdd1733d229e.JPG)

**Comment by Saimis777** [comment]
Hello,

Thank you for the additional information!

We are currently looking in to this issue, and I will get back to you ASAP!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @Spiros333  ,

The new beta version of the module is now released! You can download it here - https://github.com/mollie/PrestaShop/releases

The new update has been implemented - order creation after payment which should resolve your case, let us know with any feedback you'll have regarding the new update!

I will mark the issue as resolved for now, let us know if you need any help, we can reopen the issue if needed!

--
Best regards,
Invertus Support team
