### ISSUE TITLE
Awaiting for mollie payment, but no payment link to mollie

### ISSUE THREAD

**Issue by wzzly** [mollie/PrestaShop#397]
### Expected behavior
When something goes wrong when a customer wants to pay with mollie (iDeal), there should be an option to resend the payment link. Some orders don't have this option.

### Actual behavior
Some customers report that they lose the order when wanting to pay with mollie. They get a blank screen and nothing happens. The order is created by prestashop in the BO with the status "awaiting for mollie payment", but when you enter the order in BO, there is no mollie section and option to resend the playment link (like ususal).

### Steps to reproduce the behavior
It doesn't happen with overy order. What could be the problem?

### Environment
* PrestaShop version: 1.7.7.5
* Mollie module version: 3.3.4 
* PHP version: 7.3
![image](https://user-images.githubusercontent.com/35727938/131250612-a9e1a939-116c-456a-8cb0-9800df35fa15.png)

**Comment by Saimis777** [comment]
Hi @wzzly ,

Thank you for your message!

To check this issue out, we would need BO + FTP logins, as from the current information it seems that the orders are not getting mapped. Could you send your credentials to - support@invertu.eu (do not reply to this message via GitHub with the credentials) so we could check this further?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @wzzly ,

Thank you for your patience!

After next release we will only create order when payment is paid. So there won't be any issues when order is created before payment is completed. This will be 4.4.0 release, and it will be released very soon, you can find the latest releases here - https://github.com/mollie/PrestaShop/releases

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
@Saimis777 Thanks for your message.
This will be a good step forward I think. But do you know why some payments fail? So not the payments itself, but I get reports from SOME customers that when they confirm the order/payment method, they get a blank screen and the order is gone. That's why their order is then automatically canceled.

**Comment by Saimis777** [comment]
Hi @wzzly ,

Hard to tell without any screenshots, need further information on such cases, as we did not encounter this before, could be that the payment itself sometimes also fails, not the module, though that might not be the case.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @wzzly ,

The new beta version of the module is now released! You can download it here - https://github.com/mollie/PrestaShop/releases

The new update has been implemented - order creation after payment which should resolve your case, let us know with any feedback you'll have regarding the new update!

I will mark the issue as resolved for now, let us know if you need any help, we can reopen the issue if needed!

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
@Saimis777 Today I have another report from a client that get an error when they want to pay the order:

•	Er is een fout opgetreden terwijl u uw betaling initialiseert Neem contact op met onze klantenservice.
arrow_back Terug naar uw winkelwagentje 

translation:
An error occurred while initializing your payment Please contact our customer service.
arrow_back Back to your shopping cart

**Comment by Saimis777** [comment]
Hey @wzzly ,

Thank you for reporting that!

Could you clarify if it's an issue on the same shop as you've previously sent credentials to?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
@Saimis777 yes it's the same shop.
Below the customer and his cart with the error.
customer ID = 40
cart ID = 001003

**Comment by Saimis777** [comment]
Hey @wzzly ,

Looks like the Mollie API returned this error and not the module itself, maybe you can find more information in Mollie – Effortless payments next to created order history?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Also,

I would like to note that Mollie had an incident, which might also be related to this issue.

You can track Mollie status for more information here - https://status.mollie.com/

Let us know if you'll encounter the issue once more, and please if you will, maybe you could raise a new issue regarding it, so it would be crystal clear which issue we are?

Thank you!

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
@Saimis777 thanks, yes maybe it was the incident Mollie had. You can close this and I will let you know if it happens again in a new issue.
