### ISSUE TITLE
Status of payed order that has quantity 1 is set on Backorder payed.

### ISSUE THREAD

**Issue by folkertsmit** [mollie/PrestaShop#398]
### Expected behavior
Status Payed

### Actual behavior
Status backorder payed

### Steps to reproduce the behavior
Since last update all incoming order where the stock of the product is 1 (or lower of course) the status of this order is set on status backorder payed.

### Environment
* PrestaShop version: 1.7.4.3
* Mollie module version: 3.3.4 
* PHP : 7.1.33

**Comment by Saimis777** [comment]
Hi @folkertsmit ,

Thank you for your message, we've received information about this case, and currently working on a fix, we will keep you posted regarding the progress!

Thank you for your collaboration!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

Thank you for your patience!

We've resolved the issue, made that even if products are with quantity as 1 will not be put on backorder paid, the fix will be included in the 4.4.0 release, which will be released very soon! You can see the latest releases here - https://github.com/mollie/PrestaShop/releases

--
Best regards,
Invertus Support team

**Comment by folkertsmit** [comment]
Great thanks!

Met vriendelijke groet,

Folkert Smit


Op do 2 sep. 2021 om 10:26 schreef Saimis777 ***@***.***>:

**Comment by folkertsmit** [comment]
Hi do you know when? 5 days later now :)
Met vriendelijke groet,

Folkert Smit


Op do 2 sep. 2021 om 10:26 schreef Saimis777 ***@***.***>:

**Comment by Saimis777** [comment]
Hey @folkertsmit ,

We're aiming to release it this month, can't give you an exact date, since with the releases there might be unforeseen step backs, but we'll do our best to release it ASAP!

Thank you for your patience.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @folkertsmit ,

The new beta version of the module is now released! You can download it here - https://github.com/mollie/PrestaShop/releases

We fixed the issue with backorder - Transaction status will be PAID when product quantity is 1 or more.

I will mark the issue as resolved for now, let us know if you need any help, we can reopen the issue if needed!

--
Best regards,
Invertus Support team
