### ISSUE TITLE
Apple Pay doesn't show up in the Checkout Page

### ISSUE THREAD

**Issue by DK-Tugce** [mollie/PrestaShop#399]
### Expected behavior
After activating Apple Pay on the Prestashop module, it should show up on the checkout page

### Actual behavior
Apple pay looks activated on the Prestashop Module but it doesn't show up on the checkout. In the payment settings every country is selected for Mollie. 

Mollie Module Settings:
![Screenshot 2021-08-30 at 16-10-24 Module Manager • OssyHomer](https://user-images.githubusercontent.com/89790367/131354389-f01b837c-d8b9-42e4-902a-8f8c3d85c0d3.png)
![Screenshot 2021-08-30 at 16-21-50 Module Manager • OssyHomer](https://user-images.githubusercontent.com/89790367/131354390-de4133a7-838c-4359-a045-bf178a43f549.png)

Checkout View
![Screenshot 2021-08-30 at 16-22-00 OssyHomer](https://user-images.githubusercontent.com/89790367/131354427-087de845-cf82-40e0-a4fb-54280a54d448.png)

### Environment
* PrestaShop version: 1.7.7.0
* Mollie module version: 4.3.3
* PHP version: 7.3

**Comment by Saimis777** [comment]
Hello,

Thank you for your message!

Have you tried going through the troubleshooting tab and checked the possible solutions there for this issue? You can find them here- https://github.com/mollie/PrestaShop/wiki/Troubleshooting#payment-method-does-not-appear-in-front-office

Let me know once you've tried them and if it still does not show up!

--
Best regards,
Invertus Support team

**Comment by DK-Tugce** [comment]
Hi,
It is fixed thank you.

Best regards,
Tugce

**Comment by Saimis777** [comment]
No problem!

Let us know if you need any further help!

--
Best regards,
Invertus Support team
