### ISSUE TITLE
Mollie module giving errors

### ISSUE THREAD

**Issue by loetje88** [mollie/PrestaShop#40]
Since a couple of days, the module is only giving errors, which resulting in being unable to reach the site and change the payment status.
Customers  dont recieve any info, not knowing if the payment was succesfull, or recieving an error the paymant has failed, but actually not failed since i recieve them and payment is done.

Also module will not update, followd the instructions, installed again, but still listing as version 1.3 while files from the new update are on the server.

**Comment by loetje88** [comment]
Also same errors as listed below, saying the API is not right( it is) or that the cart has already been used.

The first store never had any issues with returning the cart status. But the second now doesn't get some things work. I am using Mollie payment module. ( https://github.com/mollie/Prestashop ). The shop is NOT in maintenance mode during the tests.

Order is correctly handled -> Payment is accepted in the order screen (only sometimes, most of them fail to show this) 
Customer gets screen with 'no final payment status'
Customer gets NO e-mail of confirmation.
SSL is enabled.

The error in the log is the following:
" Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart "

**Comment by Trendweb** [comment]
Hi @loetje88 ,

We are Mollie's prestashop partner and we also provide support for Prestashop. Could you please contact us at info@trendweb.nl so we can provide you with a sollution?

Regards

**Comment by loetje88** [comment]
Hi trendweb!

just replied by mail :)

regards
