### ISSUE TITLE
test mode of the Mollie module stuck in loading screen

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop#404]
### Expected behavior
In test modus with Ideal payment you can choose between the status options: open, paid, failed, cancel and expired. If you choose for example status "open" the order should be created in Prestashop with status "open"

### Actual behavior

The order gets stuck on the loading screen and the order isnt created in Prestashop. Note that this is with every status option except with "paid"

### Steps to reproduce the behavior
Put the module in test modus and add a product into the shopping cart and go try to check out. Choose for example ideal and continue and when you are on the page that ask which status to assign to the test order, choose any status you want except paid.

### Environment
Prestashop: 1.7.7.8
* Mollie module version: v4.4.0
* PHP version: 7.3.30

**Comment by Saimis777** [comment]
Hi @Maikel726 ,

Thank you for raising the issue.

We're checking the provided steps now, and I will get back to you ASAP!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @Maikel726 ,

Just informing you that we are still working on the case, I am waiting for further clarifications.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @Maikel726 ,

The new 4.4.1 version with an added new message to ‘open’ status now on test mode is now released. 

You can download the new version here - https://github.com/mollie/PrestaShop/releases

Let us know if everything works as intended, any feedback is appreciated!

--
Best regards,
Invertus Support team
