### ISSUE TITLE
bigger issue now with klarna no order is been created

### ISSUE THREAD

**Issue by Spiros333** [mollie/PrestaShop#409]
klarna authorized are not creating an order in the order page 
![image](https://user-images.githubusercontent.com/85503636/134018242-04383e9e-08c2-4a2d-a024-09ff5ef731a8.png)

### Environment
* PrestaShop version: 1.7.6.2
* Mollie module version: 4..4.0
* PHP version: 7.2

**Comment by Spiros333** [comment]
the issue has become worse then first in #358

**Comment by Saimis777** [comment]
Hi @Spiros333 ,

Thanks for reporting that.

Forwarded information to the team, checking the issue out.

Will keep you posted!

--
Best regards,
Invertus Support team

**Comment by Spiros333** [comment]
TIJUBAUNP #7855 - this order was created by hand because mollie didn't create the order, in the mollie portal the order was klarna authorized
IHFNDWLYV #7856  - this order was created by hand because mollie didn't create the order, in the mollie portal the order was klarna authorized

After the two non working orders, SMZEYJIZK #7857 was created with email confirmation and order on the orderpage.

**Comment by Saimis777** [comment]
Hi @Spiros333 ,

From the error message it looks like there was am issue with the server, and Mollie didn’t got response, maybe it was not able to connect to merchants shops webhook. Our guess that there was an issue with the merchants server but we might be wrong, would need another example to catch the error. Please let us know if this happens again.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Also,

I would like to note that Mollie had an incident, which might also be related to this issue.

You can track Mollie status for more information here - https://status.mollie.com/

Let us know if you'll encounter the issue once more!

--
Best regards,
Invertus Support team

**Comment by Spiros333** [comment]
okay thanks
something als sinds the last days the status don't change automaticly from klarna payment authorized to klarna payment shipped.
I need it to do it by hand, is this something you can fix?

**Comment by Saimis777** [comment]
Hi @Spiros333 ,

So as I understand the issue did not repeat itself, therefore I will mark this issue as resolved.

Regarding Klarna status maybe you could raise a separate issue? And in there provide screenshots from mollie.com if the status there changed to "shipped" and what the history shows.

Thank you!

--
Best regards,
Invertus Support team
