### ISSUE TITLE
Warning: the secure key is empty, check your payment account before validation

### ISSUE THREAD

**Issue by Saimis777** [mollie/PrestaShop#414]
An issue ticket regarding the error: "Warning: the secure key is empty, check your payment account before validation"

**Comment by Spiros333** [comment]
Just make an klarna order.
A customer order is when this appeared, so think my customer just placed an klarna order.
Order: NZEOXBFNF Placed on 22-09-2021
Payment: Pay later. 
And then there it was as customer text in the invoice.

So don't know what you want me to telll you just make an klarna order

**Comment by Spiros333** [comment]
Environment
PrestaShop version: 1.7.6.2
Mollie module version: 4..4.0
PHP version: 7.2

**Comment by Adekonl** [comment]
Cannot reproduce, but potential fix:
modules/mollie/src/Service/TransactionService.php:258
`$customer = new \Customer($cart->id_customer);
$this->module->validateOrder(
            (int) $cartId,
            (int) Configuration::get(Mollie\Config\Config::MOLLIE_STATUS_AWAITING),
            (float) $originalAmount,
            isset(Config::$methods[$apiPayment->method]) ? Config::$methods[$apiPayment->method] : $this->module->name,
            null,
            array(),
            null,
            false,
            $customer->secure_key
        );`

**Comment by AaronTajriba** [comment]
I got exact the same issue with
PrestaShop version: 1.7.6.8
Mollie module version: 4.4.0
PHP version: 7.3

**Comment by Saimis777** [comment]
Hi @Spiros333 , @AaronTajriba ,

The new 4.4.1 version with the fixed issue where order has been created without cart security key and gives warning. 

You can download the new version here - https://github.com/mollie/PrestaShop/releases

Let us know if everything works as intended, any feedback is appreciated!

--
Best regards,
Invertus Support team
