### ISSUE TITLE
Version number of 1.3.1 is 1.3.0

### ISSUE THREAD

**Issue by samverdyck** [mollie/PrestaShop#42]
The version number of 1.3.1 is configured as 1.3.0, which results in an invalid message in the module. 

![1](https://user-images.githubusercontent.com/12470000/32788367-53310240-c959-11e7-8f19-57204aad315f.png)
![2](https://user-images.githubusercontent.com/12470000/32788430-754ec8bc-c959-11e7-95b8-9778a5008464.png)

**Comment by Trendweb** [comment]
Hi @samverdyck ,

Thank you very much for reporting this. We have already fixed this in the upcomming update which will be placed on Github as soon as possible.

Kind Regards
