### ISSUE TITLE
Mollie requires (fr-fr) language code instead of (fr). Breaks PS translations and other modules

### ISSUE THREAD

**Issue by darkstudio** [mollie/PrestaShop#420]
### Expected behavior
A message appears at the last step indicating that no payment method is available
It prevents other payment methods such as paypal and stripe from working
If mollie module is unselected on PAYMENT -> PREFRENCES  :  Restricted curency or Restricted group,  al other module work again.

This issue is not on 4.3.2, its works on 4.3.2 ! The problem is that version 4.3.2 is not usable with the order bug (creation of an order even if payment is refused).
Mollie is disabled for now. we will wait a fix.

### Environment
PrestaShop version: 1.7.6.8
Mollie module version: 4.4.0, 4.3.3
PHP version: 7.1.33
![image](https://user-images.githubusercontent.com/6309663/134880264-1d9218b9-5d0e-42a4-b0c9-bfbdf1c8e1a5.png)

**Comment by Saimis777** [comment]
Hi @darkstudio ,

Maybe you could clarify the process how can we replicate this issue? Should we have PayPal and Stripe installed on the shop? And regarding the restrictions, which restrictions exactly do you enable for Mollie that causes this? Is it unselected completely?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by darkstudio** [comment]
The Stripe and Paypal modules are installed. The mollie module is configured on TEST mode.
No restriction on the means of payment, checked everywhere in the PAYMENT -> PREFRENCES part
I have tried to disable stripe and paypal but no changes.
note: i have just tested version 4.4.1 and its the same. No payment options.

**Comment by Saimis777** [comment]
Hi @darkstudio,

Thanks for the additional information.

We will try to replicate this from our end, and I will let you know how it will go!

--
Best regards,
Invertus Support team

**Comment by CooUoo** [comment]
Hi,

Check your config in BO > International > Localisation > Languages.
The language code must be (in your case) **fr-fr** and not just **fr**.
I had the same problem and solved it like this.

Regards

**Comment by darkstudio** [comment]
> Hi,
> 
> Check your config in BO > International > Localisation > Languages. The language code ("Code de langue" in French) must be (in your case) **fr-fr** and not just **fr**. I had the same problem and solved it like this.
> 
> Regards

It works but it generates a lot of side effects at the translation level ... (problem on title of emails (new order, order confirmation etc) Prestashop does not really like this change after installation / translation.

Regards,

**Comment by CooUoo** [comment]
Yes, I know.
Emails sent by Mollie do not have the translated titles.
I had to mod some files of Mollie module to have the emails titles back in French.
It's because the emails are sent by Mollie and not by the usual PS functions.
But at least, your payment methods are displayed and usable :)

**Comment by darkstudio** [comment]
> Yes, I know. Emails sent by Mollie do not have the translated titles. I had to mod some files of Mollie module to have the emails titles back in French. It's because the emails are sent by Mollie and not by the usual PS functions. But at least, your payment methods are displayed and usable :)
If we use the prestashop interface to translate emails titles, the emails is broked :) modifications must be on template files located on mails forlder of mollie module and template.

**Comment by Saimis777** [comment]
Hi @darkstudio ,

As I understood from the thread, editing the language code from fr to fr-fr resolved your issue, is that correct?

If yes, can we close this issue? 

As for the other issues, could you raise a new issue for those? With details of what actually breaks in your shop after changing the language code? You've mentioned that the email translations that are sent from Mollie the translations get broken?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by darkstudio** [comment]
> Hi @darkstudio ,
> 
> As I understood from the thread, editing the language code from fr to fr-fr resolved your issue, is that correct?
> 
> If yes, can we close this issue?
> 
> As for the other issues, could you raise a new issue for those? With details of what actually breaks in your shop after changing the language code? You've mentioned that the email translations that are sent from Mollie the translations get broken?
> 
> Looking forward to your reply!
> 
> -- Best regards, Invertus Support team

I think that is not normal that mollie module can't work with a fresh installation where language are configured by prestashop directly ;)
Stripe, Paypal and other payment module work with native installation.
Its a workaround  not a fix.

Regards,
Its a workaround but not a

**Comment by Saimis777** [comment]
@darkstudio ,

This is because Mollie's API itself only takes languages codes as example "fr-fr", so if it's only fr, it will not be picked up, resulting in payment methods not being shown.

--
Best regards,
Invertus Support team

**Comment by chrisvanberg** [comment]
Hi, 

I've had the same issue and the solution worked for me.
It could be nice if the module could detect this error and tell us on the module page.

Best regards,

**Comment by AmandaMollie** [comment]
Thanks all for the feedback! I'm remaining this ticket to "Mollie requires (fr-fr) language code instead of (fr). Breaks PS translations and other modules" and we'll see what we can do to handle the fresh installations.

**Comment by Saimis777** [comment]
Hello,

This raised issue is noted in the Mollie-Invertus board, once there will be updates regarding it, I will let you all know.

Closing the issue for now.

--
Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @chrisvanberg @darkstudio ,

I hope that you are doing well!
I wanted to inform you that this issue has been fixed with our latest 5.0.0-beta2 version. You can find it and check it out [here](https://github.com/mollie/PrestaShop1.7/releases/tag/v5.0.0-beta2). 

Let us know if you have any questions or feedback!

Best regards,
Invertus Support team
