### ISSUE TITLE
Error: parameter \"to\" is corrupted

### ISSUE THREAD

**Issue by wzzly** [mollie/PrestaShop#426]
Some customers have reported they can't pay the order with mollie. 
When I look at the logs I see a wierd error, but don't know if it has to do with some customers not being able to pay.
The: Error: parameter \"to\" is corrupted, is logged with every Mollie incoming webhook message

![image](https://user-images.githubusercontent.com/35727938/135904549-74ef15df-4adc-4c23-bb79-eddb16791e66.png)

### Environment
* PrestaShop version: 1.7.7.5
* Mollie module version: 4.4.1
* PHP version: 7.3

**Comment by Saimis777** [comment]
Hi @wzzly ,

Thanks for reporting this!

Which payment method did your users tried that encounter this used? Is it with Bancontact or some other? Or is it with every payment method?

Looking forward to your reply!

--
Best regards,
Invertus Support tea

**Comment by wzzly** [comment]
@Saimis777 yes we still have the error and the new order email from ps_mailalerts isn't sending anymore either. But I think your right. This is probably not related to mollie. You can close this.

**Comment by Saimis777** [comment]
Hey @wzzly ,

Thanks for the clarification.

Marking ticket as resolved.

--
Best regards,
Invertus Support team
