### ISSUE TITLE
Sending payment link expires in 15 minutes (iDeal)

### ISSUE THREAD

**Issue by wzzly** [mollie/PrestaShop#429]
### Expected behavior
Would expect this link to be the same as sending a payment request (which never expires until the customer pays)

### Actual behavior
An e-mail gets send to the customer when creating a order from a shopping cart or when clicking the payment icon on the BO orders page. The problem is that after 15 minutes the order gets canceled, probably because the link expires.

### Steps to reproduce the behavior
Convert a cart into an order in the BO on the carts page. Then check the "Send customer a payment link email" after selecting mollie as the payment method. The order gets created and the order will have the status: "Waiting for mollie payment", but it seems the order gets canceled way to soon because an iDeal payment only stays active for 15 minutes.
In mollie dashboard, you can send someone a payment request, which stays active until it gets used, so it would be beter to send this.

![image](https://user-images.githubusercontent.com/35727938/136265762-aeaedee4-9aac-445c-a477-c66aedcd23d6.png)
![image](https://user-images.githubusercontent.com/35727938/136266022-984aaf99-958c-47f8-8709-8902c9f35f1d.png)

### Environment
* PrestaShop version: 1.7.7.5 
* Mollie module version: 4.4.1 
* PHP version: 7.3

**Comment by Ashley-Butcher** [comment]
Can confirm, we're seeing the same issue.

**Comment by Saimis777** [comment]
Hi community,

This ticket is listed in the inner board of Invertus-Mollie as a future feature.

Once it's out, I will notify you.

For now I will mark this as closed, to keep the cases that are solved at the moment.

--
Best regards,
Invertus Support team
