### ISSUE TITLE
Error after Updating

### ISSUE THREAD

**Issue by waschier-design** [mollie/PrestaShop#431]
Error with payments after Updating to latest Version (4.4.1)

Also Reset of module does not work.
After Reset Payment Methods can not be activated (Error while deleting old payment methods).

Error is caused by missing Tables. (See Screenshot)
After inserting Tables from "src/Install/DatabaseTableInstaller.php" manually via phpmyadmin module starts working again.

![mollie-screenshot-tables](https://user-images.githubusercontent.com/13886105/136343250-15a17271-c1dc-432b-82da-4d9222f1bb46.JPG)

### Environment
* PrestaShop version: 1.7.7.1
* Mollie module version: 4.4.1
* PHP version: 7.3.31

**Comment by Saimis777** [comment]
Hey @waschier-design ,

Thanks for your message!

Maybe you could clarify from with version did you made the update to 4.4.1 please?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by waschier-design** [comment]
We were upgrading 1 shop from Version 4.3.0
Other PrestaShop (same PS Version) was on Mollie Version 3.5.2

Both were upgraded versions from Mollie Module Version 2.0.x
and had problems with upgrading before.

**Comment by Saimis777** [comment]
Hey @waschier-design ,

Since the issue isn't active for some time, I will mark it as resolved.

Let me know if you still encounter any issues, we can re-open the ticket then!

--
Best regards,
Invertus Support team
