### ISSUE TITLE
Wrong description after update mollie

### ISSUE THREAD

**Issue by AaronTajriba** [mollie/PrestaShop#438]
### Expected behavior
When the payment & order is accepted the order should update the Details in the mollie dashboard to the set parameters in the module (this was the case in previous versions.

### Actual behavior
The payment option Details gets correctly added when the payment is started. But when the payment is accepted and the Details gets updated it has only the prestashop order number instead of the custom text.

### Steps to reproduce the behavior
Do a payment on a live version of mollie.

### Environment
    PrestaShop version: 1.7.6
    Mollie module version: 4.4.1
    PHP version: 7.2

**Comment by madevtools** [comment]
Hi! 

Is there any date of the upcoming version, because this problem is difficult for our administration of payments. 

Thank you in advance.

**Comment by Saimis777** [comment]
Hi @madevtools ,

The next release is planned to be out on the 9th of December.

Thank you for your patience.

--
Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @madevtools,

The issue has been resolved in the new release, which is out now, and can be downloaded here - https://github.com/mollie/PrestaShop/releases/tag/4.4.3

Let us know if you have any other questions, and any feedback regarding the release!

--
Best regards,
Invertus Support team
