### ISSUE TITLE
Order set to 'Canceled' after 15 minutes

### ISSUE THREAD

**Issue by madevtools** [mollie/PrestaShop#439]
### Expected behavior
Paid orders are given the 'Order paid' status

### Actual behavior
After the 'Order Paid' status, orders are canceled without any reason after about 15 minutes 
![paid to canceled](https://user-images.githubusercontent.com/92570825/137451821-254ee6b8-ee09-43b3-8305-fcf56cfcfa28.PNG)
![fout](https://user-images.githubusercontent.com/92570825/137451825-500f61b7-ef06-4050-be8f-c7f5f56e6c1b.PNG)

### Environment
* PrestaShop version: 1.7.6.7
* Mollie module version: 4.4.1
* PHP version: 7.3

**Comment by Saimis777** [comment]
Hi,

Due to inactivity, I will mark this issue as resolved.

Let us know if you will have any other questions!

--
Best regards,
Invertus Support team

**Comment by madevtools** [comment]
Hi. We upgraded the module at two webshops and these errors still occur. Always between 10 and 15 minutes after the payment has been done. 
We are obtaining very much complains so we really hope there will be a working solution, because these problems are already here for weeks and this is really a problem for our revenue, customer service and customers. If these problems are not solvable we have to switch to a different payment provider. 
![error_again_mollie](https://user-images.githubusercontent.com/92570825/140610829-819eff75-21c9-4aec-9de7-66c98af57092.jpg)

**Comment by Saimis777** [comment]
Hello,

Due to inactivity for more than 5 days, we are marking ticket as resolved.

Please let us know if further help is needed.

--
Best regards,
Invertus Support team

**Comment by madevtools** [comment]
I just sent you an email

**Comment by Saimis777** [comment]
Hi @madevtools ,

Found out that there was issue in Mollie v4.4.2 where payment API method with custom description would change paid order status if payment got expired. It is fixed on v4.4.3 and uploaded beta version in your shops with this issue resolved.

Let us know if everything is okay!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @madevtools ,

Due to inactivity I will mark this issue as closed.

Let us know if you have any other questions!

--
Best regards,
Invertus Support team
