### ISSUE TITLE
mollie_return.tpl should extend page.tpl in PrestaShop 1.7

### ISSUE THREAD

**Issue by muyncky** [mollie/PrestaShop#44]
Hi,

When returning to the result page the customers sees a blank page. In PrestaShop 1.7 the page.tpl layout should be extended, like so:
```
{extends file='page.tpl'}
{block name='page_content'}
	<h2>{l s='Welcome back' mod='mollie'}</h2>
	<p>{$msg_details|escape:'htmlall':'UTF-8'}</p>
	<a class="btn btn-default" href="{$link->getPageLink('index', true)|escape:'htmlall':'UTF-8'}">
	  <i class="icon icon-chevron-left"></i> {l s='Continue shopping' mod='mollie'}
	</a>
{/block}
```

It is then necessary to create separate templates for 1.6 and 1.7.

Thanks in advance for an update.

**Comment by snowycatsoftware** [comment]
Hi @muyncky,

Thank you for taking the time to report the issue and you are right. We will provide an update as soon as possible!

Kind regards,

Snowy Cat Software

**Comment by muyncky** [comment]
Hi @snowycatsoftware,

It it possible to contribute to this module?

**Comment by snowycatsoftware** [comment]
Hi @muyncky,

We are always open to suggestions by users or other developers. If you have an idea for improvements, you can always contact us by email.

Kind regards,

Snowy Cat Software

**Comment by snowycatsoftware** [comment]
Hi @muyncky,

We just released a new version of the Mollie module with a fix for this issue. Thank you again for notifying us about this problem!

Kind regards,

Snowy Cat Software
