### ISSUE TITLE
 "resend payment link" icons are gone as well in the BO orders page

### ISSUE THREAD

**Issue by wzzly** [mollie/PrestaShop#449]
### Expected behavior
When customer uses mollie to pay the order and the order is paid, the total should be the total of all orders placed by the customer.

### Actual behavior
When I check the ps_orders table, all orders paid with mollie have the total_paid_real set to 0. This should be the amout of the order?
When I place a test order with another payment option (pay later by invoice) and set the order status to paid manually in the BO, the total_paid_real IS set to the order total amount (€118,92)
![image](https://user-images.githubusercontent.com/35727938/138471830-16d1118c-c9ff-4c95-87ac-ccdc9579da7d.png)
![image](https://user-images.githubusercontent.com/35727938/138472409-b3e370d2-81b4-4a60-b777-0cfba2d8b71a.png)

### Steps to reproduce the behavior
When customer makes a payment with mollie. The status gets set OK. But on the customer list in BO the order total is still 0 euros. Also on the BO customer page, the total of customer's orders is still 0.

### Environment
* PrestaShop version: 1.7.7.8 
* Mollie module version: 4.4.2 
* PHP version: 7.3

**Comment by wzzly** [comment]
@Saimis777 sorry guys.. seems this site was still running 4.4.1. I really thought it was on 4.4.2. I just updated it to 4.4.2 and the latest customer that ordered had the totals in the customer page displayed correctly!
I still don't have the resend payment link icons though. 
It's the same webshop as I send you the credentials for by email @Saimis777

**Comment by Saimis777** [comment]
Hey @wzzly ,

Thanks for the information, I've checked the email several times, and the spam folder, but did not receive the credentials sorry, maybe you could re-send them please?

Thank you.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @wzzly ,

Would it be possible to re-send the credentials if the issue persists?

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
@Saimis777 sorry for the late reply. I'll send the credentials for the problem with the resend payment link. You can close this issue.

**Comment by Saimis777** [comment]
Hey @wzzly ,

Thanks for the information!

Yeah, I remember you sending them before, but need to be sure that they are not changed or if something else changed..

Thanks again, I will update you regarding the payment link icons.

--
Best regards,
Simonas

**Comment by Saimis777** [comment]
Hi @wzzly,

Resend payment links no longer exist because orders are only created when order is paid. So we no longer need it.

Let us know if you have any other questions!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello,

I will mark this issue as resolved for now.

Let us know if you need any further help!

--
Best regards,
Invertus Support team
