### ISSUE TITLE
Order incorrectly marked as "refunded"

### ISSUE THREAD

**Issue by JoshuaLuckers** [mollie/PrestaShop#45]
In some cases it's possible that an order will show the "The order has been refunded!" message when viewing it via the admin.

# Steps to reproduce

1. Place an order using iDeal. The issuer list should be shown on its own page.
2. When the new page with the list of issuers is opened press back in your browser.
3. Place the order again using iDeal and complete the payment.

The mollie_payments table now has two entries for the same cart id.
When viewing the order in the admin it will now show the "The order has been refunded!" message.

**Comment by JoshuaLuckers** [comment]
We solved it temporarily by adding "ORDER BY created_at DESC" in the query used in the method hookDisplayAdminOrder().

**Comment by firstred** [comment]
Looking at the code it seems to rely on having one or more cancel events in the transactions table. Not sure if an `order by` would help in this case, but if `refunds` are guaranteed to be the last action, then this sounds like a pretty solid solution. Thanks for sharing it!

@snowycatsoftware What do you think?

**Comment by JoshuaLuckers** [comment]
A better solution might be to prevent duplicate payment records for the same cart id. If the payment for a cart already exists we should use the paymentUrl for that payment instead of creating a new one.

**Comment by snowycatsoftware** [comment]
Hi @JoshuaLuckers,

Thank you for taking the time to report this Issue and for offering a solution.

Like @firstred mentioned, this is a solid solution to get the right row. We also have to change a different part of the method hookDisplayAdminOrder().

We will release a new version of the Mollie module as soon as possible!

Kind regards

Snowy Cat Software

**Comment by snowycatsoftware** [comment]
The new version v2.0.4 with a fix for this issue has just been released.

We will close this issue.

Regards
