### ISSUE TITLE
New order email is missing

### ISSUE THREAD

**Issue by Maikel726** [mollie/PrestaShop#450]
### Expected behavior
After you placed an new order you should receive an new order e-mail to your mail that was assigned in the module 'Mail alerts'

### Actual behavior
Only the payment accepted mails are send to the customer but the new order e-mail is missing.

### Steps to reproduce the behavior
Place a new order and you should receive an new order mail.

### Environment
Prestashop 1.7.7.4
Mollie 4..4.2
PHP-version: 7.3.31

**Comment by Saimis777** [comment]
Hello, 

As there are duplicates of this ticket, we will keep the information regarding email case in the ticket - #444

Closing this one.

--
Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @Maikel726 @pantoffelke!

The issue has been resolved in the new release, which is out now, and can be downloaded here - https://github.com/mollie/PrestaShop/releases/tag/4.4.3

Let us know if you have any other questions, and any feedback regarding the release!

--
Best regards,
Invertus Support team
