### ISSUE TITLE
Order not created after payment

### ISSUE THREAD

**Issue by Xesau** [mollie/PrestaShop#451]
### Expected behavior
An order would be created in the Dashboard after the Mollie payment was completed.

### Actual behavior
No order was created, even though the payment was completed and the webhook was called (according to Mollie payment history). The payment description remained "mol_...". The metadata included cart_id, order_reference and secure_key.

### Steps to reproduce the behavior
I cannot yet reproduce the issue

### Environment
* PrestaShop version: 1.7.6.3
* Mollie module version: 4.4.1
* PHP version: 7.2.34

**Comment by Xesau** [comment]
I've updated the module, I'll let you know when it happens again.

**Comment by wzzly** [comment]
@Saimis777 I just placed a test order with the mollie "Overboeking" (bank transfer) payment method, which mean I have 30 days to pay the order by bank. As a customer I get the email to make the payment, but as the payment is not yet completed, there is no order created in the backend. Shouldn't the order be created with the status "Waiting for payment" ?? Now the merchant does not know that a customer placed an order and stock is not updated.

**Comment by Saimis777** [comment]
Hey @wzzly ,

Good notice, there will be an update just for bank transfer, to create an order before the payment due to the waiting time.

We're planning to release it in the next release.

--
Best regards,
Invertus Support team

**Comment by Maikel726** [comment]
Hi,

Having the same issue with PayPal and iDEAL payments.

**Comment by Saimis777** [comment]
Hi @Maikel726,

Is it also for the 4.4.1 version or 4.4.2?

--
Best regards,
Invertus Support team

**Comment by Maikel726** [comment]
Hi @Saimis777

Version 4.4.2

**Comment by Maikel726** [comment]
Hi, @Saimis777

Is it possible to release the fix for this issue as soon as possible? I'm getting more and more complaints that people don't get their ordered stuff.

**Comment by Saimis777** [comment]
Hi @Maikel726 ,

We are doing our best, to keep on track with the new release.

Maybe you could send us your BO + FTP credentials so we could resolve the issue for you? To the email - support@invertus.eu

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @Maikel726 ,

Due to inactivity for more than 5 days I will mark the issue as resolved.

Please let us know if you will need further help!

--
Best regards,
Invertus Support team

**Comment by anthony-mca** [comment]
hi @Xesau , did you find a solution ?
I'm exactly in the same situation as you
