### ISSUE TITLE
Payment methods only show in Test mode

### ISSUE THREAD

**Issue by EvilDragon** [mollie/PrestaShop#453]
### Expected behavior
All enabled payment methods show up

### Actual behavior
Only Apple Pay seems to show

### Steps to reproduce the behavior
Hard to tell, as it might be something in my installation?

### Environment
* PrestaShop version: 1.7.8.0
* Mollie module version: 4.4.2
* PHP version: 7.4.25

I have the problem that the enabled Mollie Payment options don't appear on the checkout page. All other payment options are there, only Mollie is missing.
It seems thought that Apple Pay does work - as a few users paid via Apple Pay. I've never seen it myself - but I guess Apple Pay only appears when you're using an Apple device?

In Sandbox mode, all payment methods appear and work fine, in production mode, they're gone.

I already had to change the language from "de" to "de-de" (otherwise the payment methods won't even show up in testing mode).

Any hint how I can debug this / find out the reason no payment methods are being shown?

Thanks!

**Comment by Saimis777** [comment]
Hi @EvilDragon ,

Thank you for your message.

Have you tried going through these steps as well - https://github.com/mollie/PrestaShop/wiki/Troubleshooting#payment-method-does-not-appear-in-front-office ?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by EvilDragon** [comment]
Oh, thanks a lot!
Resetting the modules settings and ONLY entering the Live API made it work.

So yeah, probably some bug in grabbing the enabled payment methods then :)

**Comment by Saimis777** [comment]
Excellent!

Let us know if you will need any other assistance!

--
Best regards,
Invertus Support team

**Comment by powolnymarcel** [comment]
Hello,

We have followed the troubleshooting steps and the payment options don't appear on the checkout page.

**Comment by powolnymarcel** [comment]
Got in touch with your Team and 
The solution was be to check in BO->International->Localization if the language codes have this format:

fr-fr

instead of : "fr" in our case
