### ISSUE TITLE
ps_emailalerts -> new order mails not being send, since last mollie update

### ISSUE THREAD

**Issue by wzzly** [mollie/PrestaShop#458]
### Expected behavior
When a new order is placed, a notification email is being send to the merchant with the official Mail Alerts module by Prestashop.

### Actual behavior
Since the last Mollie update this email is not being send when the order is paid with Mollie. I gues this has to do with the new change of only creating a new order after payment is success and not triggering the right script?

### Steps to reproduce the behavior
On prestashop 1.7.7 of 1.7.8 with the official Mail Alerts module installed and the latest mollie 4.4.2. 
Mail alerts module can be installed in the module catalog in BO. Or downloaded on github: https://github.com/PrestaShop/ps_emailalerts/
Place a new order and no "new order mail" is being send.

Spend a lot of time figuring out it was due to the mollie module as this is the only payment method we used. But when testing with a different payment method everything works.
Hope you guys have a quick fix for this as this is  

### Environment
* PrestaShop version: 1.7.8
* Mollie module version: 4.4.3
* Mail Alerts module version 2.3.0 https://github.com/PrestaShop/ps_emailalerts/
* PHP version: 7.1.26

**Comment by wzzly** [comment]
UPDATE: I downgraded mollie 
4.4.0 -> email works! 
4.4.1 -> email works!
4.4.2 -> email NOT being send

**Comment by Saimis777** [comment]
Hi @wzzly .

Thanks for the ticket!

This will be fixed next release but for faster fix you do this:

remove Mollie – Effortless payments : +-810line
remove or comment:
if ('new_order' === $template) { return $newOrderMailValidator->validate((int) $order->current_state); }

That should fix the issue for now, until the next release.

--
Best regards,
Invertus Support team

**Comment by powolnymarcel** [comment]
Thanks for all the efforts @Saimis777 :)

**Comment by Saimis777** [comment]
Hello, 

As there are duplicates of this ticket, we will keep the information regarding email case in the ticket - #444

Closing this one.

--
Best regards,
Invertus Support team

**Comment by wzzly** [comment]
@Saimis777 thanks the temporary fix works!

**Comment by waschier-design** [comment]
Same error here - We'll try the temporary fix and inform you if it works within a day.

**Comment by Saimis777** [comment]
Thanks @wzzly , @waschier-design ,

If you'll have any other questions, let me know!

**Comment by loonas** [comment]
Hi @wzzly @waschier-design!

The issue has been resolved in the new release, which is out now, and can be downloaded here - https://github.com/mollie/PrestaShop/releases/tag/4.4.3

Let us know if you have any other questions, and any feedback regarding the release!

--
Best regards,
Invertus Support team
