### ISSUE TITLE
order statuses empty

### ISSUE THREAD

**Issue by powolnymarcel** [mollie/PrestaShop#462]
### Expected behavior
Bo shoud show correct order statuses

### Actual behavior
BO show empty fields, in database the current_state column is "0"

### Steps to reproduce the behavior
Create an order as a customer, complete the checkout process and come back to back office to see the empty status

### Environment
* PrestaShop version: 1.7.5.0
* Mollie module version: 4,4,2 
* PHP version: 7.1.26

**Comment by powolnymarcel** [comment]
Message sent, thanks for the support

**Comment by Saimis777** [comment]
Hi @powolnymarcel ,

The credentials that were previously sent are blocked, we can't log in, should we proceed with this case and wait for the new credentials with a new access?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @powolnymarcel ,

Due to inactivity I will mark this issue as closed for now.

Let me know if you have any other questions!

--
Best regards,
Invertus Support team
