### ISSUE TITLE
Mollie API loaded on every pages

### ISSUE THREAD

**Issue by Nathanpaternotte** [mollie/PrestaShop#467]
Hello,

I notice that on my store, your module loads on each page a JS file coming from you. Slowing down my site and reducing my Pagespeed score, shouldn't it only be loaded at the cart level? 

https://js.mollie.com/v1/mollie.js

My shop : https://am-detailing.com

### Environment
* PrestaShop version: 1.7.8.0
* Mollie module version: 4.3.2 * 
* PHP version: 7.3

**Comment by Saimis777** [comment]
Hello,

Thank you for the ticket,

This issue was already raised, you can follow this thread here - https://github.com/mollie/PrestaShop/issues/408 there are explanations on why it is loaded on all pages, not only cart level.

--
Best regards,
Invertus Support team
