### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by JoshuaLuckers** [mollie/PrestaShop#47]
To make it easier for people to create new issues I would like to suggest to add an issue template where we ask the submitter for some basic informatie to make it easier te reproduce a certain bug.

**Comment by snowycatsoftware** [comment]
Hi @JoshuaLuckers ,

Thank you for taking the time and efford to place this suggestion! We think it's a good idea to add this to the repository. We will look into your pull request and merge it as soon as possible.

Kind regards

**Comment by willemstuursma** [comment]
@davdebcom something for mollie/WooCommerce too?
