### ISSUE TITLE
Pagespeed

### ISSUE THREAD

**Issue by waschier-design** [mollie/PrestaShop#474]
### Expected behavior

--> Mollie.js should only load on necessary pages
--> Mollie.js should be delivered minified (compressed)
--> Mollie.js should be loaded async

### Actual behavior
There are 2 problems with Pagespeed and Loading time.
1.) Mollie.js loads on every page - including index, category, Product Page
2.) Mollie.js loads uncompressed.

This makes bad Pagespeed and is unnecessary.
Should be easy to fix.

### Steps to reproduce the behavior

Install Module and check site with gtmetrix, Pagespeed Insights or other tools ;)

### Environment
* PrestaShop version: 1.7.8.0 
* Mollie module version: 4.4.2 
* PHP version: 7.3.x

**Comment by Saimis777** [comment]
Hey @waschier-design ,

This issue can be found here - https://github.com/mollie/PrestaShop/wiki/Upcoming-fixes-Wishlist in the #408 ticket you can see the reasons on why JS is loaded on all pages.

It's one of the wishlist/upcoming fixes, will notify once it's completed in the #408 ticket :)

--
Best regards,
Invertus Support team
