### ISSUE TITLE
Feature request: Refund € amount instead of product units

### ISSUE THREAD

**Issue by wzzly** [mollie/PrestaShop#476]
### Expected behavior
We had a case where we wanted to refund a % of the total amount of the order. But in the order page, when clicking refund, you can only choose a number of units you want to refund. So now we had to do it in the mollie.com dashboard and the order totals are wrong in Prestashop.

### Actual behavior
Would be nice if you want to make a refund on the order page, that you can also choose a € amount you want to refund, instead of only a number of units.

![image](https://user-images.githubusercontent.com/35727938/144075184-6447bc74-7b6e-408c-a2bb-f48b25027653.png)

**Comment by Saimis777** [comment]
Hello,

Thank you for the request, I'm adding it to our wiki page named - Upcoming fixes-Wishlist

Mollie team will either confirm or deny the request, I will keep you updated regarding this case.

--
Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi there @wzzly!

We have noted down this feature request in our plans, and once we have an update about it, we will let you know!

For now, we will close this issue.

--
Best regards,
Invertus Support team
