### ISSUE TITLE
Refund not possible (PrestaShop backoffice)

### ISSUE THREAD

**Issue by RVanDamage** [mollie/PrestaShop#478]
One of our customers always refunded orders using the Mollie tab from the PrestaShop backoffice. Recently we upgraded from Mollie module 3.5 to the latest v4.4.2.

Now the refunding does not work anymore and shows an error. Their only option to refund now is to use Mollie dashboard directly.
However our customer prefers to do it from the PrestaShop backoffice.

We already did some small trouble shooting. At first we thought it were only the "Pay later" orders, but now came to the conclusion that other payments like iDeal have the same issue.

We will do some more research later and provide you with more info.

### Environment
* PrestaShop version: 1.7.6.9 
* Mollie module version: 4.4.2
* PHP version: 7.2.34

**Comment by Saimis777** [comment]
Hi @RVanDamage ,

Thank you for the information!

Since you were updating from 3.5, you would need to completely remove the module, including the tables in the database, and re-install module as a new one.

Please try that, and let me know if it helps!

--
Best regards,
Invertus Support team

**Comment by RVanDamage** [comment]
Hi @Saimis777,

This is something we have already done, also because we were updating from 3.5.
Or maybe there is some other way to delete all tables from database?
Isn't default deinstalling and removing module enough?

**Comment by Saimis777** [comment]
Hi @RVanDamage ,

You would need to manually delete Mollie created tables in the database. The tables have a prefix mol_ and one is mollie_ so you can delete them manually, and install the module as a new one.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @RVanDamage,

Let us know once you're ready to continue with this!

For now, we will mark this issue as resolved.

--
Best regards,
Invertus Support team
