### ISSUE TITLE
Checkout button stay unclickable if you entered wrong information in the integrated credit card form

### ISSUE THREAD

**Issue by AnatoleRozan** [mollie/PrestaShop#484]
### Expected behavior
I enter wrong credit card information, I have the error message, I modify and you click on the button again. Then the order is confirmed.

### Actual behavior
I enter wrong credit card information, I have the error message, I modify but the order button stayed not clickable.

### Environment
* PrestaShop version: 1.7.7.0 
* Mollie module version: 4.4.3 
* PHP version: 7.1.26 

Really, the plugin has too many bugs... I've never seen that.

**Comment by loonas** [comment]
Hi there, Anatole, I hope that you are having a great day so far!

I'm truly sorry to hear that you are experiencing this issue. Could you provide a screenshot or more details about what error appears when entering the wrong information?
Additionally, could you provide us your BO + FTP credentials so we could resolve the issue for you? You can email them directly to support@invertus.eu.

I will be looking forward to your reply!

Best regards,
Invertus Support team

**Comment by AnatoleRozan** [comment]
Hello, 

Thank you for your answer.

I let you try the bug in a VM.

I spent too many times reporting you issues. You should redevelop the entire plugin. All our developers (intern and extern) have issues on it...

Best regards,

Anatole.

**Comment by loonas** [comment]
Thank you for your response, Anatole!

I completely understand your position regarding this and I'm truly sorry to hear about the problems that you have had with it. We are constantly improving the module and striving to perfect it, so it would raise no issues with it's performance, and we truly appreciate the feedback about it - it helps us improve.

Our developers have taken a look at the issue, and applied a fix. You can find the module, with the included fix, right [here](https://we.tl/t-Wn0QCyeXzU).

Could you check it out and let us know how it goes?
We will be looking forward to your reply.

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Thank you for the update, Anatole. I'm glad to hear that, and we are more than happy to help.
I will mark this issue as resolved for now.

Let us know if you need any further help at any time!

Best regards,
Invertus Support team

**Comment by AnatoleRozan** [comment]
https://user-images.githubusercontent.com/38098728/145185836-c81273ed-661c-42c9-9010-99900d4ce704.mp4

**Comment by loonas** [comment]
Thank you for the video @AnatoleRozan!

I have forwarded it for further investigation to our developers, and we will keep you updated in the open git issue about this (#486).

Best regards,
Invertus Support team
