### ISSUE TITLE
Problem selecting payment methods

### ISSUE THREAD

**Issue by AnatoleRozan** [mollie/PrestaShop#486]
### Steps to reproduce the behavior
Use external page option (because too many problems in the embed form).

• Select Credit card payment method
• Then select Paypal
• Then click on "Checkout"
• You are redirect to the Credit card landing page instead of Paypal...

### Environment
PrestaShop version: 1.7.7.0
Mollie module version: 4.4.3
PHP version: 7.1.26

**Comment by loonas** [comment]
Hi there, Anatole, how are you doing today?

Our team is already looking into this issue, we truly appreciate the following notes as well. We will keep you updated about the progress!
Thank you for your patience, and understanding.

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi there, @AnatoleRozan!

Our team has checked the issue, and they have not been able to replicate it on their side. Could you share screenshots or screen recordings of the issue? 
It would help us to replicate it and proceed with further investigation.

I will be looking forward to your reply.

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi there @AnatoleRozan,

Our developer checked the video, but we are unable to replicate the issue. In order to resolve this, could you please provide your BO+FTP credentials to support@invertus.eu?

We will be able to investigate it further.

I will be looking forward to your reply!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @AnatoleRozan,

Let us know once you're ready to continue with this!

For now, we will mark this issue as resolved.

--
Best regards,
Invertus Support team
