### ISSUE TITLE
ccs

### ISSUE THREAD

**Issue by whoopzies** [mollie/PrestaShop#49]
hello 
i like to ask how can i make the background of the paybutens transparant 
is now a big with buten and i like it transparant how can i do it let me know 

thx

**Comment by firstred** [comment]
This is how I changed the background of the buttons. This might work for you as well:
```
.mollie_methods p.payment_module 
    background: transparent;
}
```
You can add this to your theme's CSS or the `order.css` file in your theme folder.

**Comment by snowycatsoftware** [comment]
Hi @firstred ,

That's a great solution! We are going to mark this issue as closed.

Kind regards

**Comment by whoopzies** [comment]
thx for you fast respons 👍
