### ISSUE TITLE
'Send webshop locale' setting results in redirect to homepage 

### ISSUE THREAD

**Issue by preitsma** [mollie/PrestaShop#50]
Mollie Prestashop Addon 2.0.4
Prestashop 1.6.1.10 
Module setting: send locale for payment screen set to 'Send webshop locale'

Clicking Ideal in the final screen of the Checkout Flow redirects me the home page instead of the Mollie Bank selection screen.
This happens on Safari and Firefox, not on Chrome. Did not test on IE.

**Comment by snowycatsoftware** [comment]
Hi @preitsma ,

We just release the new version with the fix for this issue.

Kind regards
