### ISSUE TITLE
Make the 'order canceled' function optional

### ISSUE THREAD

**Issue by x0royx** [mollie/PrestaShop#52]
If you decide to give the customer a partial refund for whatever reason (discount or other agreement), still the module will automatically put the entire order as ''refunded''. This causes the customer's account to show the order value at 0.00, while in fact it could be a different value that is still paid. This has consequences for the order status being shown as incorrect, and for example the email that is automatically sent out by Prestashop that says: ''Order refunded''. It also removes the customer loyalty points for that order, considering Prestashop thinks the complete order was cancelled and refunded.

I would like to have the ability to turn off this connection. While it seems a good idea, it's definately not a good solution for every shop and situation.

**Comment by snowycatsoftware** [comment]
Hi @x0royx ,

Thank you for taking the time and efford to post this issue. We will look into this and we will inform you about upcomming changes.

Kind regards

**Comment by snowycatsoftware** [comment]
Hi @basemedia ,

We are currently working on a major update for the Mollie module. This issue has been taken into account. As soon as the update is ready to be released, we will provide further information concerning this issue as well.

Kind Regards

**Comment by snowycatsoftware** [comment]
We just released the new version in which this issue has been fixed. Therefore, we are closing this issue.

Regards
