### ISSUE TITLE
Change "ps_orders.payment" after customer changes payment method

### ISSUE THREAD

**Issue by muyncky** [mollie/PrestaShop#53]
Hi Mollie,

When a customer choses the payment method banktransfer but completes it with iDeal everything works. But in the system the order is still registered as if it was paid with banktransfer.

I suggest to put this code (did not test) at line `145` at the end of `if ($apiPayment->metadata->cart_id)` in `controllers/front/webhook.php`:

```
if ($psPayment['bank_status'] == 'banktransfer') {
    $order = new Order($orderId);
    $order->payment = 'banktransfer';
    $orderId->update();
}
```
I would kindly like to ask you to implement this for the next update. 

Thanks a lot!

**Comment by snowycatsoftware** [comment]
Hi @muyncky ,

Thank you for bringing this to our attention. We will look into this and of course, we will keep you updated.

Kind regards

**Comment by snowycatsoftware** [comment]
We just released the new version in which this issue has been fixed. Therefore, we are closing this issue.

Regards
