### ISSUE TITLE
Possiblility to enter custom returnURL based on User-agent

### ISSUE THREAD

**Issue by preitsma** [mollie/PrestaShop#55]
We embedded our Presta webshop into an iOS app and are running into a problem when a customer returns from the bank app, back to the webshop. 
The bank app opens Safari and tries to load the return url, which it can't find since the webshop and session are wrapped in the shop app.

This could potentially be solved if the add-on would allow us to enter a customer return URL for a specific User-Agent. In this case we can detect the users coming from the app (User-Agent = WebKit), and use an appscheme return url instead, something like `our-app://return-url?order=bla`.

This would return a user to our shop app.

In case this is not feasible to implement, could you give me some hints as in which files I need to hack this functionality myself?

Thanks ahead!

**Comment by JoshuaLuckers** [comment]
You could override the MolliePaymentModuleFrontController. 
[The return url is created at line 336](https://github.com/mollie/PrestaShop/blob/7d219193004a76fcd59178354635b8cedd706600/controllers/front/payment.php#L336)

**Comment by willemstuursma** [comment]
Mollie doesn't accept any in-app (appscheme) return URLs. You need to redirect back to the app on the return page.

**Comment by willemstuursma** [comment]
https://help.mollie.com/hc/en-us/articles/214437245-How-do-I-redirect-the-user-to-my-app-after-a-payment-
