### ISSUE TITLE
order_page_name

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop#57]
Hello,

I am having a small issue with the new version. We use a small piece of code to "hide" the menu in the checkout:
{if {$request} == "{$base_dir_ssl}authentication?back=my-account"}
{include file="$tpl_dir/header-order.tpl"}
{elseif (($page_name == "order") && ($order_page_name == "order-summary"))}
{include file="$tpl_dir/header-order.tpl"}
{else}

When installing the new version 3.0+ i am having this issue in the top of the website.
Notice: Undefined index: order_page_name in /public_html/cache/smarty/compile/a2/29/be/a229be2c69f6ae48834f06cad35a6fdad48c5f03.file.header.tpl.php on line 81
Notice: Trying to get property of non-object in /public_html/cache/smarty/compile/a2/29/be/a229be2c69f6ae48834f06cad35a6fdad48c5f03.file.header.tpl.php on line 81

Is the new version using the header or some kind of hook in a different way?

**Comment by snowycatsoftware** [comment]
Hi @basemedia ,

This doesn't sound like Mollie related issue. It looks cache related. Maybe if you clear the cache, it might solve this issue. Please let us know if this solves the problem.

Regards

**Comment by basemedia** [comment]
Thanks for the fast response:

I am getting this message then:
Notice: Undefined index: order_page_name in /var/www/.nl/public_html/tools/smarty/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 81

Notice: Trying to get property of non-object in /var/www/.nl/public_html/tools/smarty/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 81

**Comment by snowycatsoftware** [comment]
Hi @basemedia ,

Which hook did you use to assing $order_page_name to smarty? And could you please show me the code?

**Comment by basemedia** [comment]
Well we removed some code in a different header file. Override is like this OrderController.php:

It only happens in the checkout pages.

<?php
class OrderController extends OrderControllerCore
{
// tell the header and footer templates when a user is on the shopping cart / order summary page
public function initHeader()
{
  if (!Tools::getValue('ajax')){
   if(((int)$this->step == 0) || ((int)$this->step == -1))
	self::$smarty->assign('order_page_name', 'order-summary');
   parent::initHeader();
  }
}
}
?>

**Comment by firstred** [comment]
Looks like the module always enables error reporting from version 3.0.0 on. If you remove the following lines from the main module file it will no longer show those error messages: https://github.com/mollie/PrestaShop/blob/9a5a6526150ef2710b71c1d7277eb11559e51c2b/mollie.php#L35-L37

**Comment by basemedia** [comment]
Working thanks Michael!

**Comment by snowycatsoftware** [comment]
@basemedia ,

We are very sorry for the inconvenience this has caused, we just released a new version in which the error reporting has been removed.

Regards
