### ISSUE TITLE
iDEAL-QR-codes

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop#59]
When the iDEAL-QR-codes is activated the modal is pushed to the top. Some payment providers are not directly visible in. Some redesign is needed.

Screenshot attached.
![qr](https://user-images.githubusercontent.com/1645341/41771829-a942343c-7616-11e8-941e-d47feaf9b39d.png)

**Comment by snowycatsoftware** [comment]
Hi @basemedia ,

We tested this in multiple browsers before launching it and we didn't have this problem. We just tested this again to be sure and all bank options including iDEAL QR are showing neatly. Could you provide us with a link where we can view this issue? If you rather not post the link // domainin public, you can also e-mail us at info@snowycatsoftware.com.

We will look into this as soon as possible.

Kind regards

**Comment by willemstuursma** [comment]
@snowycatsoftware Neat, I didn't know that iDEAL QR was supported in our Prestashop plugin. Is there something arranged that pushes the payment status back to the shopper, some polling?

**Comment by snowycatsoftware** [comment]
Hi @willemstuursma ,

Thank you and yes, this was recently added this to the Mollie module. When the payment is completed (or cancelled or expired), the status is sent back and the user is provided with a custom .tpl. This file will provide some more insights :) : https://github.com/mollie/PrestaShop/blob/master/controllers/front/qrcode.php

**Comment by firstred** [comment]
Setting the bank icon height to `24px` seems to do the trick, but we'll have to be careful with the touch area, otherwise this modal is going to be difficult to use on touch devices. Might have to retain the screen size limit of 800(w) x 860(h) as well.

**Comment by firstred** [comment]
That seems to work. Feel free to comment if it still doesn't look good in your store.
