### ISSUE TITLE
no tax added on the payment-fee

### ISSUE THREAD

**Issue by Frankyet** [mollie/PrestaShop#602]
### Expected behavior
When payment fee is used you suspect it using the tax from the country of the customer

### Actual behavior
There is no tax added on the payment-fee

### Steps to reproduce the behavior
Creat a order with a payment methode with payment-fee

### Environment
* PrestaShop version: 1.7.8.7
* Mollie module version: v5.2.0
* PHP version: 7.4

**Comment by justelis22** [comment]
Hi there @Frankyet!

We have received your request, it will be overviewed and we will get back to you!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello @Frankyet, thanks for waiting!

At the moment, this is how the Mollie module is configured. If you have taxes assigned to a product, the total price of a product would be calculated like this:
Total price with tax excluded then the taxes for the products are applied and in the end, the Mollie payment fee is added to the total. You can check this example:
![image](https://user-images.githubusercontent.com/103486043/183067484-a351546d-1f89-4cff-95c1-05534ae8779d.png)
The total for the products without taxes is 18.9 EUR, the total without taxes but with additional fees, shipping and etc. is 22.9 EUR. This brings the total price to 26.49 EUR. The taxes are only calculated for the products.
In this example, VAT was 19 %.
Payment fee - 4 EUR.

Let us know if you have any additional questions!

Best Regards,
Invertus Support team.

**Comment by Frankyet** [comment]
There is no tax calculateted over the payment fee and that is not correct Op 5 aug. 2022 13:26 schreef justelis22 ***@***.***>:
Hello @Frankyet, thanks for waiting!
At the moment, this is how the Mollie module is configured. If you have taxes assigned to a product, the total price of a product would be calculated like this:
Total price with tax excluded then the taxes for the products are applied and in the end, the Mollie payment fee is added to the total. You can check this example:

The total for the products without taxes is 18.9 EUR, the total without taxes but with additional fees, shipping and etc. is 22.9 EUR. This brings the total price to 26.49 EUR. The taxes are only calculated for the products.
In this example, VAT was 19 %.
Payment fee - 4 EUR.
Let us know if you have any additional questions!
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hey there, @Frankyet!

We will communicate with our team and we will let you know how we can solve this case.
Thank you for your patience!

Best Regards,
Invertus Support team.

**Comment by basemedia** [comment]
What is the status of this issue?

**Comment by justelis22** [comment]
Hi @basemedia,

This task was forwarded to the Mollie team, we are still waiting for some answers and additional details so that we could begin the development.
If anything changes, we will inform you here.

Best Regards,
Invertus Support team.

**Comment by basemedia** [comment]
Hi @justelis22,

Any updates regarding this issue?

Thanks.

Luke

**Comment by justelis22** [comment]
Hi @basemedia,

We are planning on doing this, but it is still under Mollie's review at the moment.

Once we have some news, we will inform you here.

Best Regards,
Invertus Support team.

**Comment by Frankyet** [comment]
Why is this issue taking so long? it is reported almost 16 week ago. Mollie it self is also counting tax on his payments, so it should not be that hard te review this.

best regards,
Frank

**Comment by justelis22** [comment]
Hi there @Frankyet,
Thanks for waiting!

We are planning to include this fix in the next release, although, at the moment we are on release freeze, so the release most likely will be done at the beginning of Q1.

Once again thank you for your patience and understanding! You can be sure that the information about any updates will be added to this issue.

Best Regards,
Invertus Support team.

**Comment by Frankyet** [comment]
Hello Invertus Support team,

we are 9 month further still not solbed this issue, is it better to look for a module on the addon market of prestashop for payment fee for PayPal? are is ut wainting useful?

best regard,
Frank

**Comment by justelis22** [comment]
Hi there @Frankyet,

Thank you for your patience!

I wanted to inform you that the payment fee feature has been added to the beta release, which can be found here - https://github.com/mollie/PrestaShop/releases/tag/v6.0.1-beta

If you haven't found another module yet, we would really appreciate your feedback!

Best Regards,
Invertus Support team.
