### ISSUE TITLE
hookDisplayHeader does not check if api key exist and notice in developer mode.

### ISSUE THREAD

**Issue by arjan-designpro** [mollie/PrestaShop#624]
### Expected behavior
 if (!$apiKey) {
    return;
}

### Actual behavior
Notice because its not always filled. (in cart)

### Environment
* PrestaShop version: 1.7.8.7
* Mollie module version: 5.3.1
* PHP version: 7.4

**Comment by justelis22** [comment]
Hey there,

We will be glad to help you with this! Our team will check your case, and get back to you as soon as possible with an update.

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello there,

This was fixed with the 6.0.0 release. Marking the issue as resolved.

If there are any other questions, please do let me know!

--
Best Regards,
Invertus Support team.
