### ISSUE TITLE
Edge case: returns from EPS payments (bank site, second step) are not handled properly

### ISSUE THREAD

**Issue by firstred** [mollie/PrestaShop#64]
Going directly from the EPS payments bank page:
![epsueberweisung](https://user-images.githubusercontent.com/6775736/42112948-ebd19120-7be9-11e8-8f77-0aa4c483a937.png)

to the return URL, causes the following message to be shown:
![nopaymentstatus](https://user-images.githubusercontent.com/6775736/42113002-109fe236-7bea-11e8-8f63-2e588f84b631.png)

this is likely due to the fact that the payment status == `pending` at the moment we are making our return. The "Abbrechen" link (top right) seems to be a direct link to the store, so Mollie likely hasn't had the chance to set the payment status to `canceled`, yet.
This problem does not occur when the user cancels the EPS payment during the first step:
![zahlungabbrechen](https://user-images.githubusercontent.com/6775736/42113139-853e4d9e-7bea-11e8-8728-93ed3b039b2a.png)

**Comment by willemstuursma** [comment]
Thanks, maybe we can pick this up from our side, I'll have a look next week.

**Comment by snowycatsoftware** [comment]
Hi @willemstuursma ,

@firstred is my bussinesspartner. We run SnowyCatSoftware together. Could you please add him as a Collaborator to this repository and to the https://github.com/mollie/thirtybees repository as well?

Have a great weekend!

Regards

**Comment by willemstuursma** [comment]
@firstred could you send me the payment id for the payment that had this problem.

For eps, canceling the payment ("Abbrechen") seems to lead to a `failed` status in our API. We're looking into this.

**Comment by firstred** [comment]
@willemstuursma 

I'm not 100% sure, but these could be the payment IDs:
- `tr_ktTTNE8GsW`
- `tr_NDWA59Bvsz`
- `tr_svenBhKJat`
- `tr_UDy8sJMszm`

**Comment by firstred** [comment]
Closing this issue for now. It seems that since commit 7befd8ab76a6196fba9f0f9243c13351d9018272 the module is now able to handle these statuses as well.
