### ISSUE TITLE
Images not shown on onepagecheckout

### ISSUE THREAD

**Issue by yavuzaydin** [mollie/PrestaShop#67]
After updating the Mollie module to the most recent version (3.2.0) images aren't shown on our onepagecheckout module. The code which shows the image is within a {if $payment_method.img}...{/if} block, $payment_method.img is undefined. It did work previously (which was an older Mollie version, I think a 2.x version).

**Comment by snowycatsoftware** [comment]
Hi @yavuzaydin ,

- Which exact 2.0.x version did you use before you upgraded to 3.2.0? 
- Did you also upgrade the one-page checkout module you use in the meanwhile as well? 
- Do the images show if you disable the one-page checkout module?

Kind Regards

**Comment by yavuzaydin** [comment]
Previous version was 2.0.5, onepage checkout module is not upgraded (image from coinpayments payment module is still shown, taht's the only other payment method I have).

> Do the images show if you disable the one-page checkout module?

Tried to disable the module but couldn't get the checkout page to work. Need to dig further in this, unfortunately the backend is so slow which makes working on Prestashop a hell right now.

**Comment by snowycatsoftware** [comment]
Slow backend can be fixed. This is a PrestaShop addons server problem. Use the module you can find on the PrestaShop forum (see link below) to temporarily disable addons connection and the backend (and frontend) problem should be solved. Look for the post made by a user named "El Patron" and download the module (named disableaddonsapi (1).zip). Install it, enable it and the backend should be fast again. The frontend as well.

https://www.prestashop.com/forums/topic/907905-very-slow-backend/

**Comment by Lolito** [comment]
why do you write me now? i updated from 1.6 to 1.7 prestashop, and all is
working fine here, i have no issues.

Manuel Torres

**Comment by yavuzaydin** [comment]
Disregard, I have tested this on my development environment and it works there. On my production I have a couple of other overrides which is probably causing this.

**Comment by firstred** [comment]
@Lolito you likely are watching this repository on GitHub, so you see all notifications.
If you visit the following page: https://github.com/mollie/PrestaShop then click "Unwatch", top-right corner of your screen, you can disable these notification mails.
