### ISSUE TITLE
PHP8 support new prestashop 8.0.1 want PHP8 on server

### ISSUE THREAD

**Issue by nl2ttl** [mollie/PrestaShop#670]
### Expected behavior
Support for PHP 8

### Actual behavior
Now I get large php error logs

### Environment
* PrestaShop version: 8.0.
* Mollie module version: 5.4.0
* PHP version: 8

Error log in attachment (is from one page load)
[Errorlog.txt](https://github.com/mollie/PrestaShop1.7/files/10788104/Errorlog.txt)

**Comment by justelis22** [comment]
Hey there,

We will be glad to help you with this! Our team will check your case, and get back to you as soon as possible with an update.

--
Best Regards,
Invertus Support team.

**Comment by thomveen** [comment]
Same here

**Comment by sharkooon** [comment]
Any updates about this?

**Comment by justelis22** [comment]
Hey there,

The issue has now been fixed, please update the module if you haven't yet.

We will also be waiting for your feedback!

--
Best Regards,
Invertus Support team.
