### ISSUE TITLE
Order status changes back to payment accepted while order already shipped

### ISSUE THREAD

**Issue by melissaandries** [mollie/PrestaShop#676]
### Expected behavior
Order status shouldn't be changed back to payment accepted after order has been shipped.

### Actual behavior
Order has been shipped and status was updated accordingly. After a while it was updated again to payment accepted. This causes orders to be shipped twice.

### Steps to reproduce the behavior
Unable to reproduce ourselves, but we have seen it for 2 different orders now, see attached screenshots.
Both orders were placed using Klarna as payment option.

### Environment
* PrestaShop version:  1.7.8.5
* Mollie module version: 5.3.1 
![2023-03-10 12_17_50-Order management _ Bekijken • Zizzoo — Firefox Developer Edition](https://user-images.githubusercontent.com/105208007/224302813-5f10b2db-87af-440d-9e5c-c8a01de9be84.png)
![2023-03-10 12_17_07-Order management _ Bekijken • Zizzoo — Firefox Developer Edition](https://user-images.githubusercontent.com/105208007/224302818-9b2bec2a-c8c3-4f8f-bfb1-257af23fb388.png)

* PHP version: 7.4.30

**Comment by justelis22** [comment]
Hey there @melissaandries,

We will be glad to help you with this! Our team will check your case, and get back to you as soon as possible with an update.

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi @melissaandries,

We have analyzed the issue and tried to replicate the behavior, although without any success.
Could you please send us access to your shop (BO and FTP credentials) to our email at support@invertus.eu?

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello there,

As this issue was not updated for some time now, I will close it.
If you are still facing the issue, please send me the requested information and we will pick up from where we ended.

--
Best Regards,
Invertus Support team.
