### ISSUE TITLE
Add Klarna to payment methods

### ISSUE THREAD

**Issue by yavuzaydin** [mollie/PrestaShop#68]
Please add Klarna to payment methods.

**Comment by snowycatsoftware** [comment]
Hi @yavuzaydin ,

We are currently working on an upgrade to add Klarna to the Mollie module. The new version will be available as soon as possible.

Kind Regards

**Comment by snowycatsoftware** [comment]
Hi @yavuzaydin ,

Klarna has been added in the latest version of the Mollie module (v3.3.0). Make sure you select the "Orders API" on the config page in order to use Klarna.

Kind Regards
