### ISSUE TITLE
removed organisation still visible

### ISSUE THREAD

**Issue by musicpanda** [mollie/PrestaShop#70]
In my user account I in Prestashop I had an organisation name. Let's call it Myorg. While on my checkout page - and before my payment - I removed that organisation name. 
Yet when I continued to Mollie's payment page I saw there "Wim Panda - Myorg".

**Comment by snowycatsoftware** [comment]
Hi @musicpanda,

In which field did you remove the organisation name?

Kind Regards

**Comment by musicpanda** [comment]
Company name

**Comment by snowycatsoftware** [comment]
Hi @musicpanda ,

Because this is not a Mollie issue and because we haven't recieved a response anymore, we are closing this issue.

Kind Regards
