### ISSUE TITLE
Payment options displayed twice.

### ISSUE THREAD

**Issue by Apury** [mollie/PrestaShop#74]
I'm using Mollie in the testing environment and haven't modified the module in any way shape or form. It's a fresh installation of the module. 

### Expected behavior
Payment options should only be displayed once.

### Actual behavior
The payment options are displayed twice.

### Steps to reproduce the behavior
Visit the Checkout page in PS. 1.7.3.4
![untitled](https://user-images.githubusercontent.com/41310433/47729450-76a07b00-dc60-11e8-8bd0-3453a8407a06.png)

### Environment
* PrestaShop version: 1.7.3.4
* Mollie module version: 3.3.1

**Comment by snowycatsoftware** [comment]
Hi @Apury ,

This is a known problem in PS 1.7. Please Go to Modules -> Positions or Design -> Positions. Remove the Mollie module from the displayPaymentEU hook and it should be back to normal.

Please let us know if this solves your issue.

Kind Regards

**Comment by Apury** [comment]
Thank you! This indeed solved the problem.

**Comment by snowycatsoftware** [comment]
Hi @Apury ,

Thank you for taking the time to inform us. Have a great evening.

Kind Regards
