### ISSUE TITLE
Using the Orders API reasults in Error 500.

### ISSUE THREAD

**Issue by Apury** [mollie/PrestaShop#75]
### Expected behavior
I'm expecting to be able to use mollie as it works with the Payment API. The only difference being that it also allows for the Klarna based payment options. 

### Actual behavior
If I change mollie to use the Orders API instead of the Payments API, none of the payment options work and all of them result in an error 500, when they're usually redirecting to the mollie payment page.

### Steps to reproduce the behavior
Select Orders API instead of Payments API in the described environment.

### Environment
* PrestaShop version: 1.7.3.4
* Mollie module version: 3.3.1

**Comment by snowycatsoftware** [comment]
Hi @Apury ,

Thank you for posting this issue. Could you please enable the PrestaShop debug mode (Go to Advanced Parameters -> Performance and set debug mode to "Yes") and copy / paste the error so we can see what goes wrong in your case?

Kind Regards

**Comment by Apury** [comment]
Here you go:

![error](https://user-images.githubusercontent.com/41310433/47783976-8d001280-dd04-11e8-9c4a-4bfb485f5d85.JPG)

And this is the result with the payments API selected:

![error2](https://user-images.githubusercontent.com/41310433/47784186-27f8ec80-dd05-11e8-9167-3f18723c25a0.jpg)

**Comment by snowycatsoftware** [comment]
Hi @Apury ,

Please follow these steps:

- Unzip the latest version of the Mollie module (3.3.1) on your desktop;
- Open the folder mollie/views/templates/front;
- Via the FTP, go to the main folder of your domain and open the folder modules/mollie//views/templates/front;
- Check if all files have been uploaded as it seems 1 or more file is missing (like error.tpl in this case).

If you have the cache enabled, turn it off and clear the cache as well.

Please try another testpayment. This way we can check which exact error is thrown.

Kind Regards

**Comment by Apury** [comment]
Sadly all the files seem to exist to begin with. 

![capture](https://user-images.githubusercontent.com/41310433/47785663-abb4d800-dd09-11e8-93fa-64e2e351e0bf.JPG)

**Comment by snowycatsoftware** [comment]
It could be a problem concerning version compatibility, could you please try the bèta version enclosed it this comment to check if this solves your problem?

[mollie-v3.3.2-beta.1.zip](https://github.com/mollie/PrestaShop/files/2534120/mollie-v3.3.2-beta.1.zip)

**Comment by Apury** [comment]
This now resultet in "An error occurred while initializing your payment. Please contact our customer support." 

![capture](https://user-images.githubusercontent.com/41310433/47786253-7d37fc80-dd0b-11e8-9f93-fbaff73dccb8.JPG)

Which is certainly an improvement. After enabling the debug option in the mollie module I got a few more hints: 

> Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. Quantity must be greater than 0.. Field: lines.1.quantity. Documentation: https://docs.mollie.com/guides/handling-errors

**Comment by firstred** [comment]
That is interesting.

Do you use modules that can add product customizations to the cart (dynamic price / advanced pack 4)? Or modules that manage (shipping/handling [EU compliance]) taxes?

**Comment by Apury** [comment]
I'm using the GDPR compliance module. Given that the business is still in the stage of wrapping up price negotiations with potential partners, there hasn't been too much work done on the whole price display / calculation options that prestashop and other modules offer. 

Here is the full list of installed modules. It's not the cleanest of mock ups but it'll get the job done.

![modules](https://user-images.githubusercontent.com/41310433/47787013-d6a12b00-dd0d-11e8-90f6-2ce6eebc2fd3.jpg)

**Comment by snowycatsoftware** [comment]
Hi @Apury ,

We created a new bèta version which checks data integrity. Could you please try this version?

[mollie-v3.3.2-beta.3.zip](https://github.com/mollie/PrestaShop/files/2534359/mollie-v3.3.2-beta.3.zip)

**Comment by Apury** [comment]
I feel stupid now. You guys were right. I apparently have changed the decimals for prestashop to consider while rounding to 0 as a 'quick way' to get smooth prices. Which resulted in 2 49,99€ items to be displayed as 100€ at the checkout. Which obviously isn't right. 

Thank you for implementing the integrity check which explained perfectly well what exactly was wrong. 

My question now is, will a module like the advanced rounding (which is especially helpful when it comes to considering for example the chinese / japanese / korean currency which don't display their last two decimals. Before investing money in such a plug-in it'd be good to know whether mollie's order API will be able to cope with the rather weird way Prestashop works in that regard.
