### ISSUE TITLE
How do I trigger Mollie's default E-Mail whenever there is a bank-wire payment?

### ISSUE THREAD

**Issue by Apury** [mollie/PrestaShop#76]
### Expected behavior
I've disabled 'Send mails when bank wire pending' and am expecting an e-mail along those lines to be sent to customers. 

![capture](https://user-images.githubusercontent.com/41310433/47822170-7046f780-dd63-11e8-8c5c-a4d387fec5d2.JPG)

### Actual behavior
The e-mail template for bank wire payments is still being sent despite 'Send mails when bank wire pending' being unselected. 

### Steps to reproduce the behavior
Activate 'Send mails when bank wire pending' -> save -> deactivate

### Environment
* PrestaShop version: 1.7.3.4
* Mollie module version: 3.3.1

Sending the default bank wire e-mail obviously isn't an option with the on the fly generated reference to associate the payment with an order. 

Even after uninstalling the module, deleting the custom payment status and re-installing it, while only adding the API key, so that 'Send mails when bank wire pending' stays disabled, it sends the normal bankwire payment e-mail. 

Furthermore, refund e-mails won't be sent either. Regardless of the selected payment method. 

However, as soon as I change the API to the payments API both, the mollie bankwire e-mail and the refund e-mail are being sent. 

My question now is, are there variables such as `{bankwire_owner}` to be used for the mollie side generated reference within prestashop's default bankwire e-mail template to just forward mollie's bank-wire information to the customer with the default template? 

Additionally, I'd like to know if it's possible to get the refund e-mails working with the orders api as well.

**Comment by firstred** [comment]
Thanks for opening this issue @Apury.
We will have a look at it!

**Comment by firstred** [comment]
Thanks again for the useful information @Apury!

I think I have found what might have caused it. The Orders API reports `open` and `refund`, `partial_refund` statuses differently. I don't think we fully support the alternative in the module, yet. This is why not all the emails are sent.

We'll try to adapt the module and will let you know when an update is available. Apologies for the inconvenience!

**Comment by firstred** [comment]
Further details:

It turns out that `PaymentModule::validateOrder` always creates a new order and assigns an order status via `addWithEmail`. We can use the new `validateMollieOrder` function, already embedded in the module, to override this behavior and use `add` instead, when we don't want to send an email.

**Comment by firstred** [comment]
And it seems to incorrectly map the Mollie statuses. This check is being used to find out whether the mail needs to be sent: `'MOLLIE_MAIL_WHEN_pending`, whereas it should be `MOLLIE_MAIL_WHEN_open`.
This might be the case with refunds, too.

**Comment by Apury** [comment]
Thank you @firstred for the quick investigation. I'm happy to learn that you guys've already tracked down the issue. I'll practice myself in patience until a new update with a fix for the orders API gets released.

**Comment by firstred** [comment]
Hi @Apury 
You can try this new beta version if you want: 
[mollie-v3.3.2-beta.4.zip](https://github.com/mollie/PrestaShop/files/2540750/mollie-v3.3.2-beta.4.zip)


Note that it is not ready yet for a live environment, but the email issues should have been fixed.

**Comment by Apury** [comment]
I've simulated about 10 orders as of now and the amount in mollie's payment screen has always matched the amount in my basket / summary. Thus, I pressume that it works. From what I can tell, the default value for gift wrapping has caused it, given that I haven't used any module or the likes. 

Speaking of which, I was actually about to reiterate on that. To keep it short, I'm currently struggling with the very same problem. After all, that's still what's keeping me from using the orders API. I've once again disabled "Send mails when Bankwire pending" and whether I select "open" or "paid" in mollie's bankwire payment with my test profile, it refuses to send the mollie generated bankwire e-mails, which I can perfectly receive in the payments API.

**Comment by firstred** [comment]
> I've simulated about 10 orders as of now and the amount in mollie's payment screen has always matched the amount in my basket / summary. Thus, I pressume that it works. From what I can tell, the default value for gift wrapping has caused it, given that I haven't used any module or the likes.

Can you try to enable it, set it to 0, then disable it? Maybe you can avoid changing the code that way.
I am going to try to find out whether this is a PrestaShop bug and if so, try to provide a workaround from the module itself, so you can keep updating safely.

**Comment by firstred** [comment]
> Speaking of which, I was actually about to reiterate on that. To keep it short, I'm currently struggling with the very same problem. After all, that's still what's keeping me from using the orders API. I've once again disabled "Send mails when Bankwire pending" and whether I select "open" or "paid" in mollie's bankwire payment with my test profile, it refuses to send the mollie generated bankwire e-mails, which I can perfectly receive in the payments API.

Have you tried this with version 3.3.3? We discovered a few things in the new Orders API that would prevent the module from keeping the old behavior, but should be fine since the adjustments we made in 3.3.3. Nevertheless we're going to test this specific case again, we might have forgotten something.

**Comment by Apury** [comment]
> > I've simulated about 10 orders as of now and the amount in mollie's payment screen has always matched the amount in my basket / summary. Thus, I pressume that it works. From what I can tell, the default value for gift wrapping has caused it, given that I haven't used any module or the likes.
> 
> Can you try to enable it, set it to 0, then disable it? Maybe you can avoid changing the code that way.
> We are going to try to find out whether this is a PrestaShop bug and if so, try to provide a workaround from the module itself, so you can keep updating safely.

Oh! that was what I meant by making it less 'forgettable' given that I might one day want to enable gift wrapping but changed mollie's .php line and wonder why it acts up. Thus, I've just set the wrapping price to 0€, which had the same effect as editing the .php file.

**Comment by Apury** [comment]
> > Speaking of which, I was actually about to reiterate on that. To keep it short, I'm currently struggling with the very same problem. After all, that's still what's keeping me from using the orders API. I've once again disabled "Send mails when Bankwire pending" and whether I select "open" or "paid" in mollie's bankwire payment with my test profile, it refuses to send the mollie generated bankwire e-mails, which I can perfectly receive in the payments API.
> 
> Have you tried this with version 3.3.3? We discovered a few things in the new Orders API that would prevent the module from keeping the old behavior, but should be fine since the adjustments we made in 3.3.3. Nevertheless we're going to test this specific case again, we might have forgotten something.

I indeed have tried it with version 3.3.3. What would be the desires way of setting up the "Send mails when Bankwire pending" status anyways if one plans on using it with mollie? Same applies to "Status for Bankwire pending payments". It might aswell just be me having misconfigured it. But as of now, regardless of which settings I choose, I don't receive any of the e-mails with mollie's bank-wire information and thus, am unable to for example, offer Klarna.

**Comment by firstred** [comment]
Hi @Apury,

You can try this beta of the new version if you'd like: [mollie-v3.3.4-beta.1.zip](https://github.com/mollie/PrestaShop/files/2771047/mollie-v3.3.4-beta.1.zip)
We noticed that PrestaShop very often sees the bankwire module as the owner of the email template, thereby inserting other values than expected. We are now overriding that in the new version.
Note that the "enable email" option was merely meant to send additional information whenever a customer chooses the "bank transfer" option. The Mollie API **always** sends an email with instructions on how to make the bank transfer, so you can always turn the email option off if you don't need to add additional information. Hope that helps!

**Comment by Apury** [comment]
This one seems to work flawlessly as far as I can judge by using the test api. I've selected 'open' as the payment status, and got this, expected reply.

> Welcome back
> We have not received a definite payment status. You will be notified as soon as we receive a confirmation of the bank/merchant.

I'm not sure whether this is going to be the message that customers will receive who pay via bank transfer but if that's the case, I'd probably wish for a seperated .tpl file just for bank-wire payments, so that the default 'We have not received a definite payment status', in case of some sort of problem can stay whereas the wire payment.tpl file could be modified to give customers a better idea of what to do. 

But as I said, I'm still waiting for my VAT number (bureaucracy ..) and as of now am unable to test the wire payment in a live environment to see how it actually behaves. Thus, this might be irrelevant. Nonetheless, the instruction e-mail is now being properly sent even with the orders API. Thank you!

**Comment by firstred** [comment]
PrestaShop has a built-in way to use your own templates.

By navigating to your theme's folder and adding the files you want to change you can override what is being displayed.
In order to override the return page on 1.6 you can copy the file `/modules/mollie/views/templates/front/mollie_return.tpl` to `/themes/<your theme>/modules/mollie/views/templates/front/mollie_return.tpl` and start changing the template.

**Comment by firstred** [comment]
Marking as solved since v3.3.4. Don't hesitate to open a new issue if you need more help!
