### ISSUE TITLE
Mollie version 3.3.1 and 3.3.0 problem, no payment options

### ISSUE THREAD

**Issue by Dogzine** [mollie/PrestaShop#77]
### Expected behavior
When customer wants to pay payoption appear

### Actual behavior
None of the options besides "payment by banktransfer" appear

### Steps to reproduce the behavior
Tried to de-install and re-install,  tried to downgrde to 3.3.0, but only downgrading to 3.2.0 worked..

### Environment
* PrestaShop version: 1.6.1.19 (replace this with the full version you are using).
* Mollie module version: 3.3.1 (replace this with the full version you are using).

**Comment by dragonfly4** [comment]
Check https://github.com/mollie/PrestaShop/issues/73

I had the same issue.

**Comment by firstred** [comment]
Hi @Dogzine,

Thanks for opening this issue! It looks like it is a duplicate of #73, so let's continue over there. Have you tried the recommendations from the following comment? https://github.com/mollie/PrestaShop/issues/73#issuecomment-434831493
