### ISSUE TITLE
after create an credit-invoice FatalThrowableError

### ISSUE THREAD

**Issue by Frankyet** [mollie/PrestaShop#771]
after create an credit-invoice FatalThrowableError

in back-office create an credit-invoice by returning articles, orders that is payed with mollie module.

### Environment
* PrestaShop version: 1.7.8.7
* Mollie module version: 6.0.1
* PHP version: 7.4.33

![Mollie error](https://github.com/mollie/PrestaShop/assets/22242384/69042ead-10cd-43f6-90c8-0b6338ed8144)
![Mollie-error](https://github.com/mollie/PrestaShop/assets/22242384/212d7e32-5633-4811-b7df-650834e870e7)

**Comment by justelis22** [comment]
Hello @Frankyet,

Thank you for creating the issue, we will take a look at this and make sure it is fixed ASAP.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi @Frankyet,
Thanks for waiting!

We will include the fix in the upcoming release 6.0.2.

Best Regards,
Invertus Support team.

**Comment by Nux007** [comment]
@justelis22 Confirmed fixed and working :-)

![image](https://github.com/mollie/PrestaShop/assets/17247565/781e25e8-a61b-4628-87da-08905d98e1cd)

**Comment by justelis22** [comment]
Glad to hear that!

I am closing this issue, but if you see any bugs with the beta release, please open a new issue and report it.

Thanks!

Best Regards,
Invertus Support team.

**Comment by Frankyet** [comment]
No more faults for my also.
