### ISSUE TITLE
Use of deprecated hook actionFrontControllerAfterInit instead of actionFrontControllerInitAfter

### ISSUE THREAD

**Issue by wouwouwou** [mollie/PrestaShop#782]
### Expected behaviour
No PHP warning where the use of the deprecated hook is mentioned.

### Actual behaviour
PHP warning appears containing the following:
```
The hook "actionFrontControllerAfterInit" is deprecated, please use "actionFrontControllerInitAfter" instead in module "mollie".
```

### Steps to reproduce the behaviour
Looking at the PHP error log after loading any page in the front-office.

### Environment
* PrestaShop version: 8.0.5
* Mollie module version: 6.0.2
* PHP version: 8.2 (php-fpm)

### Other remarks
I have already tried solving this in production (yes, I know, risky and potentially breaking) by:

- Repositioning the module in the back-office through the webinterface
- Changing `actionFrontControllerAfterInit` to `actionFrontControllerInitAfter` in `getHooks()` in `subscription/install/HookInstaller.php/`
- Chaning `hookActionFrontControllerAfterInit()` to `hookActionFrontControllerInitAfter()` in `mollie.php`

This issue seems is non-breaking as far as I can see. Nevertheless, fixing this would clean up error logs.

**Comment by justelis22** [comment]
Hi there @wouwouwou,

We are planning to include the fix in the upcoming release.

Once it is done, we will let you know!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,
Thanks for waiting!

The issue should be fixed in the new release. You can try it out here - https://github.com/mollie/PrestaShop/releases/tag/v6.0.4-beta

Your feedback is greatly appreciated.

Best Regards,
Invertus Support team.
