### ISSUE TITLE
Latest version mollie incomptible with Hummingbird theme

### ISSUE THREAD

**Issue by tajriba** [mollie/PrestaShop#785]
### Expected behavior
Add to cart working

### Actual behavior
Error in error.ts with Hummingbird theme

### Steps to reproduce the behavior
Install the latest mollie module, with hummingbird theme active on the product page you can't add your product cart without errors javascript.

<img width="1479" alt="Scherm­afbeelding 2023-08-22 om 09 31 03" src="https://github.com/mollie/PrestaShop/assets/68469531/fead368b-d477-4b4b-a339-33f01dafd979">

### Environment
* PrestaShop version: 8.0.1
* Mollie module version:5.4.0 upgraded to 6.0.X
* PHP version:8.1

**Comment by justelis22** [comment]
Hi there @tajriba,

We have checked the case and unfortunately, the error can not be replicated from our testing environment.
Would it be possible to provide more information and access to your environment (back office and FTP credentials). You could send them to our support email at support@invertus.eu.

Also, there could be some issues during the upgrade, so please try to reset the module to see if the issue still happens.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @tajriba,

We have also released a bug fix in the latest version - https://github.com/mollie/PrestaShop/releases/tag/v6.0.3
Please try to upgrade the module to see if that helps, however we are not entirely sure that this is related to your exact case, as we would still need some additional details.

Best Regards,
Invertus Support team.
