### ISSUE TITLE
JQuery error - Unable to load popup on product add to cart button click

### ISSUE THREAD

**Issue by Nux007** [mollie/PrestaShop#786]
### Expected behavior
When in a product page and adding the product to the cart, it should display the popup "continue shopping' or 'Go to cart' like in this image (The Mollie module was deactivated in order to take this screenshot):

![image](https://github.com/mollie/PrestaShop/assets/17247565/27325963-1460-41ca-8f22-7ab524ddfe26)

### Actual behavior
The popup window simply not appear (When Mollie module is activated again)

![image](https://github.com/mollie/PrestaShop/assets/17247565/3fd8bd37-44bc-44c9-8973-8391dff5b80c)

No popup windows on add to cart button clicked and this warning is in the dev console:

![image](https://github.com/mollie/PrestaShop/assets/17247565/c4f3be34-39de-49d7-8693-3537cab2fb51)

### Steps to reproduce the behavior
Activate the module + add a product to cart using the product page (does not appear in catalog).
When deactivating the module, to error disappear and the confirmation window is shown.

### Environment
* PrestaShop version: 1.7.8.5
* Mollie module version: 6.0.2
* PHP version: 7.4.28

**Comment by justelis22** [comment]
Hi there,

It seems like the exception is most likely related to your PrestaShop theme, although we have found an issue that could cause errors like these, so we have improved the exception handling.
We have included the fix to the latest module version - https://github.com/mollie/PrestaShop/releases/tag/v6.0.3

Please let me know if that helps in your case, but please keep in mind that you might not see the error, although the theme might still conflict with the Mollie module.

Best Regards,
Invertus Support team.

**Comment by Nux007** [comment]
Hello,

You are the best, that fixed my problem :-D thanks !
