### ISSUE TITLE
PayPal reference code is missing with v5.4.0 in Prestashop (any Workaround?)

### ISSUE THREAD

**Issue by TJatFJS** [mollie/PrestaShop#802]
### Expected behavior
The PayPal reference code in v5.4.0 should be sent to Prestashop as this is relevant information for accounting.

### Actual behavior
Hi, our accounting department has the problem that with the module version v5.4.0 the PayPal reference code is not transferred to Prestashop.

Previously, we had PayPal PLUS as a payment service provider and the PayPal reference code was written in "transaction_id" in the database entry "xyz_order_payment" and specified in the order, so that we could automatically match the data from Prestashop and PayPal.

With Molli v5.4.0, the Mollie transaction number (e.g. tr_123456789x) is now written in "transaction_id". This would not be a problem for us either, if the PayPal reference code is at least passed in some other place.

According to Mollie support, the "problem" is solved with the current version 6.x.x, however we are still trapped on Prestashop 1.5.x for a while, so we have to live with v5.4.0 for this time.

In the Mollie backend, the PayPal reference code is stored, but cannot be exported via the export function. Unfortunately, I have not found anything in the Prestashop database entries (mol) either.

So the question is: Is there possibly a workaround to transfer the PayPal reference code to Prestashop in any way with Prestashop 1.5.x and Mollie v5.4.0 so that we can make a suitable mapping for our accounting?

### Steps to reproduce the behavior
Every order with PayPal triggers the problem for us.

### Environment
* PrestaShop version: 1.7.5.2
* Mollie module version: 5.4.0
* PHP version: 7.2

**Comment by SimonasB88** [comment]
@TJatFJS hey, thanks for reaching us!

We could check the issue on your host, if you could send us your FTP/SSH credentials, credentials to your database, Back-Office admin email and password. Send everything to the support@invertus.eu. 

Thanks.

**Comment by justelis22** [comment]
Hi there @TJatFJS,
Thanks for waiting!

Could you please clarify how do you export the information so that the payment transaction ID is included? Could you please send us the steps on how to export payment information so that we can better understand it?

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @TJatFJS,

Just in case you have missed it, could you answer my previous message?

Best Regards,
Invertus Support team.
