### ISSUE TITLE
Uncaught League\Container\Exception\NotFoundException: Alias (Mollie\Handler\RetryHandlerInterface)

### ISSUE THREAD

**Issue by GigaWeb2023** [mollie/PrestaShop#809]
FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught League\Container\Exception\NotFoundException: Alias (Mollie\Handler\RetryHandlerInterface) is not being managed by the container in /var/www/vhosts/9mmenergy.be/httpdocs/modules/mollie/vendor/league/container/src/Container.php:266

### Expected behavior
Get the complet transaction and final page after payment

### Actual behavior
Not getting back the paid order

### Steps to reproduce the behavior
using a payment method

### Environment
* PrestaShop version: 1.7.8.10 
* Mollie module version: latest
* PHP version: 7.4

**Comment by SimonasB88** [comment]
@GigaWeb2023 hey, sorry for a delay. 
Could you send us your FTP/SSH and database credentials to support@invertus.eu? The guys will take a look.

Thanks.

**Comment by GigaWeb2023** [comment]
> @GigaWeb2023 hey, sorry for a delay. Could you send us your FTP/SSH and database credentials to [support@invertus.eu](mailto:support@invertus.eu)? The guys will take a look.
> 
> Thanks.

Hi, 
we sent to the mail address all the credentials, did you get them ? 

Thanks,

**Comment by justelis22** [comment]
Hi @GigaWeb2023,

Yes, we have received the credentials.
As soon as we have analyzed the issue and get more information, I will get back to you with an update.

Best Regards,
Invertus Support team.

**Comment by GigaWeb2023** [comment]
Great, thank you,

this is the new url of the shop : https://9mmenergy.be/shop

**Comment by justelis22** [comment]
Hey @GigaWeb2023,
Thanks for waiting!

The issue was fixed by our team and will be included in the upcoming release.
We are currently in the testing phase, so if everything is good, we should release it in the upcoming weeks.

Best Regards,
Invertus Support team.

**Comment by GigaWeb2023** [comment]
Thank you for the update, 
but actuallly we have this on a real e-shop that is going to be online very soon.
Do you have any idea on when this fix will be available ? 

Best regards,

**Comment by justelis22** [comment]
Hi there,
Thanks for waiting!

The issue should be fixed in the new release. You can try it out here - https://github.com/mollie/PrestaShop/releases/tag/v6.0.4-beta

Your feedback is greatly appreciated.

Best Regards,
Invertus Support team.
