### ISSUE TITLE
payment option sepa (overboeking) throws error

### ISSUE THREAD

**Issue by jestainternetsolutions** [mollie/PrestaShop#81]
When customers want to checkout with the overboeking option it throws a blanc page with text  "Onherstelbare fout"

this problem popped up after updating mollie module

* PrestaShop version: 1.7.3.1
* Mollie module version: 3.3.1

**Comment by snowycatsoftware** [comment]
Hi @jestainternetsolutions ,

What message are you getting if you enable debug mode // check the log files? Make sure you enable debug mode on the Mollie config  page as well and set it to "all".

Kind Regards

**Comment by jestainternetsolutions** [comment]
Mollie::validateMollieOrder - Secure key does not match

**Comment by snowycatsoftware** [comment]
Hi @jestainternetsolutions ,

We just ran a test on a clean PS 1.7.3.1 installation. We can not reproduce this error. Neighter with cache enabled or disabled. Could you please contact us via info[at]snowycatsoftware.com so we can further investigate this issue?

Kind Regards
