### ISSUE TITLE
Error message: There is no order with this ID.

### ISSUE THREAD

**Issue by Thomas220815** [mollie/PrestaShop#810]
### Expected behavior
I expected the order confirmation page but always get this error message in Test and Live envirement.

### Actual behavior
Error message: There is no order with this ID.

### Steps to reproduce the behavior
1. create an order for example on site:
https://b2b.fjschuette.stagetxks.de/gb
with user:
user: daniel.renier2012@gmail.com
pw: Start12341122

please see this video: https://www.screenpresso.com/=U63X

### Environment
* PrestaShop version: 8.0.4
* Mollie module version: 6.0.3
* PHP version: 8.1

**Comment by SimonasB88** [comment]
@Thomas220815 Hey, sorry for delayed reply. Seems like an issue, specifically on one of the latest Prestashop versions  (probably).
Can we debug on your host if you could provide us FTP/SSH credentials, and access to your shop's database? Send everything to support@invertus.eu.

Thanks.

**Comment by justelis22** [comment]
Hi there,
Thanks for waiting!

The issue should be fixed in the new release. You can try it out here - https://github.com/mollie/PrestaShop/releases/tag/v6.0.4-beta

Your feedback is greatly appreciated.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,

Closing the issue, as there were no updates for some time.

Best Regards,
Invertus Support team.
