### ISSUE TITLE
Error occurred: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_employee' in 'field list'	Mollie

### ISSUE THREAD

**Issue by Hophopdidjou** [mollie/PrestaShop#815]
### Expected behavior

Dear I'm on PRESTASHOP 8.1 and have many LOG ERROR : Erreur (3) > Error occurred: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id_employee' in 'field list' | Mollie 

And create many trouble in the front for customers, many transactions not going to the end with this so we lost transaction,
what I just see is to many orders and customers abandoned cart because I have Log error and I don't know why. 

Also after I change Order statuts of one order IN PREPARATION REDAY FOR DELIVERY etc ... , systematically, Mollie change the statut of this order to payment accepted and resend once again an email accepted payment to the customer.

For information,  I have re-upload and re-install the last module version of mollie and is going automatically in TEST and not live, but nothing prevent, and trouble to change, due this I have transaction and order in Test and not in live '( is it really need to have test ) and can we have the live direct after install to not lost customers and orders 

Also why add like the subscription in the module  who made also many problem and that's not include from Mollie but only by other services ( for our shop we don't need this ) for nothing. 

but I see that the subscription is on the Customer account, right column etc ... this is to many too surcharge and maybe not help to have a stable module without subscription  

-- | --

### Steps to reproduce the behavior

Going on the log on Admin and see when the shop is on line and ready to use that appears many log with the errors 

### Environment
Prestashop 8.1.0
Mollie  v6.0.3

**Comment by Hophopdidjou** [comment]
Also after I change Order statuts of one order IN PREPARATION REDAY FOR DELIVERY etc ... , systematically, Mollie change the statut of this order to payment accepted and resend once again an email accepted payment to the customer.

**Comment by justelis22** [comment]
Hi there,
Thank you for contacting us and reporting your issue.

We will check it and get back to you as soon as possible.

Best Regards,
Invertus Support team.

**Comment by Hophopdidjou** [comment]
Dear, Thank You :) 
Maybe to help you, Here's 2 screenshots I got on the log ( I have from this morning )
Best Regards 
:)
<img width="1268" alt="Capture d’écran 2023-09-25 à 11 35 50" src="https://github.com/mollie/PrestaShop/assets/145848969/df571fba-0aa2-42c6-8001-321925f88d44">
<img width="1226" alt="Capture d’écran 2023-09-25 à 11 35 36" src="https://github.com/mollie/PrestaShop/assets/145848969/48aa21a3-6184-4ec7-9d37-b19edf3aaed5">

**Comment by Hophopdidjou** [comment]
Dear, 
by looking to understand the error I find this issue on prestashop GitHub  : Order History not updated #33238

where the problem state appears and the error indicate id_employee missing 

 i have also add the same on mollie_payments because it was missing,
ALTER TABLE `xx_mollie_payments` ADD `id_employee` INT NULL AFTER `updated_at`;
and also in mol_payment_method 
ALTER TABLE `xx_mol_payment_method` ADD `id_employee` INT NULL AFTER `id_shop`;

so I will feedback to you if the error is resolve with this but this is strange to not have this when we install the module .. 
well hope to read you soon 

Also I have deactivate the mail statut : send and email when accepted payment at this moment 
because we are LIVE not Test and developers, so as we have problem with the order state for our customers we will not continue to have this bug.

**Comment by justelis22** [comment]
Hi there,
Thanks for waiting!

Could you please send us access to your back office and FTP to our email support@invertus.eu?

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @Hophopdidjou,

I have written you an email asking if the new Mollie module fixes the issue for you.

Waiting for your reply!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,

As this issue has been inactive for some time now, I will close it.

If the issue can still be recreated, please let us know, and it will be reopened.

Best Regards,
Invertus Support team.
