### ISSUE TITLE
Payment method not on invoice

### ISSUE THREAD

**Issue by RoyPG** [mollie/PrestaShop#82]
### Expected behavior
{$payment->payment_method} is not shown on invoice and delivery slip.
Instead it shows Mollie Payment Module ( file pdf/invoice.payment-tab.tpl )

### Actual behavior
I payed with ideal, but this is not shown on invoice.

### Environment
* PrestaShop version: 1.7.4.3
* Mollie module version: 3.3.1

**Comment by firstred** [comment]
Hi @RoyPG,

Are you trying to customize the tpl file? We have tried to reproduce this with the default templates of 1.7.4, but always ended up with the payment code (`ideal`, `inghomepay`, etc.) on our invoices.

Can you try restoring the default template file or if that does not work, share the code that you have so we can have a look at it?

**Comment by RoyPG** [comment]
Hi Michael,
The code is original ( invoice.payment-tab.tpl)
<table width="100%" border="0">
				{foreach from=$order_invoice->getOrderPaymentCollection() item=payment}
					<tr>
						<td class="right small">{$payment->payment_method}</td>
						<td class="right small">{displayPrice currency=$payment->id_currency price=$payment->amount}</td>
					</tr>
				{/foreach}
			</table>

The strange thing is that the orderconfirmation by mail is correct ( payment : ideal )

**Comment by RoyPG** [comment]
Invoice shows module name as payment method (PDF)

**Comment by firstred** [comment]
@RoyPG Can you contact us at info@snowycatsoftware.com? It is difficult to find out what is happening on your environment via GitHub.

I just tried to copy and paste that code snippet and it looks exactly as designed:
![screenshot from 2018-11-23 17-07-25](https://user-images.githubusercontent.com/6775736/48952438-71bea680-ef42-11e8-82eb-0483113e3f32.png)
