### ISSUE TITLE
Exclude shipping method from Orders API

### ISSUE THREAD

**Issue by Heartz66** [mollie/PrestaShop#83]
Would be cool to exclude the shipping method from being pushed to the Orders API.

<img width="827" alt="screen shot 2018-11-17 at 21 09 47" src="https://user-images.githubusercontent.com/8833887/48665361-3721bd80-eaad-11e8-9e83-5a35a9a39802.png">

**Comment by firstred** [comment]
Marking as solved since v3.3.3. Feel free to reopen by leaving a comment.
