### ISSUE TITLE
Error message: There is no order with this ID.

### ISSUE THREAD

**Issue by fuchsbart** [mollie/PrestaShop#830]
### Expected behavior
The order confirmation page is loaded after a test payment when "Paid" is selected as the result.

### Actual behavior
No matter what result is chosen for a test payment, the error always occurs: There is no order with this ID.

### Steps to reproduce the behavior
Install the module with 1.7.8.7 and try to buy with test mode.

### Environment
* PrestaShop version: 1.7.8.7
* Mollie module version: 6.0.4
* PHP version: 7.3.33

**Comment by justelis22** [comment]
Hi there @fuchsbart,

Could you please send us access to your back office and FTP credentials to support@invertus.eu?
We are not able to recreate the issue from our side, so we would like to debug your shop to identify the issue.

Waiting for your reply!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,

As we have not received any updates, we are going to close the issue.

If you are still facing it, don't hesitate to reach out to us and we will reopen it!

Best Regards,
Invertus Support team.
