### ISSUE TITLE
Exception thrown by module mollie on upgrade. Property OrderState->name is empty.

### ISSUE THREAD

**Issue by Gozylatech** [mollie/PrestaShop#837]
### Expected behavior
Update

### Actual behavior
Exception thrown by module mollie on upgrade. Property OrderState->name is empty.

### Steps to reproduce the behavior
Update 6.0.3 to 6.0.4

### Environment
* PrestaShop version: 1.7.8.7
* Mollie module version: 6.0.3
* PHP version: 7.4

**Comment by justelis22** [comment]
Hi @Gozylatech,
Thanks for waiting!

We will check this case and get back to you as soon as possible.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello @Gozylatech,

The fix for this issue will be included in the next release. For your case, we would recommend resetting the Mollie module to create new order states.

Keep me updated on how it goes!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,

As this will be included in the new release, I am going to close the ticket.
The solution for now would be resetting the module to create new order statuses.

If there is anything else, do not hesitate to reach out!

Best Regards,
Invertus Support team.
