### ISSUE TITLE
translation of payment method for invoice

### ISSUE THREAD

**Issue by pedalracer** [mollie/PrestaShop#86]
### Expected behavior
Payment method should be translatable (e.g. for invoice).

### Actual behavior
payment method "klarnapaylater" e.g. is not translatable

Pay later. = Klarna: Rechnung

Despite the string is there to be translated/renamed in bo/translations the English name appears on German invoice.

### Steps to reproduce the behavior
Describe the steps to reproduce the behavior here (replace this line).

### Environment
* Thirtybees 1.0.7 (PS1.6)
* Mollie module version: 3.3.1.

**Comment by firstred** [comment]
Hi @pedalracer 

This feature has been scheduled for February 2019 (version 3.4.0). We'll make sure you can translate the payment method on your invoice. Note that the module will likely still default to using the codes, since so many bookkeeping integrations currently depend on it.
