### ISSUE TITLE
Ordernumber is not sending to paypal/creditcard transactions

### ISSUE THREAD

**Issue by tajriba** [mollie/PrestaShop#871]
### Expected behavior
Use order number in transaction description.

### Actual behavior
No order number.

### Steps to reproduce the behavior
Place order with paypal/creditcard.
<img width="612" alt="Scherm­afbeelding 2024-01-03 om 11 45 16" src="https://github.com/mollie/PrestaShop/assets/68469531/65451d32-cc7e-47d4-906b-d027ad9388e0">

### Environment
* PrestaShop version: 1.7.6
* Mollie module version: 604
* PHP version: 7.3

**Comment by justelis22** [comment]
Hi there @tajriba,

I have just tested the description on our test environment, the same as in your screenshot, and it is being sent to Mollie from PrestaShop:
![image](https://github.com/mollie/PrestaShop/assets/103486043/e0d2adc9-1e18-46e8-8d27-55ee0f706718)
![image](https://github.com/mollie/PrestaShop/assets/103486043/65cd4f44-48f4-4e26-ba54-e7e9e9eb9393)

Could you please clarify where is it not being sent? Do you see any errors in the PrestaShop error logs?

I am waiting for your reply!

Best Regards,
Invertus Support team.

**Comment by tajriba** [comment]
Hi @justelis22 ,

For your information: We use payment fee also as setting:
<img width="978" alt="Scherm­afbeelding 2024-01-08 om 15 16 54" src="https://github.com/mollie/PrestaShop/assets/68469531/c37f1c94-d174-49b3-89d7-a637aca100d4">

**Comment by justelis22** [comment]
Hi @tajriba,

I have copied the same values as you sent to us.
I am not able to see any issues on my side, perhaps it would be possible for you to send us access to your shop to us? We would need FTP and back office credentials to debug the issue on your shop.
You can send the details to support@invertus.eu.

Best Regards,
Invertus Support team.

**Comment by tajriba** [comment]
Sorry, this problem is in our custom code inside the mollie module due of transfering some extra data to the email order config. Close issue please.

**Comment by justelis22** [comment]
Hi @tajriba,

Thank you for the information, I am closing the issue.

If anything else, do not hesitate to reach out!

Best Regards,
Invertus Support team.
