### ISSUE TITLE
Manual order gives me taxRulesGroupId must be of type int null given error

### ISSUE THREAD

**Issue by joujou333** [mollie/PrestaShop#872]
### Expected behavior
Creating the order without error

### Actual behavior
Getting error:

Mollie\Provider\TaxCalculatorProvider::getTaxCalculator(): Argument #1 ($taxRulesGroupId) must be of type int, null given, called in /home/wrufwqck/public_html/modules/mollie/src/Provider/PaymentFeeProvider.php on line 88
[TypeError 0]

### Steps to reproduce the behavior
In backoffice create a manual order and assign the payment method to Mollie.

### Environment
* PrestaShop version: 8.1.3
* Mollie module version: 6.0.4
* PHP version: 8.2.13

When creating the order as customer as normal, the module works just fine.

**Comment by joujou333** [comment]
Sorry, i think i made a issue too soon.
Could this be the issue? https://github.com/mollie/PrestaShop/wiki/Order-creation

Because the order is created first instead of the other way around

**Comment by justelis22** [comment]
Hi there @joujou333,

We will check this case and get back to you as soon as possible.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
@joujou333,

We have discussed this internally and it should not be possible to create orders manually from the back office, there are a lot of moving parts, and it would be complex to make the module function in such a way.

Let me know if you have any other questions!

Best Regards,
Invertus Support team.

**Comment by joujou333** [comment]
Hi @justelis22 ,

Thanks for your rapid response.
Ahh I were already afraid of it that it wont work.

Issue can be closed then :)

**Comment by joujou333** [comment]
I did something nasty to not calculate the paymentfee and tax for it.
On file modules/mollie/src/Provider/PaymentFeeProvider.php

I commented the lines 88-115. So the payment fee is always 0, which is not a problem for now.
We get the the email and the working payment link, as expected.

**Comment by justelis22** [comment]
Hi there @joujou333,

This manual order creation flow is not maintained as it seems. I will have to talk with the Mollie team to see if this is something we will develop.
As soon as we have some information, I will post it here.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @joujou333,

We have talked with the Mollie team again and we will fix this feature.
The fix is planned to be added to the upcoming release, but if the issue is bigger than expected, we might put it on hold for the next release.

I will inform you regarding updates!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello there,

The fix was added to 6.1.0.

Best Regards,
Invertus Support team.
