### ISSUE TITLE
Clear cache from console gives warnings and crashes.

### ISSUE THREAD

**Issue by sharkooon** [mollie/PrestaShop#873]
### Expected behavior
Clearing the cache from console with: `php ./bin/console cache:clear`
I expect the following message from console:
`[OK] Cache for the "dev" environment (debug=true) was successfully cleared. `

<img width="863" alt="Scherm­afbeelding 2024-01-15 om 14 17 49" src="https://github.com/mollie/PrestaShop/assets/533123/29cdb591-6aa9-4556-a2f3-1cb229e54be6">

### Actual behavior
Clearing the cache from console with: `php ./bin/console cache:clear`

```
In PsrCachedReader.php line 198:
                                                                                                                          
  Warning: filemtime(): stat failed for /var/www/html/vendor/prestashop/autoload/src/Autoloader.php(113) : eval()'d code 
```
<img width="942" alt="Scherm­afbeelding 2024-01-15 om 14 16 23" src="https://github.com/mollie/PrestaShop/assets/533123/5c37d256-e013-4b73-8863-806db1d5365c">

### Steps to reproduce the behavior
- Install mollie module and enable it.
- from console: `php ./bin/console cache:clear`

### Environment
* PrestaShop version: 8.1.3
* Mollie module version: 6.0.4
* PHP version: 8.1.27

### Additinal information
- tested on fresh installed prestashop
- when disabling mollie module, clear cache works correctly from console.

The following changes works:

> modules/mollie/subscription/Controller/AbstractAdminController.php
> `namespace Mollie\Subscription\Controller;`
> to:
> `namespace Mollie\Subscription\AdminController;`

> modules/mollie/src/Controller/AbstractMollieController.php
> `class AbstractMollieController extends \ModuleFrontControllerCore`
> to
> `class AbstractMollieController extends ModuleFrontControllerCore`

**Comment by justelis22** [comment]
Hi there @sharkooon,

I have forwarded the issue to our development team. As soon as we have some updates I will let you know.

Best Regards,
Invertus Support team.

**Comment by sharkooon** [comment]
My suggested changes breaks other stuff, so don't use it. It only works for clear cache from console: php ./bin/console cache:clear

**Comment by justelis22** [comment]
Hi @sharkooon,

The issue can be recreated with native PrestaShop modules as well, as the solution works only when all of the modules are deleted.
It seems to be a PrestaShop issue in general, I would suggest creating a ticket there.

Best Regards,
Invertus Support team.
