### ISSUE TITLE
Authentication error in PrestaShop 1.7.5

### ISSUE THREAD

**Issue by dswart** [mollie/PrestaShop#88]
When configuring the Mollie-module in PrestaShop 1.7.5, after entering an API-key, an error occurs trying to display the payment methods.

### Expected behavior
No authentication error should be thrown when entering your API-key, and the payment methods should be displayed.

### Actual behavior
When configuring the module, the list of payment methods cannot be shown due to the following error:
```
Error executing API call (401: Unauthorized Request): Missing authentication, or failed to authenticate. Documentation: https://docs.mollie.com/guides/authentication
```

### Steps to reproduce the behavior
* Install the module
* Enter an API-key (test or live)
* See error message

### Environment
* PrestaShop version: 1.7.5.0
* Mollie module version: 3.3.2

**Comment by firstred** [comment]
Hi @dswart, thanks for opening this issue.

This error occurs when there is a communication issue between the API and your server. You can test this by sending an empty request to one of the endpoints or leaving out the headers, that should result in the same error.
I've seen PrestaShop 1.7.5 interfere a lot with the way it communicates with several APIs, Mollie's being just one of them, but every single issue we've seen so far had a different cause. Unfortunately we haven't been able to reproduce this on our own test environments, but we do have received a relatively high amount of reports for PrestaShop 1.7.5 compared to previous versions, which could be a sign something's not as stable as it used to be.
Therefore I think you'd be helped a lot quicker if someone could have a look at your environment. You can reach the support team through this page: https://www.mollie.com/en/contact

And if you happen to have found a reproducible case, don't hesitate to share it with us. We'd be happy to have a look!

**Comment by dswart** [comment]
Hi @firstred, thanks for you reply.

Yesterday, I noticed that the change was not saved properly, causing the error. This would perhaps be more of a UI-issue, as clicking enter from the text field does not work. Saving with the button at the end of the page fixed the issue, so for now everything is fine :) Thanks again!

**Comment by firstred** [comment]
That is some great feedback, thanks!

Do you see any JavaScript errors in your developer tools' console? We're using the built-in HelperForms with a custom `onSubmit` event, so they should normally prevent you from submitting by pressing `Enter`, but this can be very fragile. I can confirm that a super fresh vanilla install of PrestaShop 1.7.5 prevents the submit when pressing enter, but causing a few JavaScript-errors on the page changes the behavior to just submit the form and indeed does NOT process the entered information w/o any kind of feedback. Madness!

@snowycatsoftware What shall we do? Rebuild everything with React? :stuck_out_tongue: 
That would be really awesome and prevent tons of errors, make 1.5 - 1.6 compatibility a lot easier etc. etc., but I am not sure if this would pass Addons' technical validation.

**Comment by firstred** [comment]
As a side note: I noticed the [official GDPR module](https://addons.prestashop.com/en/legal/32323-official-gdpr-compliance-by-prestashop-15-16.html) has been built, for the most part, with Vue.js, so it looks like the platform is opening up to allowing JavaScript frameworks.
