### ISSUE TITLE
Status not sent to PrestaShop ?

### ISSUE THREAD

**Issue by tbnv** [mollie/Prestashop#9]
Hello,

I installed the Mollie plugin on our PrestaShop website. It is using the test API key right now. When completing an order, we can choose the payment status we want to send to PrestaShop. But it looks like it doesn't work.

When coming back to PrestaShop, a message like "we didn't receive payment information yet, you will be notified when the status is updated" appears and the shopping cart still contains the items. In the backend, the status is always "waiting for payment" even if we asked the status to be "paid" on the Mollie test payment page.

Do you think it's a problem with our install or the plugin or...?

**Comment by mollierobbert** [comment]
Hi Thibaut, from the sound of it our servers are unable to reach your webhook-URL. Most likely you're running the plugin on a local server that is not accessible from the internet.

If you still can't figure out what's going wrong, please post the customer ID or profile ID so we can check our logs.

**Comment by Ron-e** [comment]
I am having the same problem and end message with setting up/testing a webshop for a friend on shared hosting, but mine doesn't even show the order in the back-end.
The order stays in the shopping cart with the customer and the back-end...
This is for a friend and not for myself, i am not comfortable posting his customer ID or profile ID here.

**Comment by Ron-e** [comment]
Now i get the message thru the mollie website that the URL http://www.domain.nl/module/mollie/webhook
id=tr_C0dE did not respond.

1. There is no module dir, but modules.
2. there is no webhook dir there?

**Comment by paetor** [comment]
Hi Ron-e, it's hard for me to debug this issue for you without being able to pinpoint your account. Could you please mail us with your issue at info@mollie.com, and I'll try to help you debug this.

**Comment by tbnv** [comment]
On my side, it looks like the problem was caused by the website being in maintenance mode, thus not reachable from mollie.com

**Comment by Ron-e** [comment]
LOL, same problem as @tbnv, so problem solved..
Sometime it are the small things you never thought of..

**Comment by paetor** [comment]
Ok cool!

**Comment by lvgunst** [comment]
We've added an entry to the FAQ about reporting payment statuses to PrestaShop: https://github.com/mollie/Prestashop#veel-gestelde-vragen
