### ISSUE TITLE
Empty bank list iDEAL on checkout

### ISSUE THREAD

**Issue by sharkooon** [mollie/PrestaShop#917]
3 weeks ago i published a fix for iDEAL empty bank list on checkout.
https://github.com/mollie/PrestaShop/pull/902

On a fresh prestashop installation 8.1.5 with mollie 6.1.0 installed and iDEAL is active. The ideal bank list on checkout is empty.

SELECT * FROM `ps_mol_payment_method_issuer`
0 results.
This commit fixes the ps_mol_payment_method_issuer table being filled when mollie module settings are saved.

To reproduce the issue for mollie v6.1.0:

empty table with: TRUNCATE ps_mol_payment_method_issuer (if table is not empty when upgrading)
save mollie settings from module
SELECT * FROM ps_mol_payment_method_issuer
what results in 0 results, no ideal bank issuers information is available.
After adding 'include' => 'issuers' to
$apiMethods = $api->methods->allAvailable(['locale' => '', 'include' => 'issuers']);
will fix it, and table is being filled with ideal issuers data for iDEAL.

Module version 6.0.5 does work! But also contains:
$apiMethods = $api->methods->allActive(['resource' => 'orders', 'include' => 'issuers', 'includeWallets' => 'applepay']);
[link to ApiService.php:120](https://github.com/mollie/PrestaShop/blob/e52bede85096e28a3a8390f2051513814c6a73ee/src/Service/ApiService.php#L120)
We dont use applepay so can't test that, probably have to add that one too.

**Comment by justelis22** [comment]
Hi there,
Thanks for waiting!

I have forwarded the issue to our development team. As soon as we have more information, I will get back to you.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
@sharkooon Hi there,

The changed were merged and will be added to the 6.2.0 release.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @sharkooon,

The issue was fixed and the beta 6.2.0 is already available.

If you can, please install it and if you have some feedback, I would highly appreciate it

Best Regards,
Invertus Support team.
