### ISSUE TITLE
Resend payment link column only has icon for some orders

### ISSUE THREAD

**Issue by wzzly** [mollie/PrestaShop#918]
### Expected behavior
No resend payment link column anymore in orders BO view, because orders are already paid when created now right?

### Actual behavior
The resend payment link icon is visible for only some orders. I don't know why for some new orders it is still there? As all orders are paid with mollie/ideal and are paid.

### Steps to reproduce the behavior
Happens to some new orders, but only a few. Don't know why.

![image](https://github.com/mollie/PrestaShop/assets/35727938/937103b0-c2d0-496d-95df-e2bb6ece31dc)

### Environment
* PrestaShop version: 1.7.8.10
* Mollie module version: 6.0.1 
* PHP version: 8

**Comment by justelis22** [comment]
Hi there,
Thank you for the information.

I will check this for you and get back with additional info as soon as possible.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi @wzzly,

I was able to recreate the case as well.

As this is not a critical issue, it will not be added to the upcoming release, but I will talk with the Mollie team to prioritize accordingly.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @wzzly,

Our development team was not able to recreate the issue, so we do not see what is causing it. However, iDeal 2.0 will be introduced in the upcoming release, so my recommendation would be to check if the issue continues with the new version as well.
If it does, we will see what else could be done.

For now, I am closing this issue, please wait for the 6.2.1 release, thanks!

Best Regards,
Invertus Support team.
