### ISSUE TITLE
Forwarding after payment not correct? Template does not work. Blank page

### ISSUE THREAD

**Issue by onlyprint** [mollie/PrestaShop#919]
### Expected behavior
Customer comes back to our site after payment and sees the confirmation page

### Actual behavior
When I process the payment at Mollie, I come back to the webshop. Here, however, the template is not loaded correctly, so that I only see the footer without styles. When I reload the URL (cmd+R), it is fine and the URL is also customized. 

####before reload
https://domain.nl/module/mollie/return?cart_id=408&utm_nooverride=1&rand=1715084657&key=9737a42fad0bff1a6a0e3d3c874f8c57&customerId=4&order_number=mol_408663a1d719464b1715084657

####after reload
https://domain.nl/order-bevestiging?id_cart=408&id_module=185&id_order=197&key=42faa0cb227ea889e7aba70e0e7f9405

### Steps to reproduce the behavior
simply place an order. Every time you pay for an order with Mollie. The problem does not occur with other payment methods

### Environment
* PrestaShop version: 1.7.8.8
* Mollie module version: 6.1.1 (I have tested various versions without success)
* PHP version: 7.4.33  (Serverinformatie: Linux #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 Server softwareversie: Apache PHP-versie: 7.4.33 Geheugenlimiet: 256M Maximale uitvoeringstijd: 240 Maximale bestandsgrootte voor uploads: 32M)

<img width="1948" alt="Bildschirmfoto 2024-05-07 um 15 57 04" src="https://github.com/mollie/PrestaShop/assets/169169388/fe8faa79-ecae-46de-905a-2bccb2fae88d">

**Comment by justelis22** [comment]
Hi there @onlyprint,

I have forwarded the information to our development team. As soon as we have more details, I will let you know.

Best Regards,
Invertus Support team.

**Comment by onlyprint** [comment]
Hello,


We have already been able to fix it ourselves. The problem was not caused by your module, but by another one that was in the footer hook. The problem is now solved. Thank you! 



Met vriendelijke groet,


Johannes Classen 

Team Onlyprint

Onlyprint.nl B.V.




+31 45 302 00 11 


***@***.*** 


www.onlyprint.nl 


Hoofdstraat 53, 6372 CP Landgraaf 

--- original message ---
On May 24, 2024 at 10:19 AM GMT+2 ***@***.*** wrote:



Hi there @onlyprint,

I can see that you have a development shop, would it be possible for you to provide us access to it? We are not able to recreate the issue, so it would be helpful to have an environment where the issue could be seen from our side.

Please send us back-office and FTP credentials to ***@***.*** and we will continue debugging the issue.

Best Regards,

Invertus Support team.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by justelis22** [comment]
Hi @onlyprint,

Thanks for letting us know!

I am closing this issue as resolved.

Best Regards,
Invertus Support team.
