### ISSUE TITLE
Orders API checkout error on 'free' product with shipping cost.

### ISSUE THREAD

**Issue by Apury** [mollie/PrestaShop#94]
Hey there! It's me again. I stumbled upon a new problem. I've created a product with a discount of 100%. Effectively rendering the price 0.00€. To go even on the product, the shipping cost will be the only price adjustment. 

However, once I check out, it throws this error at me: 

Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. Invalid amount value for field vatAmount.. Field: lines.1.vatAmount.value. Documentation: https://docs.mollie.com/guides/handling-errors. Cart Dump: { "amount": { "currency": "EUR", "value": "7.99" }, "method": "paypal", "redirectUrl": "https:\/\/XXXX.com\/module\/mollie\/return?cart_id=103&utm_nooverride=1&rand=1548503636", "webhookUrl": "https:\/\/XXXX.com\/module\/mollie\/webhook", "metadata": { "cart_id": 103, "order_reference": "XXXXX", "secure_key": "XXXXXX" }, "locale": "en_US", "billingAddress": 

The tax rule for the product is: "no tax"

The curious part is, if I combine the free product with any other product, which isn't free, in my store, the payment goes through without a problem. 

### Environment
* PrestaShop version: 1.7.3.4
* Mollie module version: 3.3.4 
* PHP version: 7.1.26 +ubuntu16.04.1+deb.sury.org+1

**Comment by firstred** [comment]
Hi @Apury 

Thanks for reporting this issue! What are the results with version 3.3.5? 
https://github.com/mollie/PrestaShop/releases

**Comment by Apury** [comment]
Oddly enough. 3.3.5 fixed #95. However, ordering the free product still results in the same error at check out.

**Comment by firstred** [comment]
Is this a discount on a single product or the whole order? I can checkout with just a shipping fee only.

**Comment by firstred** [comment]
By giving a 100% discount on the whole order (ex. shipping costs)

**Comment by Apury** [comment]
It's set up in the catalog -> products -> 'FREE product' -> Shipping panel as a "Specific price condition". 

- All currencies
- All countries
- All groups
- All customers
- Apply to all combinations
- Stating at 1 unites
- Leave initial price
- Apply a discount of 100 %

I can't find an option of whether or not the discount includes or excludes shipping in there.

**Comment by Apury** [comment]
I played around with it a little bit. 

Setting a cart wide rule for the category and setting it to 100% discount results in the same error. 

Alternatively, setting a price discount based on value (e.g. 9.99€) with the "include tax" option, also results in the same error.

**Comment by firstred** [comment]
It seems to affect all carts of which the products subtotal `<= 0`

Can you try this new beta and see if that improves anything?
[mollie-v3.3.6-beta.1.zip](https://github.com/mollie/PrestaShop/files/2800340/mollie-v3.3.6-beta.1.zip)

**Comment by firstred** [comment]
You can immediately revert to v3.3.5 if you want to. There are no database changes.

**Comment by firstred** [comment]
This issue also seems to be limited to specific price rules, catalog price rules and actual product prices set to 0. We tested this situation in the past with cart rules, but since kinds of those rules leave the original amounts and vat rates in the cart, the module was able to grab the correct amounts. The specific rules remove a lot of info from the cart object, which is why a new source was necessary, but luckily I have found one.
The newer version of the module uses this source to calculate the VAT, which should now still be correct for both free and paid products.

**Comment by firstred** [comment]
Thanks a lot for all your reports!

We knew that supporting the Orders API on PrestaShop wasn't going to be easy, but leaving it out would have potentially closed the door to new payment methods such as Klarna and future authorize/capture based payment methods on PrestaShop. Thanks to your reports we have been able to cross a lot of edge cases off the list, so thank you very much for helping us improve the module!
