### ISSUE TITLE
Klarna Pay Later/Pay Expiry/Cancellation Problem

### ISSUE THREAD

**Issue by mariuszsienkiewicz** [mollie/PrestaShop#944]
### Expected behavior

Sometimes Klarna Pay Later/Pay Now gets cancelled or expired, which is visible in order history (in Mollie Dashboard). It looks like this:

- Order created 26 April 2024 at 00:04
- Payment of type Pay Later cancelled 28 April 2024 at 00:05
- Order <order_id> has expired from status created 24 May 2024 at 00:05
- Webhook called successfully, it took 1.1 seconds 24 May 2024 at 00:05

PrestaShop should get a notification about this and reflect the cancellation/expiry status in the PrestaShop order status using probably `MOLLIE_STATUS_EXPIRED` or `MOLLIE_STATUS_CANCELED` config.

### Actual behavior

When Klarna Pay Later/Now gets expired or cancelled, our shop is indeed notified about this via webhook. However, the Mollie module sets the wrong status, "Order payment authorized" is set twice in the example above it gets reflected like this:

- Order payment authorized		2024-04-26 00:14:25	
- Order payment authorized		2024-04-26 00:08:47

It appears that the module cannot properly handle cancellation/expiry because `MOLLIE_STATUS_EXPIRED` and `MOLLIE_STATUS_CANCELED` is not used anywhere, unless I missed something in the code.

Our client (the shop owner) has lost too much money because of this bug. Please check if it works for you and if not we must have some way to get around this problem.

Plugin version: 6.1.1

**Comment by mariuszsienkiewicz** [comment]
Okay, I found the place where `MOLLIE_STATUS_EXPIRED` or `MOLLIE_STATUS_CANCELED` are used. I will debug further. If it's only a problem in our environment, I will close this issue.

**Comment by justelis22** [comment]
Hi there @mariuszsienkiewicz,

Thank you for the detailed explanation of the issue!

I have forwarded the information to our development team and as soon as I have more details, I will get back to you!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
@mariuszsienkiewicz Hey there,

Do you have any more information about the issue? We are finding it difficult to recreate the issue so additional information (perhaps steps to recreate the issue with test mode) would be helpful.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
@mariuszsienkiewicz Hey there,

Did you have some to look into this deeper? Can you confirm if this is an issue from your side or is this being caused by the Mollie module?

Thanks!

Best Regards,
Invertus Support team.
