### ISSUE TITLE
Last version not compatible with Thirthy Bees 

### ISSUE THREAD

**Issue by grbfst** [mollie/PrestaShop#947]
### Expected behavior
Mollie working

### Actual behavior
"The version of your module is not compliant with your thirty bees version.
    Unable to install module"

### Steps to reproduce the behavior
Install the latest Mollie in Thirty Bees

### Environment
* PrestaShop version: 1.6.1.999  = Thirty Bees a Prestashop Fork (thirty bees version: 1.1.0 )
* Mollie module version: 6.2.1
* PHP version: 7.4.33 

there are several checks in the code: version_compare(_PS_VERSION_, '1.7.7.0', '>='

**Comment by justelis22** [comment]
Hi there @grbfst,

The error is quite straightforward, Mollie 6.x.x will not work with a lower PrestaShop version than 1.7.7.x.

We have Mollie for PS 1.6, you can download it here - https://github.com/mollie/PrestaShop1.6/releases/tag/v4.5.4, however, it is not actively maintained anymore.

Let me know if you have any other questions!

Best Regards,
Invertus Support team.

**Comment by grbfst** [comment]
I understand the straightforward error but on the releases (https://github.com/mollie/PrestaShop) page it specifically states:
"Download the latest version of the module (the '.zip' file) via the Releases page which is compatible with PrestaShop 1.6 to 1.7."

**Comment by justelis22** [comment]
@grbfst, I see, there seems to be an issue with the URL, the readme file hasn't been updated for a file.

For PS 1.6 use the link I provided.

Best Regards,
Invertus Support team.
