### ISSUE TITLE
Orders API - The amount of the order does not match the total amount from the order line.

### ISSUE THREAD

**Issue by Apury** [mollie/PrestaShop#95]
This problem is related to this previous issue: #89 and mayhaps even to #94 

The only changes are, that the mollie version has changed to 3.3.4 and that the circumstances are different. 

This time, I'm trying to apply a 10% discount to a product, priced at 6.99€. Theoretically lowering its price to  6.29€. + 6.99€ shipping. Equals 13.28€ in total. 

Mollie however throws this error at me when I try to checkout: 

> Error executing API call (422: Unprocessable Entity): The amount of the order does not match the total amount from the order lines. Expected order amount to be €14.68 but got €13.28. Field: amount. Cart Dump: { "amount": { "currency": "EUR", "value": "13.28" },  "unitPrice": { "currency": "EUR", "value": "7.69" }, "totalAmount": { "currency": "EUR", "value": "7.69" }, "vatAmount": { "currency": "EUR", "value": "0.00" }, "vatRate": "0.00" }, { "name": "Shipping", "quantity": 1, "sku": "", "unitPrice": { "currency": "EUR", "value": "6.99" }, "totalAmount": { "currency": "EUR", "value": "6.99" }, "vatAmount": { "currency": "EUR", "value": "0.00" }, "vatRate": "0.00" } ], "payment": { "webhookUrl": } }

Oddly enough, looking at the values, there is a random 7.69€ coming from the first unitPrice value and I have no idea where it is coming from. 

The item in question is configured like this: 

Tax excluded: 9.99€
Tax included: 9.99€
Tax rule: no tax
Specific price: - 30 %
Round mode: Round up away from zero, when it is half way there.
Round type: Round on each item.
Number of decimals: 2 

PS version: 1.7.3.4
Mollie version: 3.3.4

Further testing shows, that if I don't apply a coupon, the checkout for a total of €13.98 works flawlessly.

**Comment by Apury** [comment]
Fixed in version 3.3.5.

**Comment by firstred** [comment]
Great news! Thanks for letting us know!
