### ISSUE TITLE
Question about PrestoShop account / shop registration

### ISSUE THREAD

**Issue by gsnel** [mollie/PrestaShop#956]
I don 't know where to ask it today, because mollie support is closed until monday, but I have a question:

I am using the Mollie Addon for payments. I created a copy of the webshop for testing purposes.

In the Mollie settings of the copy, a message appeared stating that the shop was linked to another shop and that to prevent issues, it would be better to unlink the store.

I did this, but now the production environment now is also no longer linked. 

![2024-07-13 16_04_51-Settings](https://github.com/user-attachments/assets/d72569f6-28bc-4b51-a5ac-e37d35feaeaf)

When I click on the "Manage linked stores" button, I get the message: "No stores are linked to this account. To see the associated stores, please log in with the correct user account of the association."

![2024-07-13 16_07_36-Settings](https://github.com/user-attachments/assets/0ca77c4c-360f-49e2-a180-bd74cbb1036d)

Data sharing is also disabled: "An error has occurred while initializing the data sharing component. Please try again later. You can contact the module author if the problem persists."

Does anyone have any idea what to do? I can't find anything that points me in the right direction to solve this problem.

In the copy environment, I created another account, linked the store, unlinked it, linked it again, and deleted the account to see if I could relink it, but now I have the same problems in the copy. I can't provide another account to link Mollie/the shop to another account.

So how can I link my shop again to an prestashop account, and how to enable share data.

Thanks in advance!

**Comment by justelis22** [comment]
Hi there @gsnel,

These modules are maintained by PrestaShop and Mollie does not affect the functionality.

My recommendation would be to reach out to PS support and resolve this account issue.

Let me know if there is anything else I can help with!

Best Regards,
Invertus Support team.
