### ISSUE TITLE
With a subscription, the customer is charged even if the product is out of stock

### ISSUE THREAD

**Issue by zorrobiwan** [mollie/PrestaShop#974]
### Expected behavior
If the product is out of stock, order is not passed and customer should not be charged

### Actual behavior
If a product is out of stock, order is NOT created in PrestaShop backoffice, but customer is charged as a payment is initiated in Mollie backoffice 😳

### Steps to reproduce the behavior
Subscribe to a product with few stock. On next subscription occurence, client will be charged in the Mollie backoffice but no order will be created.

### Environment
* PrestaShop version: 1.7.7.6
* Mollie module version: 6.2.2
* PHP version: 7.3.31-1~deb10u7

**Comment by justelis22** [comment]
Hi there,

We will check this issue and I will get back to you as soon as more details.

Thank you for your patience!

--
Best Regards,
Invertus Support team.

**Comment by zorrobiwan** [comment]
some more information about the issue

First (non recurrent) command 
![image](https://github.com/user-attachments/assets/4661962a-5cf4-4160-9cb6-c352a6d660e4)

First (recurrent) command initiated by the Mollie backend
![image](https://github.com/user-attachments/assets/5d7a2dcc-3bda-4314-97e5-783ae7ba4b12)

we can see payment is initiated, credit card is debited then webhook is called but in error each time (no stock)
Payment stays "payed" which should not be the case

If I read well the documentation
https://docs.mollie.com/reference/webhooks#retry-schema
it seems nothing is planned on Mollie side to cancel or review a payment if the webhook finally fails.

This is unfortunately inconceivable for us and represents a NOGO for our client

Do you have any follow-up to give to this?

Thanks

**Comment by justelis22** [comment]
Hi there @zorrobiwan,

Forwarded everything to the Mollie team and our developer.

We will check this and discuss internally before coming back to you.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @zorrobiwan, thanks for waiting!

I've spoken to the Mollie team about this and all their integrations that have built a subscription functionality are built this way. For Mollie, it's out of their scope of whether the product is available or not. 
At least for now, it is the merchant's responsibility to make sure there are enough goods available for the subscription. 

TL:DR - It’s by design and intended as it is.

If you have any other questions, please let me know!

Best Regards,
Invertus Support team.

**Comment by zorrobiwan** [comment]
thanks for the answer even if it doesn't satisfy me

I'm also an IT guy and I know that it's pretty easy to answer "as designed" when a problem is complex to solve.

And it's pretty crazy that in a transactional financial universe, we debit a credit card without ANY control over the possible success of the operation linked to this debit

Anyway.

If this can't be done on the backend side (or in collaboration with), maybe you could consider stronger information on the PrestaShop side.
Currently, the module records an error in the PrestaShop log system (cfr MollieSubscriptionWebhookModuleFrontController). But I can't see an admin checking every morning if an order has failed due to lack of stock.

Couldn't you at least add the possibility of an email alert?

Big thanks for the follow-up

**Comment by justelis22** [comment]
@zorrobiwan Hi there, thanks for waiting.

I have forwarded the information to the Mollie team.

Once I have more details, I will post an update here.

If you have any questions, please let me know!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @zorrobiwan,

We will update the documentation to cover this and provide the steps to handle this and avoid problems in the future.

As for handling it, our recommendation would be to set up the native PrestaShop module Mail Alerts, which has the functionality to send emails to the merchant when the product stock reaches a defined number of times.
It would be redundant to implement email notifications on Mollie's side when PS already offers this functionality:
![image](https://github.com/user-attachments/assets/7b7e0ba4-c789-4cb4-b167-48cbd1bde91c)

This will help you to manage your subscriptions, as at the moment, Mollie is not planning on making improvements for this case.

If you have any questions, please let me know!

Best Regards,
Invertus Support team.

**Comment by zorrobiwan** [comment]
Thx for your reply

Of course my client implements the Mail Alerts module.

What I'm asking is to be warn about lack of stock by Mollie Module. It's to be warned (more than with a simple log) that a payement initiated on the backend side failed for any reason (which could be a lack of stock)!

Anyway, we'll find and implement our own solution (or use another payment provider)
