### ISSUE TITLE
interface LoggerInterface extends \Psr\Log\LoggerInterface ??

### ISSUE THREAD

**Issue by ijzershop** [mollie/PrestaShop#985]
<?php
/**
 * Mollie       https://www.mollie.nl
 *
 * @author      Mollie B.V. <info@mollie.nl>
 * @copyright   Mollie B.V.
 * @license     https://github.com/mollie/PrestaShop/blob/master/LICENSE.md
 *
 * @see        https://github.com/mollie/PrestaShop
 * @codingStandardsIgnoreStart
 */

namespace Mollie\Logger;

interface LoggerInterface extends \Psr\Log\LoggerInterface
{
}

Serious???

**Comment by justelis22** [comment]
Hi there,

We will check this issue and I will get back to you as soon as more details.

Thank you for your patience!

--
Best Regards,
Invertus Support team.

**Comment by ijzershop** [comment]
Don't need to wait for that, if you don't see the error in this. I will fix the errors myself after your upgrades, or start using an other service.  It's sad to see a company like invertus produces such code but after 2 years  i accept it will not be any better in the future.

**Comment by justelis22** [comment]
Hi there @ijzershop,

Could you help us to understand if this is causing any issues in your shop?

This part of the code should not make any impact for you, so I would appreciate additional information.

Best Regards,
Invertus Support team.
