### ISSUE TITLE
Status change causes confusion

### ISSUE THREAD

**Issue by mariuszsienkiewicz** [mollie/PrestaShop#991]
We have noticed that Mollie updates statuses through requests to our PrestaShop system. While this provides valuable information, it makes it challenging for our warehouse staff to keep up with the changes. Please see the screenshot below:

![image](https://github.com/user-attachments/assets/7d570915-2fea-4a1e-ab30-0ce8903eb18d)

It updates the status even after the package has been marked as "Sent" ("Wysłane") (twice!), which disrupts the warehouse workflow. Is there any way to disable this update?

### Environment
* PrestaShop version: 8.1.7
* Mollie module version:  6.2.3
* PHP version: 8.1

**Comment by justelis22** [comment]
Hi there @mariuszsienkiewicz,

We have checked this issue and tried to recreate it locally on our environments, however, everything seems to be working fine, but we were not able to prompt this issue.

That being said, we will need access to your shop to debug the issue. Can you provide the Back Office and FTP credentials?
If you have a development environment, that would be even better. That way, we can work on the issue without disturbing the live store.

You can add the credentials here - https://privatebin.net/ and share the link via email at support@invertus.eu

Also, please attach logs from the Mollie dashboard.

Thanks!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
@mariuszsienkiewicz,

As this was not updated for a couple of weeks, I am closing the issue.

If you decide to get back to it, please post a reply here and we will continue from where we left of.

If you have any questions, please let me know!

Best Regards,
Invertus Support team.
