### ISSUE TITLE
Order payment mismatch due to the `ps_mollie_payments` ordering 

### ISSUE THREAD

**Issue by mariuszsienkiewicz** [mollie/PrestaShop#994]
### Expected behavior

When the user changes the payment method, the method ultimately used for payment should take priority.

### Actual behavior

The Mollie block at the bottom of the order page displays the most recently modified payment method for the order, rather than the payment method ultimately used to complete the order.

![image](https://github.com/user-attachments/assets/75dcb009-1444-41d5-80b3-f980ba32cc38)

As you can see, the latest payment update appears as the first row in the results. This is the data used by the module to display the Mollie block on the BO order page. Unfortunately, this is not the payment method that was actually used to pay for the order; it’s the second one. This behavior causes issues in the BO, as you cannot process refunds or ship products using the Mollie block because the wrong payment method is being referenced.

This issue occurs across all our clients' shops. For orders where the block references the wrong payment, we have to manually update the `created_at` column to make the correct payment appear as the "newest" one. In the example order shown in the screenshot, we had to manually change the `created_at` date from `2024-11-07 12:28:27` to `2024-11-10 12:28:27`. After making this adjustment, we were able to click the Ship All button.

### Environment
* PrestaShop version: 8.1.7
* Mollie module version: 6.2.3
* PHP version: 8.1

**Comment by justelis22** [comment]
Hi there,

We will check this issue and I will get back to you as soon as more details.

Thank you for your patience!

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @mariuszsienkiewicz,

Could you please provide more information about the circumstances of the order appearing in the back office when it is not paid or authorized and does not have an order ID?

When an order is created in the back office, the cart should disappear, and no new entries will be in this table.

Can you please let me know how the issue can be recreated? Does it happen for all of the orders or only specific ones?

Please attach some screenshots or a video recording of the error.

Thanks!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
As this was not updated for a couple of weeks, I am closing the issue.

If you decide to get back to it, please post a reply here and we will continue from where we left off.

Best Regards,
Invertus Support team.
